### ISSUE TITLE
Is \TIGRE\Python\tigre\demos\.ipynb_checkpoints needed in the repo?

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#100]
@reubenlindroos Is this folder needed? It looks like just metadata of the ipyton notebooks. It seems to generate merge conflicts because the number of runs of the notebooks is recorded and obviously everyone will have a different one.

**Comment by reubenlindroos** [comment]
Hi Ander. I dont think so. Ill run some tests and remove it if that is the case.

**Comment by reubenlindroos** [comment]
I added .ipynb_checkpoints to the .gitignore file and removed it from the repo. You shouldnt have that issue anymore.
