### ISSUE TITLE
python code is non PEP8 compliant 

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#106]
Modify python code to have correct style.

**Comment by Kaushl2208** [comment]
@AnderBiguri @reubenlindroos  Is the issue still in progress?? If not, I would like to work on it.

**Comment by AnderBiguri** [comment]
Hi @Kaushl2208 , 
The development is mainly being done in a branch, pydev. You are welcomed to fork that branch and make pull requests, as we are not currently attempting to fix it.

**Comment by Kaushl2208** [comment]
Hey, @AnderBiguri  thanks for letting me know. I was looking to help. I will make a PR regarding this issue. And is there anything else I can help with?

**Comment by AnderBiguri** [comment]
I will check if there is something we can delegate and will let you know
next week. Thanks for the help!

**Comment by AnderBiguri** [comment]
@Kaushl2208  if you want to give a hand we do have a relatively big issue we do not know how to fix: Making the python/CUDA code compile and run on Windows.

**Comment by Kaushl2208** [comment]
@AnderBiguri  I would love to help but, I am not a Windows user and not familiar with its complexes.
