### ISSUE TITLE
Matlab gives error in compile

### ISSUE THREAD

**Issue by saluksic** [CERN/TIGRE#113]
## Expected Behavior
Complie.m work

## Actual Behavior
Compile.m gives the below error in Matlab

## Code to reproduce the problem (If applicable)
>> Compile
MEX configured to use 'Microsoft Visual C++ 2013 (C)' for C language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
	 variables with more than 2^32-1 elements. You will be required
	 to update your code to utilize the new API.
	 You can find more information about this at:
	 https://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN
Compiling TIGRE source...
This may take a couple of minutes....
Error using mex
No supported compiler was found. For options, visit
https://www.mathworks.com/support/compilers.

Error in Compile (line 47)
        mex -largeArrayDims ./Source/Ax_mex.cpp ./Source/ray_interpolated_projection.cu
        ./Source/Siddon_projection.cu ./Source/ray_interpolated_projection_parallel.cu
        ./Source/Siddon_projection_parallel.cu -outdir ./Mex_files/win64
 
>> 
```

```

## Specifications 

  - MATLAB version: R2018a
  - OS: Windows 10
  - CUDA version: 10.1
I'm using Visual Studo 2013 with the C++ parts added

**Comment by AnderBiguri** [comment]
Hi @saluksic ,

There is a work-in-progress tutorial and debugging help page hidden in a branch now, here is the link:

https://github.com/CERN/TIGRE/blob/frontispiece/Frontispiece/MATLAB_installation.md

Have a look at the steps for installation and debugging that are there and let me know how it goes.

Ander

**Comment by saluksic** [comment]
Thanks for the quick reply!

I have Matlab R2018a. Is that okay, or should I try to get one of the versions listed in the table on the link you sent?

**Comment by AnderBiguri** [comment]
2018a should be fine

**Comment by saluksic** [comment]
Ander,

I changed the file name of mex_CUDA_win64_MVS2013.xml to mex_CUDA_win64.xml in the TIGRE 1.4 folder and that made a difference. When I compiled compile.m in MATLAB I got the following response:

>> Compile
MEX configured to use 'Microsoft Visual C++ 2013 (C)' for C language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
               variables with more than 2^32-1 elements. You will be required
               to update your code to utilize the new API.
               You can find more information about this at:
               https://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.

To choose a different language, select one from the following:
mex -setup C++
 mex -setup FORTRAN
Compiling TIGRE source...
This may take a couple of minutes....
Building with 'NVIDIA CUDA Compiler'.
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection.cu(280): warning: variable "fits_in_memory" was set but never used
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection.cu(387): warning: variable "size_image" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection.cu(280): warning: variable "fits_in_memory" was set but never used
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection.cu(387): warning: variable "size_image" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection.cu(280): warning: variable "fits_in_memory" was set but never used
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection.cu(387): warning: variable "size_image" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection.cu(280): warning: variable "fits_in_memory" was set but never used
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection.cu(387): warning: variable "size_image" was declared but never referenced

C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection_parallel.cu(144): warning: variable "azm" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection_parallel.cu(145): warning: variable "azM" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection_parallel.cu(144): warning: variable "azm" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection_parallel.cu(145): warning: variable "azM" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection_parallel.cu(144): warning: variable "azm" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection_parallel.cu(145): warning: variable "azM" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection_parallel.cu(144): warning: variable "azm" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/Siddon_projection_parallel.cu(145): warning: variable "azM" was declared but never referenced

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\Ax_mex.exp

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\Ax_mex.exp

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\Ax_mex.exp

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\Ax_mex.exp

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\Ax_mex.exp

MEX completed successfully.
Building with 'NVIDIA CUDA Compiler'.
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(211): warning: variable "xyzOffset" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(399): warning: variable "source" is used before its value is set
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(378): warning: variable "sinalpha" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(378): warning: variable "cosalpha" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(441): warning: variable "source" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(211): warning: variable "xyzOffset" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(399): warning: variable "source" is used before its value is set
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(378): warning: variable "sinalpha" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(378): warning: variable "cosalpha" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(441): warning: variable "source" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(211): warning: variable "xyzOffset" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(399): warning: variable "source" is used before its value is set
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(378): warning: variable "sinalpha" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(378): warning: variable "cosalpha" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(441): warning: variable "source" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(211): warning: variable "xyzOffset" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(399): warning: variable "source" is used before its value is set
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(378): warning: variable "sinalpha" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(378): warning: variable "cosalpha" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(441): warning: variable "source" was declared but never referenced
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/voxel_backprojection_parallel.cu(399): warning: variable "source" is used before its value is set

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\Atb_mex.exp

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\Atb_mex.exp

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\Atb_mex.exp

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\Atb_mex.exp

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\Atb_mex.exp

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\Atb_mex.exp

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\Atb_mex.exp

MEX completed successfully.
Building with 'NVIDIA CUDA Compiler'.
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV.cu(188): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV.cu(235): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV.cu(188): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV.cu(235): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV.cu(188): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV.cu(235): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV.cu(188): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV.cu(235): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\minTV.exp

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\minTV.exp

MEX completed successfully.
Building with 'NVIDIA CUDA Compiler'.
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV2.cu(214): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV2.cu(261): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV2.cu(214): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV2.cu(261): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV2.cu(214): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV2.cu(261): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV2.cu(214): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
C:/Users/luks430/Documents/TIGRE-1.4/TIGRE-1.4/MATLAB/Source/POCS_TV2.cu(261): warning: function "__shfl_down(float, unsigned int, int)"
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_30_intrinsics.hpp(207): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\AwminTV.exp

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\AwminTV.exp

MEX completed successfully.
Building with 'NVIDIA CUDA Compiler'.
Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\tvDenoise.exp

Could Not Find C:\Users\luks430\Documents\TIGRE-1.4\TIGRE-1.4\MATLAB\Mex_files\win64\tvDenoise.exp

MEX completed successfully.
Compilation complete

I looked in the TIGRE MATLAB folder under Mex_Files\win64 and found a Atb_mex.mexw64, AwminTV.mexw64, AX_mex.mexw64, minTV.mexw64, and tvDenoise.mexw64, but I didn’t see any .exp files corresponding to those.

I ran the d03_generateData.m and got the following error:
>> d03_generateData
Undefined function or variable 'headPhantom'.

Error in d03_generateData (line 51)
head=headPhantom(geo.nVoxel);

Then I checked the mex -setup -v and got this:
>> mex -setup -v
Verbose mode is on.
... Looking for compiler 'Intel C++ Composer XE 2013 with Microsoft Visual Studio 2013 (C)' ...
... Looking for environment variable 'ICPP_COMPILER14' ...No.
... Looking for environment variable 'ICPP_COMPILER13' ...No.
Did not find installed compiler 'Intel C++ Composer XE 2013 with Microsoft Visual Studio 2013 (C)'.
... Looking for compiler 'Intel Parallel Studio XE 2015 with Microsoft Visual Studio 2013 (C)' ...
... Looking for environment variable 'ICPP_COMPILER15' ...No.
Did not find installed compiler 'Intel Parallel Studio XE 2015 with Microsoft Visual Studio 2013 (C)'.
... Looking for compiler 'Intel Parallel Studio XE 2015 with Microsoft Visual Studio 2015 (C)' ...
... Looking for environment variable 'ICPP_COMPILER15' ...No.
Did not find installed compiler 'Intel Parallel Studio XE 2015 with Microsoft Visual Studio 2015 (C)'.
... Looking for compiler 'Intel Parallel Studio XE 2016 with Microsoft Visual Studio 2013 (C)' ...
... Looking for environment variable 'ICPP_COMPILER16' ...No.
Did not find installed compiler 'Intel Parallel Studio XE 2016 with Microsoft Visual Studio 2013 (C)'.
... Looking for compiler 'Intel Parallel Studio XE 2016 with Microsoft Visual Studio 2015 (C)' ...
... Looking for environment variable 'ICPP_COMPILER16' ...No.
Did not find installed compiler 'Intel Parallel Studio XE 2016 with Microsoft Visual Studio 2015 (C)'.
... Looking for compiler 'Intel Parallel Studio XE 2017 with Microsoft Visual Studio 2013 (C)' ...
... Looking for environment variable 'ICPP_COMPILER17' ...No.
Did not find installed compiler 'Intel Parallel Studio XE 2017 with Microsoft Visual Studio 2013 (C)'.
... Looking for compiler 'Intel Parallel Studio XE 2017 with Microsoft Visual Studio 2015 (C)' ...
... Looking for environment variable 'ICPP_COMPILER17' ...No.
Did not find installed compiler 'Intel Parallel Studio XE 2017 with Microsoft Visual Studio 2015 (C)'.
... Looking for compiler 'Intel Parallel Studio XE 2017 with Microsoft Visual Studio 2017 (C)' ...
... Looking for environment variable 'ICPP_COMPILER17' ...No.
Did not find installed compiler 'Intel Parallel Studio XE 2017 with Microsoft Visual Studio 2017 (C)'.
... Looking for compiler 'MinGW64 Compiler (C)' ...
... Looking for environment variable 'MW_MINGW64_LOC' ...No.
Did not find installed compiler 'MinGW64 Compiler (C)'.
... Looking for compiler 'Microsoft Visual C++ 2012 (C)' ...
... Looking for registry setting 'HKLM\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 11.0 ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 11.0 ...No.
... Looking for registry setting 'HKLM\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VS7' 11.0 ...Yes ('C:\Program Files (x86)\Microsoft Visual Studio 11.0\').
... Looking for file 'C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\amd64\cl.exe' ...No.
Did not find installed compiler 'Microsoft Visual C++ 2012 (C)'.
... Looking for compiler 'Microsoft Visual C++ 2013 (C)' ...
... Looking for registry setting 'HKLM\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 12.0 ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 12.0 ...No.
... Looking for registry setting 'HKLM\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VS7' 12.0 ...Yes ('C:\Program Files (x86)\Microsoft Visual Studio 12.0\').
... Looking for file 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64\cl.exe' ...Yes.
... Looking for folder 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC' ...Yes.
... Looking for registry setting 'HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.1' InstallationFolder ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.1' InstallationFolder ...No.
... Looking for registry setting 'HKLM\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v8.1' InstallationFolder ...Yes ('C:\Program Files (x86)\Windows Kits\8.1\').
... Looking for registry setting 'HKLM\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 12.0 ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 12.0 ...No.
... Looking for registry setting 'HKLM\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VS7' 12.0 ...Yes ('C:\Program Files (x86)\Microsoft Visual Studio 12.0\').
... Looking for registry setting 'HKLM\SOFTWARE\Microsoft\VisualStudio\SxS\VC7' 12.0 ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Microsoft\VisualStudio\SxS\VC7' 12.0 ...No.
... Looking for registry setting 'HKLM\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VC7' 12.0 ...Yes ('C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\').
... Looking for environment variable 'VS120COMNTOOLS' ...Yes ('C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\').
... Looking for file 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe' ...Yes.
... Looking for registry setting 'HKLM\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 12.0 ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 12.0 ...No.
... Looking for registry setting 'HKLM\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VS7' 12.0 ...Yes ('C:\Program Files (x86)\Microsoft Visual Studio 12.0\').
... Looking for file 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat' ...Yes.
... Looking for folder 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC' ...Yes.
Found installed compiler 'Microsoft Visual C++ 2013 (C)'.
... Looking for compiler 'Microsoft Visual C++ 2015 (C)' ...
... Looking for registry setting 'HKLM\SOFTWARE\Microsoft\VisualStudio\SxS\VC7' 14.0 ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Microsoft\VisualStudio\SxS\VC7' 14.0 ...No.
... Looking for registry setting 'HKLM\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VC7' 14.0 ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VC7' 14.0 ...No.
Did not find installed compiler 'Microsoft Visual C++ 2015 (C)'.
... Looking for compiler 'Microsoft Visual C++ 2017 (C)' ...
... Looking for registry setting 'HKLM\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 15.0 ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 15.0 ...No.
... Looking for registry setting 'HKLM\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VS7' 15.0 ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VS7' 15.0 ...No.
Did not find installed compiler 'Microsoft Visual C++ 2017 (C)'.
... Looking for compiler 'Microsoft Visual C++ 2013 (C)' ...
... Looking for registry setting 'HKLM\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 12.0 ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 12.0 ...No.
... Looking for registry setting 'HKLM\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VS7' 12.0 ...Yes ('C:\Program Files (x86)\Microsoft Visual Studio 12.0\').
... Looking for file 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64\cl.exe' ...Yes.
... Looking for folder 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC' ...Yes.
... Looking for registry setting 'HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.1' InstallationFolder ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.1' InstallationFolder ...No.
... Looking for registry setting 'HKLM\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v8.1' InstallationFolder ...Yes ('C:\Program Files (x86)\Windows Kits\8.1\').
... Looking for registry setting 'HKLM\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 12.0 ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 12.0 ...No.
... Looking for registry setting 'HKLM\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VS7' 12.0 ...Yes ('C:\Program Files (x86)\Microsoft Visual Studio 12.0\').
... Looking for registry setting 'HKLM\SOFTWARE\Microsoft\VisualStudio\SxS\VC7' 12.0 ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Microsoft\VisualStudio\SxS\VC7' 12.0 ...No.
... Looking for registry setting 'HKLM\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VC7' 12.0 ...Yes ('C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\').
... Looking for environment variable 'VS120COMNTOOLS' ...Yes ('C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\').
... Looking for file 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe' ...Yes.
... Looking for registry setting 'HKLM\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 12.0 ...No.
... Looking for registry setting 'HKCU\SOFTWARE\Microsoft\VisualStudio\SxS\VS7' 12.0 ...No.
... Looking for registry setting 'HKLM\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VS7' 12.0 ...Yes ('C:\Program Files (x86)\Microsoft Visual Studio 12.0\').
... Looking for file 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat' ...Yes.
... Looking for folder 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC' ...Yes.
Found installed compiler 'Microsoft Visual C++ 2013 (C)'.
MEX configured to use 'Microsoft Visual C++ 2013 (C)' for C language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
               variables with more than 2^32-1 elements. You will be required
               to update your code to utilize the new API.
               You can find more information about this at:
               https://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.

To choose a different language, select one from the following:
mex -setup C++
 mex -setup FORTRAN

I took the last lines ending in ‘yes’ as a good sign.

MATLAB found the CUDA path alright:
>> getenv('CUDA_PATH')

ans =

    'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1'

But it couldn’t find the Visual Studio path:
>> getenv(VS120COMNTOOLS)
Undefined function or variable 'VS120COMNTOOLS'.

Defining the path didn’t seem to work:
>> setenv('VS120COMNTOOLS','C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools')
>> getenv(VS120COMNTOOLS)
Undefined function or variable 'VS120COMNTOOLS'.

I’m going to try for a complete re-install of Visual Studio 2013 and see if that helps.

Thanks again for the replies. I’m very excited check out the reconstruction methods in your toolkit, as I have pretty undersampled data. It’s been a headache getting CUDA and the old Visual Studio installed and working, so it’s a big relief to have someone who can help me!

Steven

**Comment by AnderBiguri** [comment]
It looks like it compiled correctly, you may have just missed to initialize Tigre before running the code. Calling InitTIGRE before the demos should suffice @salujsic

**Comment by saluksic** [comment]
Ander, I ran “InitTIGRE” and then ran the demo, and it worked! Thanks a million for the help.

Thank you very much, I’m very excited to start trying to reconstruct some of my data. Are there any tutorials or walk throughs I can avail myself of now that the toolkit is working?

**Comment by AnderBiguri** [comment]
Hi Steven @saluksic ,

I suggest having a look at the first demo, and understanding how the geometries are defined and how algorithms called. Once you go trough the first 4 or 5 demos you should be practically ready to input any type of data. If you have any problem do not hesitate to contact me and I may be able to give you a hand.

I will close this issue now.
