### ISSUE TITLE
Build fails on CUDA 9.2  error: identifier "cudaDevAttrHostRegisterSupported" 

### ISSUE THREAD

**Issue by buzmakov** [CERN/TIGRE#116]
## Expected Behavior
Successful build from sources

## Actual Behavior
Build fails on last Ubuntu 18.04 LTS with default CUDA installation (using apt-get)
Command:
```CUDAHOME=/usr python setup.py develop```

Get error during building
```
Lots of lines
.....
tigre/Source/voxel_backprojection.cu(322): error: identifier "cudaDevAttrHostRegisterSupported" is undefined
```

## Code to reproduce the problem (If applicable)

```

```

## Specifications 

  - MATLAB version: not installed
  - OS: Ubuntu 18.04 x64 LTS
  - CUDA version: 9.1

**Comment by AnderBiguri** [comment]
Hi Alexei,
Ah, we just pushed a new branch, but was mostly focused on the matlab
version. We are working on a proper python version but there is still a bit
to go. If you download the pydev branch version of the code, that
should work. It's not the most efficient, but it works.
I will try to fix the master branch sometime next week, as there should not
be a bug here anyway.
Apologies
Ander

**Comment by AnderBiguri** [comment]
Wait, you say in the title cuda 9.2 but in the body cuda 9.1. The 9.2
version is necessary. You can also use cuda 10.

**Comment by buzmakov** [comment]
Thank you!
I'll try use CUDA 9.2
