### ISSUE TITLE
BIG PROJECT: Translate TIGRE to python

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#12]
We are looking for people to help translate TIGRE to python.
This way we will not only promote the open source movement, but we will allow centers such as hospitals to have easier access to TIGRE, thus potentially improving patient treatment. 

Any help is good help!

**Comment by jpnorair** [comment]
I might be interested to help.  In particular I have some experience building fast C modules for Python, and getting them to import, etc.

**Comment by AnderBiguri** [comment]
Hi @jpnorair ,
Thats great! You help would be really appreciated in anything you could contribute to! 

 Let me go directly to the point:
There are 3 main python->C modules that would need to be created: `Ax()` `Atb()` and `minTV()`. These 3 functions will be taking python variables, error check them and pass them to C++ (CUDA). The first 2, are a the most important functions of TIGRE, as every algorithm uses them at least once per iteration. These are the functions with highest priority.  

However, there will be probably 2 students working on this during the following year, starting in a month. AFAIK neither of them with C/python skills. But, this means that they will need `Ax()` and `Atb()` to be working relatively soon, thus, either their first task is to code them, or they need to be coded by the time they start working on TIGRE. This is a problem, because I can not ask you to commit yourself to have these functions finished, and even less to do so in less than a month! 

Thus: If you think that you have time/want to do it in a month go for it and try do `Ax() `and `Atb()`. But I am assuming you probably can't. Therefore, the best thing to work with, if you want to help without time constrains, would be to either wrap `minTV()`, or  just start translating functions from the "Utilities" folder, such as the `plotImg()`, `plotProj()` , anything in Quality_measures, ....

Let me know what you think. If you have an alternative vision on this, or think that can help in something that I haven't though of, please speak your mind.
Of course you are free to do as much and as little as you wish!! Just that `Ax()` and `Atb()` are quite special in this case!

Best,
Ander

**Comment by AnderBiguri** [comment]
This task is almost finished now.
