### ISSUE TITLE
Init_multigrid should be made more conventional and fucntionality with other algorithms

### ISSUE THREAD

**Issue by reubenlindroos** [CERN/TIGRE#126]

**Comment by AnderBiguri** [comment]
I am bit sure about this one. Yes the error is correct, but I am thinking
that maybe this initialization procedure is not mathematically sounds, so I
am in doubt of completely removing it...  Don't work too much on it yet.

**Comment by AnderBiguri** [comment]
Unsure*

**Comment by reubenlindroos** [comment]
@AnderBiguri It looks like its not going to be included in the wrapper for the moment, but there was some interest in the method.
