### ISSUE TITLE
TIGRE MATLAB - CGLS returning reconstruction with half of the values = 0

### ISSUE THREAD

**Issue by reubenlindroos** [CERN/TIGRE#139]
## Expected Behavior
To return a full [2000, 2000 2000] reconstruction of the PTB phantom (with 58 projections). FDK is able to do this with with exactly the same geometry

## Actual Behavior

Returns an array with half the values = 0 along the 3rd dimension. 

## Code to reproduce the problem (If applicable)

![cgls_long_58proj](https://user-images.githubusercontent.com/25688713/62944112-ec329d80-bdd3-11e9-8f64-c41c007f6d38.png)
(on laminography2)
```
fpath = '~/SCANS/PTB/20190312_HUTCH_2220_HT_PTB_Long_002 [2019-03-14 12.05.10]';
[proj,angles] = loadNikonData(fpath,angles,58,whitelevel,'all',false);
geo.COR = 15*geo.dVoxel(1);
imgOut = CGLS(proj,geo,angles',10);
```

## Specifications 

  - MATLAB version: 2018a
  - OS: Linux
  - CUDA version: NVIDIA-SMI 430.40       Driver Version: 430.40       CUDA Version: 10.1

**Comment by reubenlindroos** [comment]
![backproj_matched_58](https://user-images.githubusercontent.com/25688713/62945435-a2978200-bdd6-11e9-9fb5-2f11b24597e2.png)

running only matched backprojection with geometry: 
![geo](https://user-images.githubusercontent.com/25688713/62945927-9d870280-bdd7-11e9-883c-e9b7dad10db2.png)

**Comment by AnderBiguri** [comment]
Can you copypaste the geometry so I can copy it?

**Comment by reubenlindroos** [comment]
Is there a function to print the structure as a string?

**Comment by AnderBiguri** [comment]
Attatch a .mat file.
