### ISSUE TITLE
Matlab 2012 x64 and vs2010, Cuda 7.5

### ISSUE THREAD

**Issue by gudsqa** [CERN/TIGRE#14]
Anyone tried compiling in this combination?  Thanks.

**Comment by AnderBiguri** [comment]
Hi @gudsqa ,
This is not a forum, but an Issue tracker. Do you have any specific problems trying this?
Ander

**Comment by gudsqa** [comment]
Sorry. No. I asked because this combination is the tools we have. Just want to know if anyone have tried.

Could you pose some platform specification that works.

BTW, this is a great work. I am in radiation oncology which use CBCT for patient positioning daily.

Thanks.

On 28/09/2016 09:26, AnderBiguri wrote:

Hi @gudsqa<https://github.com/gudsqa> ,
This is not a forum, but an Issue tracker. Do you have any specific problems trying this?
Ander

-

**Comment by AnderBiguri** [comment]
Hi @gudsqa  

I am glad that you like it, radiation oncology was our first though when we designed this toolbox! Keep tuned for future work (really soon) into motion removal in X-rays, where we are achieving to remove motion artefacts. 

About the requirements: Yes, its should work. Unfortunately I do not have access to that MATLAB version, but there should be (in theory) no problem across platforms/versions. In practice, there are sometimes, but generally they are easy to solve, and I will make my best to solve them if they are incompatibilities that TIGRE itself has.  

I will close the Issue on Github, but please feel free to continue chatting here, or send me an email to a.biguri@bath.ac.uk. 

Best,
Ander

**Comment by gudsqa** [comment]
Thanks.

A few topics are quite interesting when comes to CBCT in radiation
oncology. Like 4-D CBCT (lung and liver), motion artifact (abdomen and
pelvic region) and metal artifact (from artificial implant). I am
looking forward for your new release.

--An Qin

**Comment by AnderBiguri** [comment]
Yes indeed!
We beliebe (yet to test with real data)  that iterative algorithms in TIGRE
will significantly reduce the metal artefacts in imaging, without any
additional processing.

Additionally,  our future work is 4DCBCT without the need of data binning.
We believe we are capable of creating high quality videos using the same
data that nowadays is used for the treatment CBCT.  We are currently
refining the lasts tests on this and we will try to publish this (and add
it to TIGRE) soon.

Ander
