### ISSUE TITLE
Detector rotation not working

### ISSUE THREAD

**Issue by WKrauze** [CERN/TIGRE#142]
## Expected Behavior
I would expect that after specifying detector rotation array I will see a difference in generated projections.

## Actual Behavior
Whether I specify detector rotation matrix or not there is no difference in generated projections. Checked with 'parallel' and 'cone' modes. When I plot the difference between projections calculated with and without rotated detector I get matrix of zeros.

## Code to reproduce the problem (If applicable)

```
nangles = 20
angles = np.linspace(-np.pi/2, np.pi/2, nangles, dtype=np.float32)

geo = tigre.geometry(mode='parallel', default=True, nVoxel=np.array([250, 250, 250]))
geo.DSO = 1000
geo.DSD = 2000
geo.rotDetector = np.array((2, 1, 1))

geo2 = tigre.geometry(mode='parallel', default=True, nVoxel=np.array([250, 250, 250]))
geo2.DSO = 1000
geo2.DSD = 2000
geo2.rotDetector = np.array((0, 0, 0))

head = data_loader.load_head_phantom(geo.nVoxel)
proj = tigre.Ax(head, geo, angles)
proj2 = tigre.Ax(head, geo2, angles)

plt.ion()
for ii in range(nangles):
    plt.imshow(proj[ii, :, :]-proj2[ii, :, :])
    plt.show()
    plt.pause(0.0001)
```

## Specifications 

  - Python version: 2.7 (tested also on 3.6)
  - OS: Linux Manjaro 18.1.1
  - CUDA version: 10.1

**Comment by AnderBiguri** [comment]
@pewter-cauldron I'll have a look when I can. Can you, however, test the same thing but with angles in radians just to make sure.

**Comment by pewter-cauldron** [comment]
@AnderBiguri Thank you. I was all the time specifying this value in radians - I tested different values, also the absurd ones as in the example (for which I would still expect some effect). Just now I rerun the same piece of code but for:
`geo.rotDetector = np.array((.2, .1, .1))`
with the same effect (no effect).

**Comment by AnderBiguri** [comment]
@pewter-cauldron Sure, fantastic, thanks for the test. I will try to give it a look. I suspect its just the matter with python-CUDA communication, somewhere on the way the values may be dropped. Definitely its not in the source code, as its the same one as MATLAB and it works there. 
I won't be able to have a look at this immediately, so If you feel adventurous you can try to follow the  calls inside tigre.Ax() and its likely there is a minor bug where the values are not being parsed.

**Comment by AnderBiguri** [comment]
I think I found it: 

https://github.com/CERN/TIGRE/blob/master/Python/tigre/Source/_types.pxd#L138

Instead of copying the input values, they are being set to zero.  Clearly a bug. Solution should be easy, if you do change it before I have time for it, please submit a pull request to be fixed in the main code.

**Comment by pewter-cauldron** [comment]
Thank you for your help. I will take a look at that but I can't promise that I'm capable of repairing that.

**Comment by pewter-cauldron** [comment]
@AnderBiguri So I tried to change the -types.pxd file. I modified the lines 139 to 141:
```
c_geom.dRoll[i] = p_geometry.rotDetector[i][0]
c_geom.dPitch[i] = p_geometry.rotDetector[i][1]
c_geom.dYaw[i] = p_geometry.rotDetector[i][2]
```
and recompiled the package. Unfortunately this didn't change anything and the rotation of a detector still does not work, so I guess something else must also be changed.
PS I made sure that the recompilation uses the modified file. Tested of Python 2.7 and 3.6.

**Comment by AnderBiguri** [comment]
@pewter-cauldron hum, I though that was the only thing that would be needed. I'll try to check it from my side, see what else I can figure out. Thanks for the help!

**Comment by genusn** [comment]
## Summary
WKrauze 's modification worked fine for 'cone' mode.

## Expected Behavior
Works for both 'cone' and 'parallel' mode.

## Actual Behavior
Works only for 'cone' mode.
The rotation of the detector does not work in the 'parallel' mode.

## Code
```
nangles = 50
angles = np.linspace(-np.pi/2, np.pi/2, nangles, dtype=np.float32)

dRot = 45

geo = tigre.geometry(mode='parallel', default=True, nVoxel=np.array([250, 250, 250]))
geo.dDetector = np.array((0.5, 0.5))*3
geo.sDetector = geo.dDetector * geo.nDetector
geo.DSO = 500
geo.DSD = 700
geo.rotDetector = np.array((0, 0, dRot*np.pi/180))

geo2 = tigre.geometry(mode='parallel', default=True, nVoxel=np.array([250, 250, 250]))
geo2.dDetector = np.array((0.5, 0.5))*3
geo2.sDetector = geo2.dDetector * geo2.nDetector
geo2.DSO = 500
geo2.DSD = 700
geo2.rotDetector = np.array((0, 0, 0))

geo3 = tigre.geometry(mode='cone', default=True, nVoxel=np.array([250, 250, 250]))
geo3.dDetector = np.array((0.5, 0.5))*3
geo3.sDetector = geo3.dDetector * geo3.nDetector
geo3.DSO = 500
geo3.DSD = 700
geo3.rotDetector = np.array((0, 0 , dRot*np.pi/180))

geo4 = tigre.geometry(mode='cone', default=True, nVoxel=np.array([250, 250, 250]))
geo4.dDetector = np.array((0.5, 0.5))*3
geo4.sDetector = geo4.dDetector * geo4.nDetector
geo4.DSO = 500
geo4.DSD = 700
geo4.rotDetector = np.array((0, 0, 0))

head = data_loader.load_head_phantom(geo.nVoxel)
proj = tigre.Ax(head, geo, angles)
proj2 = tigre.Ax(head, geo2, angles)
proj3 = tigre.Ax(head, geo3, angles)
proj4 = tigre.Ax(head, geo4, angles)
#%%
plt.ion()
fig, axis = plt.subplots(2,2)
for ii in range(nangles):
    axis[0, 0].imshow(proj[ii])
    axis[0, 0].set_title("Parallel rot {} deg.".format(dRot))
    axis[0, 1].imshow(proj2[ii])
    axis[0, 1].set_title("Parallel rot {} deg.".format(0))
    axis[1, 0].imshow(proj3[ii])
    axis[1, 0].set_title("Cone rot {} deg.".format(dRot))
    axis[1, 1].imshow(proj4[ii])
    axis[1, 1].set_title("Cone rot {} deg.".format(0))
    # plt.show()
    plt.pause(0.0001)
```


![DetectorRotation](https://user-images.githubusercontent.com/25704789/86926778-706cdc80-c16d-11ea-844f-7b459f52fcba.png)

## Envs
Python version: 3.7.7 (anaconda)
OS: Windows 10
CUDA version: 10.1

P.S. This is my first post. I'm sorry if I'm rude or misunderstood.

**Comment by AnderBiguri** [comment]
@genusn let mo move this to a new issue, as it is indeed a separate problem. Lets continue the discussion there! 

New issue: https://github.com/CERN/TIGRE/issues/168

**Comment by AnderBiguri** [comment]
@genusn However, do you say that the changes proposed by @WKrauze did indeed fix the rotation? That is very good news!

**Comment by genusn** [comment]
@AnderBiguri  Yes, the detector rotation does work on python cone beam with the changes proposed by @WKrauze .  Here, I assumed that axis of rolling is $u\times v$.

**Comment by AnderBiguri** [comment]
@genusn Ah fantastic. Then this issue can be fixed and closed, thanks for confirmation.

**Comment by yuanpengpeng** [comment]
> ## Expected Behavior
> I would expect that after specifying detector rotation array I will see a difference in generated projections.
> 
> ## Actual Behavior
> Whether I specify detector rotation matrix or not there is no difference in generated projections. Checked with 'parallel' and 'cone' modes. When I plot the difference between projections calculated with and without rotated detector I get matrix of zeros.
> 
> ## Code to reproduce the problem (If applicable)
> ```
> nangles = 20
> angles = np.linspace(-np.pi/2, np.pi/2, nangles, dtype=np.float32)
> 
> geo = tigre.geometry(mode='parallel', default=True, nVoxel=np.array([250, 250, 250]))
> geo.DSO = 1000
> geo.DSD = 2000
> geo.rotDetector = np.array((2, 1, 1))
> 
> geo2 = tigre.geometry(mode='parallel', default=True, nVoxel=np.array([250, 250, 250]))
> geo2.DSO = 1000
> geo2.DSD = 2000
> geo2.rotDetector = np.array((0, 0, 0))
> 
> head = data_loader.load_head_phantom(geo.nVoxel)
> proj = tigre.Ax(head, geo, angles)
> proj2 = tigre.Ax(head, geo2, angles)
> 
> plt.ion()
> for ii in range(nangles):
>     plt.imshow(proj[ii, :, :]-proj2[ii, :, :])
>     plt.show()
>     plt.pause(0.0001)
> ```
> 
> ## Specifications
> * Python version: 2.7 (tested also on 3.6)
> * OS: Linux Manjaro 18.1.1
> * CUDA version: 10.1

May I ask which version of tigre you tested on? Can you test tigre in the environment of python3.6, numpy==1.16.0?
