### ISSUE TITLE
Matlab error

### ISSUE THREAD

**Issue by vinxenz** [CERN/TIGRE#145]
I get this error on the execution of the matlab file:"d04_SimpleReconstruction.m"

**Invalid MEX-file 'C:\Users\Utente\Documents\TIGRE-master\MATLAB\Mex_files\win64\Ax_mex.mexw64': Impossibile trovare il modulo
specificato.

Error in Ax (line 59)
projections=Ax_mex(img,geo,angles,ptype);

Error in d04_SimpleReconstruction (line 36)
projections=Ax(head,geo,angles,'interpolated');**

**Comment by AnderBiguri** [comment]
Hi @vinxenz ,
Have you compiled TIGRE yourself?

**Comment by vinxenz** [comment]
I have not followed the standard installation. I don't have CUDA on my
graphic card. Is it necessary?

Il ven 29 nov 2019, 19:41 Biguri <notifications@github.com> ha scritto:

**Comment by AnderBiguri** [comment]
Yes, you need to follow the installation instructions to be able to use
Tigre.
