### ISSUE TITLE
Create geometry class

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#146]
The geometry structure has been getting more flexible and complicated with time. Having a class, instead of an struct, to describe the geometry and add methods that apply to the geometry (such as error checking or updating) would be the best approach as software dev.

**Comment by ashwinpn** [comment]
Can I work on this? Also, could you redirect me to the geometry struct code?

**Comment by AnderBiguri** [comment]
Hi @ashwinpn ,

Yes, that is great! Please do a fork, then create a new branch and work there so you can do a Pull request when you think its finished. 

The thing is that there is not a "geometry struct code", its simply defined each time you want a script. You can see it here, for example:

https://github.com/CERN/TIGRE/blob/master/MATLAB/Demos/d01_CreateGeometry.m#L69-L108

But its there in all other demos. The idea would be to create a class that can then have different member methods to be initialized, or to modify it, such as `checkGeometry()` that already exist as a separate function. 
The issue is, of course, that this structure is used in *almost all* functions in TIGRE, so creating a class would also probably mean to changing almost all functions in TIGRE.... Maybe its not necessary, but it may be.

**Comment by ashwinpn** [comment]
Thanks! I will check it out.
