### ISSUE TITLE
Wrong Error tag

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#147]
https://github.com/CERN/TIGRE/blob/4b4cc64e4513d482a667178532d83cfcc4105ddc/MATLAB/Source/Siddon_projection.cu#L843

**Comment by Zhentao-Liu** [comment]
I meet the same problem. Have you solved it?

**Comment by AnderBiguri** [comment]
Hi @Zhentao-Liu , this was just a comment on the text being wrong nothing else. Feel free to open a new issue with you r problem.
