### ISSUE TITLE
Just curious: is TIGRE able to reconstruct clinical spiral CT?

### ISSUE THREAD

**Issue by dyycy** [CERN/TIGRE#148]
Just curious.
As far as I know, there is no open-source toolkit yet for spiral CT reconstruction.

**Comment by AnderBiguri** [comment]
Hi,
Unfortunately I am not knowledgeable about how medical spiral CT works. Do
you mean the classic 2D detectors and spiral movement?

In any case, it is likely that Tigre can do it, as it has full geometric
flexibility. If you give me more information about the geometry I will be
able to help more.
Ander

**Comment by AnderBiguri** [comment]
@dyycy  I am closing this issue, let me know if you need more information.
