### ISSUE TITLE
Multi-GPU python

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#152]
Here I will explain what I think its needed to make the multi-GPU version of TIGRE work in python. As I don't currently have access to a 2 GPU machine, I can not test these, so I will leave it open until I (or someone else) can test these.

### Main differences between python and MATLAB source code

The main issue between the two is that MATLAB stores matrices in column mayor (Fortran style) and python has them in row mayor (C styles). This means that when the 3D arrays are unrolled, `img[1]` in the source code will have a different value. However, python is now using basically the same source code as MATLAB does, which means it requires permuting the input and output of the source code in CUDA to make it work. This is a massive waste of memory, as it requires a full copy of the object, and permuting is not a cheap operation. This is the main reason why the multi-GPU code is not implemented in python, as we wanted to fix this first, which we never did.... 

This is reflected in the code in the projection CUDA calling function `_Ax.pyx` in https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/Python/tigre/Source/_Ax.pyx#L65 and in https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/Python/tigre/Source/_Ax.pyx#L94 
Similar lines can be found in `_Atb.pyx`. In order to make the Multi-GPU code work, these need to go, and the computation order of the pixels on the GPU kernels need to change.  

Other minor differences between source code:

- All `mexPrintf` should be changed to the standard `printf`

- The error checking code is defined with the C++ `inline` way https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/Python/tigre/Source/Siddon_projection.cu#L58 instead of the C `#define` macro https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/MATLAB/Source/Siddon_projection.cu#L57

- All `cudaCheckErrors` now return `int` instead of raising an error, so they need to be surrounded by an if clause. e.g. https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/Python/tigre/Source/Siddon_projection.cu#L253 vs https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/MATLAB/Source/Siddon_projection.cu#L332 

### What needs changing

Fundamentally, aside from the minor changes mentioned above, the order in which the images are computed needs to change. This should only mean a change in indices inside the kernel. As the `z` axis is the same in both data ordering methods, the multi-GPU side of the entire kernel call should have no issue (🤞). 

I suggest starting all changes from the current MATAB master branch. The multi-GPU developer python branch is stale and too far from the current TIGRE status, likely it will have lots of bugs and we did not do any development there.

I have identified the following changes in the kernels to make it work, which have worked on a standalone C++ application, but have not tested them together with the python toolbox:

**Forward project interpolated**

[MATLAB/Source/ray_interpolated_projection.cu](https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/MATLAB/Source/ray_interpolated_projection.cu)

----
### 1

https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/MATLAB/Source/ray_interpolated_projection.cu#L125-L126

Change to:

```
unsigned long  x = blockIdx.y * blockDim.y + threadIdx.y;
unsigned long  y = blockIdx.x * blockDim.x + threadIdx.x;
```

----
### 2
https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/MATLAB/Source/ray_interpolated_projection.cu#L133

Change to:
```
size_t idx =  (size_t)(x  + geo.nDetecU * y)+ (size_t)projNumber*geo.nDetecV *geo.nDetecU ;
```
----
### 3

https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/MATLAB/Source/ray_interpolated_projection.cu#L196

Change to:
```
sum += tex3D<float>(tex, ty+0.5f, tx+0.5f, tz+0.5f); // this line is 94% of time.
```
----
### 4 (?) 

It is likely that the value of the variables `geo.nVoxelX` and `geo.nVoxelY` need to be swapped before the entire CUDA code is called, but I do not know for sure. Test square images first. 

**Forward projector ray-voxel intersection** 

[/MATLAB/Source/Siddon_projection.cu](https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/MATLAB/Source/Siddon_projection.cu)

I have not tested this, but similar indices are computed and memory is read in the same way. I suspect the changes are the same, but I do not know. 

**Parallel forward projectors (2)**

[MATLAB/Source/Siddon_projection_parallel.cu](https://github.com/CERN/TIGRE/blob/master/MATLAB/Source/Siddon_projection_parallel.cu)

[MATLAB/Source/ray_interpolated_projection_parallel.cu](https://github.com/CERN/TIGRE/blob/master/MATLAB/Source/ray_interpolated_projection_parallel.cu)

Whatever it is changed in the cone shaped ones, do the same for the parallel one.

**Backprojection**

[/MATLAB/Source/voxel_backprojection.cu](https://github.com/CERN/TIGRE/blob/master/MATLAB/Source/voxel_backprojection.cu)

[/MATLAB/Source/voxel_backprojection2.cu](https://github.com/CERN/TIGRE/blob/master/MATLAB/Source/voxel_backprojection2.cu)

[/MATLAB/Source/voxel_backprojection_parallel.cu](https://github.com/CERN/TIGRE/blob/master/MATLAB/Source/voxel_backprojection_parallel.cu)

All backprojectors are essentially the same, but the matched one (voxel_backprojection2.cu) has an extra weighting kernel, which requires no modification. The instructions here are for the only one I tested, [/MATLAB/Source/voxel_backprojection.cu](https://github.com/CERN/TIGRE/blob/master/MATLAB/Source/voxel_backprojection.cu)

----

### 1

https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/MATLAB/Source/voxel_backprojection.cu#L253 

Change to:

```
 voxelColumn[colIdx]+=tex3D<float>(tex, u, v ,indAlpha+0.5f)*weigth;
```

### 2 (?)

The above change does not seem to reflect the problem properly, so I suspect there is something else missing. 

### Conclusions (tl;dr)

We need to take and modify the MATLAB source code to make sure there is no permute in the python side. The changes mentioned above are what is needed, but a multi-GPU computer, and some CUDA knowledge may be needed to make sure it works fully. 

I have not access to such computer, but will always be ready to give a hand if someone takes upon this job. Email to ander.biguri@gmail.com with any question or just reply here.

**Comment by genusn** [comment]
Hello,
I am interested in this issue and walking around the code.
I have a question. Are these two lines necessary ?
https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/Python/tigre/Source/_Ax.pyx#L65

https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/Python/tigre/Source/_Ax.pyx#L78

When I comment-out them, re-compile the _Ax.pyd file, and run the test code below, I had the same result in 60% time (4s -> 2.4s per iteration).


## Test Code

```
import datetime
from matplotlib import pyplot as plt
import tigre
import tigre.algorithms as algs
from tigre.demos.Test_data import data_loader
from tigre.utilities.Measure_Quality import Measure_Quality
import time
dt_now = datetime.datetime.now()

#geo1 = tigre.geometry(mode='cone', high_quality=False, default=True)
geo = tigre.geometry(mode='cone', nVoxel=np.array([256,256,256]),default=True)
geo.dDetector = np.array([0.8, 0.8])*2               # size of each pixel            (mm)
geo.sDetector = geo.dDetector * geo.nDetector

atypeAlgos = ("fdk", "sirt")
fig, axes = plt.subplots(1, len(atypeAlgos))

nangles = 100
angles = np.linspace(0, 2 * np.pi, nangles, dtype=np.float32)
#head = np.load('src_img_cubic_256.npy') #data_loader.load_head_phantom(geo.nVoxel)
head = data_loader.load_head_phantom(geo.nVoxel)
proj = tigre.Ax(head,geo,angles)
for idx in range(len(atypeAlgos)):
    typeAlgo = atypeAlgos[idx]
    timeStart = time.time()
    if typeAlgo == "fdk":
        niter = 1
        volume = algs.fdk(proj,geo,angles)
    elif typeAlgo == "sirt":
        niter = 20
        volume = algs.ossart(proj,geo,angles,niter,blocksize=20)
    timeElapsed = time.time()-timeStart
    print("{}, Elapsed {} s".format(typeAlgo, timeElapsed))

    # kMag = 10000
    # np.save("vol_{}_x{}.npy".format(typeAlgo, kMag), volume*kMag)

    print('RMSE {}:'.format(typeAlgo))
    quality = Measure_Quality(volume,head,['nRMSE'])
    print("RMSE = ", quality)


    mappable = axes[idx].imshow(volume[geo.nVoxel[0]//2])
    fig.colorbar(mappable, ax=axes[idx])
    axes[idx].set_title(typeAlgo)


    with open('Result_{}.csv'.format(typeAlgo), 'a') as f:
        print('{}, {}, {}, {}, {}, {}, {}, {}'.format(dt_now, timeElapsed, timeElapsed/niter, geo.nVoxel[2], geo.nVoxel[0], geo.dDetector[0], nangles, quality), file=f)

fig.savefig("centerplane.png")

```

## Specifications
Python: 3.7.7 (anaconda)
OS: Windows 10, 64 bit
CUDA version: 10.1

**Comment by AnderBiguri** [comment]
@genusn  huh that is interesting.... Those copy and transposes are supposed to be there so the output of `Ax` and `Atb` are not transposed to the input. Can you test if these particular functions (not the algorithms) do the correct thing without the transpose/copy operators? I think they should not, but I am confused now.

**Comment by genusn** [comment]
@AnderBiguri,
Firstly, I checked my understandings of ndarray of numpy with the following code:
```
import numpy as np
A0 = np.arange(24).reshape(2, 3, 4)
A = A0.copy()
print("A        :\n", A)
print("A.shape  : " , A.shape)
print("A.base   : " , A.base)
print("A.flatten: " , A.flatten(order='K'))
print("A.flatten: " , A.flatten(order='A'))
print("A[0,1,2] : ", A[0,1,2])
F = A0.copy(order="F")
print("F        :\n", F)
print("F.shape  : " , F.shape)
print("F.base   : " , F.base)
print("F.flatten: " , F.flatten(order='K'))
print("F.flatten: " , F.flatten(order='A'))
```
The result was
```
A        :
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
A.shape  :  (2, 3, 4)
A.base   :  None
A.flatten:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
A.flatten:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
A[0,1,2] :  6
F        :
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
F.shape  :  (2, 3, 4)
F.base   :  None
F.flatten:  [ 0 12  4 16  8 20  1 13  5 17  9 21  2 14  6 18 10 22  3 15  7 19 11 23]
F.flatten:  [ 0 12  4 16  8 20  1 13  5 17  9 21  2 14  6 18 10 22  3 15  7 19 11 23]
F[0,1,2] :  6
```

Secondly, in order to check that my workspace is working fine, 
I have seen if changing L65 to
`
img = img.transpose().copy(order='C')
`
makes the result image become corrupted.
The result was corrupted. i.e. it's true that my fix affects the results.

Thridly, I added several lines to the test code above as below to show the result of Ax function:

```
from __future__ import print_function
from __future__ import division
import copy
import numpy as np
import time
import sys
import datetime
from matplotlib import pyplot as plt
import tigre
import tigre.algorithms as algs
from tigre.demos.Test_data import data_loader
from tigre.utilities.Measure_Quality import Measure_Quality
import time
dt_now = datetime.datetime.now()

#geo1 = tigre.geometry(mode='cone', high_quality=False, default=True)
geo = tigre.geometry(mode='cone', nVoxel=np.array([256,256,256]),default=True)
geo.dDetector = np.array([0.8, 0.8])*2               # size of each pixel            (mm)
geo.sDetector = geo.dDetector * geo.nDetector

atypeAlgos = ("fdk", "sirt")
azSlicePos=(geo.nVoxel[0]//4, geo.nVoxel[0]//2, 3*geo.nVoxel[0]//4)
fig, axes = plt.subplots(len(azSlicePos)+1, len(atypeAlgos), figsize=(5*2, 5*(len(azSlicePos)+1)))

nangles = 100
angles = np.linspace(0, 2 * np.pi, nangles, dtype=np.float32)
#head = np.load('src_img_cubic_256.npy') #data_loader.load_head_phantom(geo.nVoxel)
head = data_loader.load_head_phantom(geo.nVoxel)
proj = tigre.Ax(head,geo,angles)

mappable = axes[0, 0].imshow(proj[0])
fig.colorbar(mappable, ax=axes[0, 0])
axes[0, 0].set_title("proj[0]")
mappable = axes[0, 1].imshow(proj[nangles//6])
fig.colorbar(mappable, ax=axes[0, 1])
axes[0, 1].set_title("proj[nangles//6]")

for idx in range(len(atypeAlgos)):
    typeAlgo = atypeAlgos[idx]
    timeStart = time.time()
    if typeAlgo == "fdk":
        niter = 1
        volume = algs.fdk(proj,geo,angles)
    elif typeAlgo == "sirt":
        niter = 3
        volume = algs.ossart(proj,geo,angles,niter,blocksize=20)
    timeElapsed = time.time()-timeStart
    print("{}, Elapsed {} s".format(typeAlgo, timeElapsed))

    # kMag = 10000
    # np.save("vol_{}_x{}.npy".format(typeAlgo, kMag), volume*kMag)

    print('RMSE {}:'.format(typeAlgo))
    quality = Measure_Quality(volume,head,['nRMSE'])
    print("RMSE = ", quality)

    for idx2 in range(len(azSlicePos)):
        mappable = axes[idx2+1, idx].imshow(volume[azSlicePos[idx2]])
        fig.colorbar(mappable, ax=axes[idx2+1, idx])
        axes[idx2+1, idx].set_title("{} Z={}mm".format(typeAlgo, azSlicePos[idx2]*geo.dVoxel[0]))


    with open('Result_{}.csv'.format(typeAlgo), 'a') as f:
        print('{}, {}, {}, {}, {}, {}, {}, {}'.format(dt_now, timeElapsed, timeElapsed/niter, geo.nVoxel[2], geo.nVoxel[0], geo.dDetector[0], nangles, quality), file=f)

fig.savefig("slices.png")
```

The result image was the same (except the plot title aliasing...why...?).
![slices_pat2](https://user-images.githubusercontent.com/25704789/90296971-1546ac00-dec8-11ea-9073-f20ae873d04f.png)



Lastly, here is my thought.
I am not a python specialist, but it seems to me that 
https://github.com/CERN/TIGRE/blob/45856141b2ddd918bcd5825fe3d0cc5aa104c01c/Python/tigre/Source/_Ax.pyx#L65
has no effect because the sequential processes 
1. transpose reverses the order of index in python expression
2. copy(order="F") copies the array in the reverse order of index.

are equivalent to 
`
copy(order="C")
`
Here, order="C" is default behaviour of copy function and
`
img = img.copy(order="C")
`
effectively does nothing.
What do you think?


p.s.
I have not tested the Atb function without using Ax.

**Comment by AnderBiguri** [comment]
@genusn to be fair, all that you are saying makes sense. Let me do a couple of test from my side to verify it, but it seems that the line is a mistake that was left when debugging/designing the functions. Its a good catch! 

I suggest the following: make a branch and a pull request. That way, I can see and help with the modifications of the code, and review and test the changes in the code easily!
