### ISSUE TITLE
ValueError: TIGRE: Call to Ax failed

### ISSUE THREAD

**Issue by vincentme** [CERN/TIGRE#155]
Hi

I just tried running the python version of the latest master branch. However, when I run any demo or runscript.sh, the same error returns

 line 25, in Ax
    return _Ax_ext(img, geox, geox.angles, krylov, geox.mode)
  File "tigre/Source/_Ax.pyx", line 70, in _Ax._Ax_ext
  File "tigre/Source/_Ax.pyx", line 27, in _Ax.cuda_raise_errors
ValueError: TIGRE: Call to Ax failed

I installed the tigre through `python setup.py install`
The cuda and python version are

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.

Thank you in advance!

**Comment by AnderBiguri** [comment]
If you try this commit, do you have the same error?

https://github.com/CERN/TIGRE/tree/45856141b2ddd918bcd5825fe3d0cc5aa104c01c

**Comment by vincentme** [comment]
> If you try this commit, do you have the same error?
> 
> https://github.com/CERN/TIGRE/tree/45856141b2ddd918bcd5825fe3d0cc5aa104c01c

Thank you. I have tried that commit. Same result. 

This time I noticed that at the beginning the error is
CUDA:Siddon_projection:3D texture memory bind fail:invalid texture reference

The full error log is

CUDA:Siddon_projection:3D texture memory bind fail:invalid texture reference
E
======================================================================
ERROR [4.227s]: test_1_FDK (__main__.TestSequence)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yunlu/github/TIGRE-master/Python/tests/test_config_gen.py", line 22, in test
    self.assertTrue(AlgorithmTest(configuration,algorithm).unit_test_call())
  File "/home/yunlu/github/TIGRE-master/Python/tests/algorithm_test.py", line 51, in unit_test_call
    self.test()
  File "/home/yunlu/github/TIGRE-master/Python/tests/algorithm_test.py", line 38, in test
    proj = tigre.Ax(head,self.geo,self.angles)
  File "/home/yunlu/.local/lib/python3.7/site-packages/pytigre-0.1.8-py3.7-linux-x86_64.egg/tigre/utilities/Ax.py", line 25, in Ax
    return _Ax_ext(img, geox, geox.angles, krylov, geox.mode)
  File "tigre/Source/_Ax.pyx", line 70, in _Ax._Ax_ext
  File "tigre/Source/_Ax.pyx", line 27, in _Ax.cuda_raise_errors
ValueError: TIGRE: Call to Ax failed

To provide more background, my environment is 
ubuntu 20.04
cuda 10.2
gcc 8.4
python 3.7

**Comment by AnderBiguri** [comment]
@vincentme  which GPU are you using?

**Comment by vincentme** [comment]
> @vincentme which GPU are you using?

I am using 2080super

**Comment by AnderBiguri** [comment]
@vincentme  Try the doollowing:


Uncomment this line: 

https://github.com/CERN/TIGRE/blob/master/Python/setup.py#L18

and change the `70`'s to `75`'s. Then compile again and try again

**Comment by vincentme** [comment]
> @vincentme Try the following:
> 
> Uncomment this line:
> 
> https://github.com/CERN/TIGRE/blob/master/Python/setup.py#L18
> 
> and change the `70`'s to `75`'s. Then compile again and try again

This time it works. Thank you!
