### ISSUE TITLE
Error using mex and error in Compile

### ISSUE THREAD

**Issue by Ruoqian-H** [CERN/TIGRE#164]
Hi TIGRE Team,

these days i am in trouble with set up instructions step 8...
matlab shows
`Error using mex
No supported compiler was found. For options, visit https://www.mathworks.com/support/compilers.

Error in Compile (line 52)
        mex -largeArrayDims ./Source/Ax_mex.cpp ./Source/ray_interpolated_projection.cu ./Source/Siddon_projection.cu
        ./Source/ray_interpolated_projection_parallel.cu ./Source/Siddon_projection_parallel.cu -outdir ./Mex_files/win64`
although after nvcc location has been changed.

can anybody help :)
## Specifications 

  - MATLAB version: R2019a
  - OS: Windows 10
  - CUDA version: 10.2.89

**Comment by AnderBiguri** [comment]
Hi @Ruoqian-H 

Which C compiler do you use? In particular, which version of visual studio?
Which GPU do you have?

**Comment by Ruoqian-H** [comment]
wow that's fast! thanks a lot for your reply :3 
i chose vs 2017.
and my laptop's GPU is NVIDIA GeForce MX150, desktop computer is NVIDIA GT 950.

**Comment by AnderBiguri** [comment]
@Ruoqian-H Possible reasons can be

- You have not installed C++ compilers with visual studio
- If you have changed the CUDA location: The code does not know where CUDA is. 

To fix the first, check the installation guide Step 5.

To fix the second, Step 6

**Comment by Ruoqian-H** [comment]
Hola Ander,
beginner problem comes again haha
under your suggestions, i fixed the "error using mex" ;), unluckily, matlab still shows "error in use compile".

error in use Compile (line 37)
mex_CUDA_win64.xml not found. You may need to rename the existing files depending on your MVS version

i tried twice, renamed the MVS2015 and MVS2019, both are failed...

**Comment by Ruoqian-H** [comment]
emm, i mean after rename, this error still exists

**Comment by AnderBiguri** [comment]
@Ruoqian-H that is not possible. That error only happens if the file not exist, I literally just check if the file exist, and if not, manually error.

**Comment by AnderBiguri** [comment]
@Ruoqian-H are you still having issues?
