### ISSUE TITLE
Error in Compile

### ISSUE THREAD

**Issue by JoaoWang** [CERN/TIGRE#165]
Hi TIGRE Team:
I am a Chinese student. Recently, I encountered some problems in installing the TIGRE toolkit. I hope to get your help. 
My problem may be similar to https://github.com/CERN/TIGRE/issues/164, I was also reported Error using mex in the installation guide Step 8, you can see Fig 1 for details. In addition, I try opening mex_CUDA_win64.xml and changing line 125 to link to my local nvcc location, but this error still exists.
![Fig 1](https://user-images.githubusercontent.com/64910341/81190464-766a0400-8fea-11ea-9287-0c7381cac624.png)
I’ve referred to Ander Biguri's suggestion inhttps://github.com/cern/tigre/issues/164 , and checked the Step 5. When I run mex -setup -v, the output is as shown in Fig 2. Although I find that the three YES in the red box seem to be a little inconsistent with the installation guide, I'm not sure whether my output is wrong.
![Fig 2](https://user-images.githubusercontent.com/64910341/81190604-a1545800-8fea-11ea-9b0f-c92ebb5ae549.png)
I also checked the detailed installation information of my VS 2017, as shown in Fig 3. I should be installing the C + + compiler.
![Fig 3](https://user-images.githubusercontent.com/64910341/81191133-42431300-8feb-11ea-95ab-fda2bf7c24b7.png)
Next, I checked step 6. When I run getenv('CUDA_PATH') and getenv('VS140COMNTOOLS'), the output is as shown in Fig 4.
![Fig 4](https://user-images.githubusercontent.com/64910341/81190675-b9c47280-8fea-11ea-8f8c-2b40764d8a8c.png)
It is worth noting that the Environment Variable VS140COMNTOOLS is new-built by myself. Before that, I cannot find VS140COMNTOOLS in my computer, and when I run getenv('VS140COMNTOOLS'), the return value is empty. You can see whether there is a problem with my environment variable settings, The way I set environment variables is: Control PanelSystem and SecuritySystemAdvanced system settingsEnvironment VariablesSystem VariablesNew, and the screenshot of my folder C:\Software\Visual Studio 2017 Community\Visual Studio IDE\Common7\Tools is shown in Fig 5.
![Fig 5](https://user-images.githubusercontent.com/64910341/81190835-e8424d80-8fea-11ea-90da-7c9edbe9a011.png)

## Specifications 

  - MATLAB version: R2019a
  - OS: Win 10
  - C++ Compiler:  Virtual Studio Community 2017
  - CUDA version: 10.1.243
  - GPU: NVIDIA Geforce Mx250

**Comment by AnderBiguri** [comment]
Hi @JoaoWang 

I can see how C++/CLI  (the C++ compiler) is not installed in your screenshots!
Which is what Step 5 suggests (check that its not random "Yes" that we are looking for, but those particular ones that I mention).
Hope this helps.

Ander

**Comment by JoaoWang** [comment]
Hi @AnderBiguri 
Thanks a lot for your reply!
I have installed C++/CLI according to your suggestion  (shown in Fig 6) and restart my computer, however, the error is still exist.
![Fig 6](https://user-images.githubusercontent.com/64910341/81203761-e84a4980-8ffa-11ea-8746-e7c34dc690ac.png)
Now, when I run `mex -setup -v`, the output is still same as before (shown in Fig 2), and I still cannot find the last two 'YES'  (shown in Fig 7) in my output.
![Fig 7](https://user-images.githubusercontent.com/64910341/81203878-09129f00-8ffb-11ea-9e43-dc131aeba9a0.png)
I don 't know how to fix it. May I try uninstalling vs2017 and installing vs2015 or  other versions you have tested?

**Comment by AnderBiguri** [comment]
I do not understand the text, but "clicking" it is not enough, you need to install it @JoaoWang. Having cl.exe is essential to be able to compile C++ code.

**Comment by JoaoWang** [comment]
Hi @AnderBiguri 
I searched my computer for cl.exe, and it can be found.
![Fig 8](https://user-images.githubusercontent.com/64910341/81206119-36ad1780-8ffe-11ea-8f5e-c7b85a9f37a0.png)

**Comment by AnderBiguri** [comment]
@JoaoWang And MATLAB can not find those? 

It would be much easier for both if you would share text instead of images. When you do Step 5, are you sure there is no `cl.exe` or `cli.exe` found by MATLAB?

**Comment by JoaoWang** [comment]
@AnderBiguri 
Yes, I'm sure there is no `cl.exe` or `cli.exe` found by Matlab. It's very strange.

**Comment by AnderBiguri** [comment]
@JoaoWang to get a better understanding coudl you try 2 things:

1) Compile a C++ mex example without cuda (e.g. `edit([matlabroot '/extern/examples/cpp_mex/arrayProduct.cpp']);`)

2) Compile a CUDA code without MATLAB (e.g. anyof the CUDA samples that come with CUDA).

**Comment by JoaoWang** [comment]
@AnderBiguri 
I tried to compile `arrayProduct.cpp` with Matlab, and configured VS2017 as default C++ compiler,  it can be run successfully. Why Matlab cannot find `cl.exe` or `cli.exe`, but the example can be compiled? I was shocked!
I also try compiling `kernel.cu` with VS2017, it also can be run successfully.

**Comment by AnderBiguri** [comment]
@JoaoWang OK, that is good news. That is that MATLAB does indeed find the compiler and compile the code. Similarly, if you can compile CUDA code, it meas that CUDA is well installed, and therefore the error is some configuration error. 

I will think a bit more, I honestly do not know why it does not compile.

**Comment by JoaoWang** [comment]
@AnderBiguri 
I'm excited to hear that this is good news. I look forward to your further reply~

**Comment by AnderBiguri** [comment]
@JoaoWang please do continue investigating why this could happen yourself. I am out of ideas and while I might come with some suggestions, its much harder for me to do it as I do not have access to your computer.

**Comment by JoaoWang** [comment]
Hi @AnderBiguri 
Can you provide an XML file for vs2017? 
I consulted a friend of mine who thought my problem might be caused by incompatibility with vs2017. At the same time, the problem of https://github.com/CERN/TIGRE/issues/164 is similar to mine. I guess that both of our problems may be due to the lack of XML file for VS2017.

**Comment by AnderBiguri** [comment]
@JoaoWang Sorry, I have been busy with other things. I can definetly say that I have used the 2015 XML to compile with 2017. So unless they have changed something on how VS2017 works (which is not unheard of) the 2015 version should be valid. I will install 2017 in my computer and test it myself as soon as I have some time.

**Comment by AnderBiguri** [comment]
@JoaoWang Still nothing sorry. To be honest, my best advice is to install any of the other MSV. I have personally tested 2013, 2015, 2019 recently.

**Comment by JoaoWang** [comment]
@AnderBiguri 
Thanks for your help! I will try to install VS 2015 and CUDA V9.2, both of which you have tested. I sincerely hope that I can successfully install Tigre this time.

**Comment by AnderBiguri** [comment]
@JoaoWang no need to change CUDA, just MVS

**Comment by JoaoWang** [comment]
@AnderBiguri 
I uninstalled CUDA v10.1 and installed CUDA V9.2 yesterday, because I saw that the version of CUDA is v9.2 in mex_CUDA_Win64_MSV2015.xml. I'll try to install Tigre again when I'm free and share my progress with you~

**Comment by AnderBiguri** [comment]
@JoaoWang its OK, bu the latest the CUDA, the faster the code. the xml only has "failsafe" systems to find CUDA if you have weirdly installed it, and the version is only used for that, so should not be a worry. You can use any, you will likely not notice any difference.

**Comment by JoaoWang** [comment]
@AnderBiguri 
I'm glad to share this good news with you. I've successfully installed Tigre. Thanks a lot for your patience and help. Now, I can use Tigre. I really believe that Tigre will become a powerful tool for my research!

**Comment by AnderBiguri** [comment]
@JoaoWang Glad you did! Check out the demos, and if you have any further questions let me know.
