### ISSUE TITLE
Detector rotation not working on python parallel beam

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#168]
## Summary
[WKrauze 's modification](https://github.com/CERN/TIGRE/issues/142) worked fine for 'cone' mode.

## Expected Behavior
Works for both 'cone' and 'parallel' mode.

## Actual Behavior
Works only for 'cone' mode.
The rotation of the detector does not work in the 'parallel' mode.

## Code
```
nangles = 50
angles = np.linspace(-np.pi/2, np.pi/2, nangles, dtype=np.float32)

dRot = 45

geo = tigre.geometry(mode='parallel', default=True, nVoxel=np.array([250, 250, 250]))
geo.dDetector = np.array((0.5, 0.5))*3
geo.sDetector = geo.dDetector * geo.nDetector
geo.DSO = 500
geo.DSD = 700
geo.rotDetector = np.array((0, 0, dRot*np.pi/180))

geo2 = tigre.geometry(mode='parallel', default=True, nVoxel=np.array([250, 250, 250]))
geo2.dDetector = np.array((0.5, 0.5))*3
geo2.sDetector = geo2.dDetector * geo2.nDetector
geo2.DSO = 500
geo2.DSD = 700
geo2.rotDetector = np.array((0, 0, 0))

geo3 = tigre.geometry(mode='cone', default=True, nVoxel=np.array([250, 250, 250]))
geo3.dDetector = np.array((0.5, 0.5))*3
geo3.sDetector = geo3.dDetector * geo3.nDetector
geo3.DSO = 500
geo3.DSD = 700
geo3.rotDetector = np.array((0, 0 , dRot*np.pi/180))

geo4 = tigre.geometry(mode='cone', default=True, nVoxel=np.array([250, 250, 250]))
geo4.dDetector = np.array((0.5, 0.5))*3
geo4.sDetector = geo4.dDetector * geo4.nDetector
geo4.DSO = 500
geo4.DSD = 700
geo4.rotDetector = np.array((0, 0, 0))

head = data_loader.load_head_phantom(geo.nVoxel)
proj = tigre.Ax(head, geo, angles)
proj2 = tigre.Ax(head, geo2, angles)
proj3 = tigre.Ax(head, geo3, angles)
proj4 = tigre.Ax(head, geo4, angles)
#%%
plt.ion()
fig, axis = plt.subplots(2,2)
for ii in range(nangles):
    axis[0, 0].imshow(proj[ii])
    axis[0, 0].set_title("Parallel rot {} deg.".format(dRot))
    axis[0, 1].imshow(proj2[ii])
    axis[0, 1].set_title("Parallel rot {} deg.".format(0))
    axis[1, 0].imshow(proj3[ii])
    axis[1, 0].set_title("Cone rot {} deg.".format(dRot))
    axis[1, 1].imshow(proj4[ii])
    axis[1, 1].set_title("Cone rot {} deg.".format(0))
    # plt.show()
    plt.pause(0.0001)
```

![DetectorRotation](https://user-images.githubusercontent.com/25704789/86926778-706cdc80-c16d-11ea-844f-7b459f52fcba.png)

## Envs
Python version: 3.7.7 (anaconda)
OS: Windows 10
CUDA version: 10.1

**Comment by AnderBiguri** [comment]
The issue is that the source code for parallel beam simply does not have detector rotation! 
The rationale to not add it there was because I simply have not ever seen a parallel beam real-life machine that could do this and never though why anyone would do it, but  I seem to be mistaken! The fix is not too hard

In the source of the cone beam CT, there is a bit where the geometry is recalculated. In there, there is a function [`rollPitchYaw` ](https://github.com/CERN/TIGRE/blob/master/Python/tigre/Source/ray_interpolated_projection.cu#L443) that rotates the detector: https://github.com/CERN/TIGRE/blob/master/Python/tigre/Source/ray_interpolated_projection.cu#L342
In the parallel code, this function is neither defined, nor used. The call to rotation of the detector needs to be replicated here:https://github.com/CERN/TIGRE/blob/master/Python/tigre/Source/ray_interpolated_projection_parallel.cu#L292

This is of course needed in the other source codes too, i.e. `Siddon_projection_parallel.cu` (should have the same function again). 
 
The back-projection code has a similar (not the same) call in the cone beam geometry fixing but not in the parallel beam one. Should be fixed in there too.

**Comment by AnderBiguri** [comment]
@genusn If you have the time and the energy to tackle this, please give it a go. I can not promise I can fix this "soon". My suggestion is that you Fork TIGRE, make a branch with your changes, and then make a pull request once you have fixed them and committed them. That will allow me to review them and automatically add them if correct (that is the magic of git).
Alternatively you can also wait until I make some time to fix this.

**Comment by WKrauze** [comment]
@AnderBiguri I am currently working on this fix, however in Matlab version of TIGRE. I already added these additional geometric transformations to "parallel" versions of the files. I haven't defined rollPitchYaw function in "parallel" files, since then I get errors during compilation that this function is defined in two different places. Now when I set rotation in my Matlab test code, the image gets rotated. I still have some doubts about this, since it looks as if in "parallel" mode, the image is rotated not with respect to the center of the image, but with respect to some point that is slightly shifted (in the "cone" mode it is rotated with respect to the center). Any ideas why could this happen? I attach the screenshot, which should give you the idea of the problem (each picture presents difference between rotated and not rotated head phantom, rotation around 90deg).
![Screenshot_20201217_172516](https://user-images.githubusercontent.com/8330881/102514658-0564f180-408d-11eb-9a49-29706bc1fcb2.png)

**Comment by AnderBiguri** [comment]
@WKrauze  oh, very great news! Thanks for working on this!

About the multiple definition: Yes, this is an issue. We need to either put the function in a separate file, or simply rename it. I suggest you rename it for now, something like `rollPitchYaw_parallel`.

You are right in your assessment of the rotation, it seem that in the parallel beam the "yellow" head is much larger and off center. Unfortunately without seing the code, I have no idea what it could be. Are you using github? Can you make a PR, or point me out the the branch where you are working in this? I am sure that by looking at code I am more able to find what is going on. 

Can you also share the code you used to generate these images?

**Comment by WKrauze** [comment]
@AnderBiguri Sure, I will rename the function, and in a few hours I will make a PR. The code that I use for testing is:
```nangles = 20;
angles = linspace(-pi/2, pi/2, nangles);
angles2= linspace(-pi/2, pi/2, nangles);

mode = 'cone';
%mode = 'parallel';

geo.nVoxel= [256; 256; 256];
geo.sVoxel= [256; 256; 256];  
geo.mode = mode;
geo.DSO = 1000;
geo.DSD = 1200;
geo.rotDetector =[1.5; 0; 0];
geo.dVoxel=geo.sVoxel./geo.nVoxel;
geo.nDetector=[512; 512];					% number of pixels              (px)
geo.dDetector=[0.8; 0.8]; 					% size of each pixel            (mm)
geo.sDetector=geo.nDetector.*geo.dDetector; % total size of the detector    (mm)
geo.offOrigin =[0;0;0];                     % Offset of image from origin   (mm)              
geo.offDetector=[0; 0];                     % Offset of Detector            (mm)
geo.accuracy=0.5;
geo.COR=0;

geo2.nVoxel= [256; 256; 256];
geo2.sVoxel= [256; 256; 256]; 
geo2.mode = mode;
geo2.DSO = 1000;
geo2.DSD = 1200;
geo2.rotDetector =[0; 0; 0];
geo2.dVoxel=geo2.sVoxel./geo2.nVoxel;
geo2.nDetector=[512; 512];					% number of pixels              (px)
geo2.dDetector=[0.8; 0.8]; 					% size of each pixel            (mm)
geo2.sDetector=geo2.nDetector.*geo2.dDetector; % total size of the detector    (mm)
geo2.offOrigin =[0;0;0];                     % Offset of image from origin   (mm)              
geo2.offDetector=[0; 0];                     % Offset of Detector            (mm)
geo2.accuracy=0.5;
geo2.COR=0;

head = headPhantom(geo.nVoxel);
head2 = headPhantom(geo2.nVoxel);
proj = Ax(head, geo, angles, 'interpolated');
proj2 = Ax(head2, geo2, angles2, 'interpolated');

imagesc(proj(:,:,1) - proj2(:,:,1))
title(mode)
if sum(proj2(:)-proj(:)) == 0
    disp('No difference')
else
    disp('It works!')
end
