### ISSUE TITLE
Cuda error?

### ISSUE THREAD

**Issue by huangs-i2r** [CERN/TIGRE#182]
Hi, I encountered an error after installed Tigre. Can anyone help? Thanks in advance.

## Expected Behavior
After installation, pass the python example.py test

## Actual Behavior
Failed with following error message:

CUDA:Siddon_projection:3D texture memory bind fail:invalid texture reference
Traceback (most recent call last):
  File "example.py", line 23, in <module>
    proj = tigre.Ax(head,geo,angles)
  File "/mnt/nas7/Work/TIGRE/Python/tigre/utilities/Ax.py", line 25, in Ax
    return _Ax_ext(img, geox, geox.angles, krylov, geox.mode)
  File "tigre/Source/_Ax.pyx", line 70, in _Ax._Ax_ext
    cuda_raise_errors(interpolation_projection(c_img, c_geometry[0], c_projections, c_angles, total_projections))
  File "tigre/Source/_Ax.pyx", line 27, in _Ax.cuda_raise_errors
    raise ValueError('TIGRE: Call to Ax failed')
ValueError: TIGRE: Call to Ax failed

## Code to reproduce the problem (If applicable)

python example.py

## Specifications 

  - Python version: 3.8
  - OS: Ubuntu 20.04
  - CUDA version: 10.0, 11.0
  - Tigre version: 0.1.8
  - tensorflow version: 2.3.1

**Comment by AnderBiguri** [comment]
Hi @huangs-i2r 

I suggest to donwload the latest commit, if you have not done that.
Can I know what GPU are you using?

**Comment by huangs-i2r** [comment]
I installed the latest code download from Github, got the same message. However, I created a brand new conda environment with python 3.7, and CUDA 10.1, then it works fine with the examply.py.
:)
