### ISSUE TITLE
Error in inport tigre

### ISSUE THREAD

**Issue by ptavares96** [CERN/TIGRE#183]
When I try run the example,py it shows me error:
"Traceback (most recent call last):
  File "C:/Users/paulo/Python Projects/ti/example.py", line 3, in <module>
    import tigre
  File "C:\Users\paulo\Python Projects\ti\tigre\__init__.py", line 4, in <module>
    from .utilities.Ax import Ax
  File "C:\Users\paulo\Python Projects\ti\tigre\utilities\Ax.py", line 1, in <module>
    from _Ax import _Ax_ext
ModuleNotFoundError: No module named '_Ax'"

**Comment by AnderBiguri** [comment]
@ptavares96 have you set up TIGRE correctly following the instructions?
Can you try running a demo?

**Comment by ptavares96** [comment]
> @ptavares96 have you set up TIGRE correctly following the instructions?
> Can you try running a demo?

I did. I'm using Windows. I saw that could have problem with this. I will try run demo and change my OS.

**Comment by AnderBiguri** [comment]
@ptavares96 someone updated TIGRE for for windows, but I haven't tested it thoroughly, and don't really know how to fix it....
