### ISSUE TITLE
can not compile

### ISSUE THREAD

**Issue by sunchang2017** [CERN/TIGRE#185]
Hi, I met mistakes when running Compile.m, here is the screen output:

```
MEX is configured to use 'Microsoft Visual C++ 2017 (C)' for C language compilation.
To select a different language, select one of the following commands:
mex - setup c + +
mex - setup FORTRAN
Compiling TIGRE source...
This may take a couple of minutes....
Incorrect use of MEX
A supported compiler was not found. About the options, please visit https://www.mathworks.com/support/compilers.
Error Compile (line 52)
mex -largearraydims./Source/ ax_met.cpp./Source/ray_interpolated_projection. Cu./Source/Siddon_projection. Cu
. / Source/ray_interpolated_projection_parallel. Cu. / Source/Siddon_projection_parallel. Cu - outdir. / Mex_files/win64
```

I have try  getenv('CUDA_PATH'), and its output is correct, and I add setenv('VS140COMNTOOLSP','C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools'), however I still cant compile successfully.

Could you help me analyze the mistake? (Please excuse my poor English)

## Specifications 

  - MATLAB version: R2019b
  - OS: win10
  - CUDA version: 11.1
  - Visual Studio: 2017 community

**Comment by AnderBiguri** [comment]
You may not have the c++ compiler installed. Have a look at the instructions in the installation guide. Sometimes Visual Studio does not install C++ compiler by default. 

Also, you do not need to set the environment variable normally, so maybe you overwrote the correct one, not sure. Check the c++ compiler install instructions first.

**Comment by sunchang2017** [comment]
I can compile a test file  'hello.cpp' below
---------------------------------------------------------
#include "mex.h"

void mexFunction(int nlhs, mxArray *plhs[], 
				int nrhs, const mxArray *prhs[])
{
	mexPrintf("Hello, world!\n");
	return;
}
---------------------------------------------------------------
>> mex hello.cpp   %can successfully generate hello.mexw64
>> hello
Hello, world!

Does that mean I installed the compiler successfully? (I only installed Microsoft Visual C++ 2017)

**Comment by sunchang2017** [comment]
I can compile a test file 'hello.cpp' below

#include "mex.h"
void mexFunction(int nlhs, mxArray *plhs[],
int nrhs, const mxArray *prhs[])
{
mexPrintf("Hello, world!\n");
return;
}

>>mex hello.cpp %can successfully generate hello.mexw64
>>hello
Hello, world!

Does that mean I installed the compiler successfully? (I only installed Microsoft Visual C++ 2017)

**Comment by AnderBiguri** [comment]
@sunchang2017 It could be, but the easier way to discovering it is to follow the instructions in the installation guide. 

If C++ works, then the problem must be a ad CUDA installation.

**Comment by civerjia** [comment]
I got the same issue, and my solution is to replace mex with mexcuda in compile.m

**Comment by AnderBiguri** [comment]
@civerjia well, yes, that is a possible solution of one of the possible causes of this problem. In your case, you did not have the CUDA paths set up well, thus using MATLAB's CUDA (if you have parallel computing toolbox) worked. MATLAB's CUDA version can be directly used by using `mexcuda` as you explain. 

But @sunchang2017 maybe does not have perellel comuting toolbox, or maybe doesnt have C++ compiler (seems that they have). So its not always the solution. 

Glad that you solved your problems though!

**Comment by civerjia** [comment]
@AnderBiguri  How to make CUDA paths set up well? I can get the correct result by using getenv('CUDA_PATH'), like 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1'. btw I'm using Visual Studio 2017

**Comment by AnderBiguri** [comment]
@civerjia I am going to admit that I don't really know... Each combinations of CUDA and VS has its own issues, and I have no idea why yours does not work with normal `mex`. 

Every time I tried it in my own windows machines, the instructions at https://github.com/CERN/TIGRE/blob/master/Frontispiece/MATLAB_installation.md#step-by-step-instructions worked well, but there is people who can't get it working... But its hard for me to debug anything, as I can not reproduce it. I mostly use ubuntu nowadays too, so even less windows testing...

**Comment by civerjia** [comment]
Ok thanks, the machine always has some unknown issues even everything looks good.

**Comment by sunchang2017** [comment]
I have compiled successfully!  I first installed MATLAB parallel computing toolbox, then I changed mex to mexcuda in Compiled.m.
So happy!!!!!
Thank you all~

**Comment by AnderBiguri** [comment]
@sunchang2017 glad you did! Feel free to ask any other question you may have in the future. I'll close the issue now.
