### ISSUE TITLE
FISTA on Multi-GPU 

### ISSUE THREAD

**Issue by genusn** [CERN/TIGRE#190]
## Expected Behavior
FISTA generates the same image regardless the number of GPU

## Actual Behavior
The bottom image of the FOV reconstructed by 1-GPU machine was different from that by 2-GPU.
The image of the 2-GPUs looks wrong.

Left column: FDK
Right column: FISTA

Upper row: bottom plane
Lower row: central plane

2-GPU
![FISTA_2gpu](https://user-images.githubusercontent.com/25704789/98053000-f1698580-1e7a-11eb-850d-6e3f875abc4e.jpg)

1-GPU

![FISTA_1gpu](https://user-images.githubusercontent.com/25704789/98052997-ed3d6800-1e7a-11eb-97fe-16d424322598.jpg)

## Code to reproduce the problem

```
clear;
close all;
geo=defaultGeometry('nVoxel',[128;128;128]);                     
angles=linspace(0,2*pi-2*pi/30,30);
head=headPhantom(geo.nVoxel);
projections=Ax(head,geo,angles,'interpolated');
nIter=3;
imgFDK = FDK(projections,geo,angles);
imgFISTA_default = FISTA(projections,geo,angles,nIter);
%% Plot the bottom of the FOV
subplot(2,2,1), imshow(imgFDK(:,:,1), 'DisplayRange',[])
subplot(2,2,2), imshow(imgFISTA_default(:,:,1), 'DisplayRange',[])
subplot(2,2,3), imshow(imgFDK(:,:,geo.nVoxel(3)/2), 'DisplayRange',[])
subplot(2,2,4), imshow(imgFISTA_default(:,:,geo.nVoxel(3)/2), 'DisplayRange',[])
```

## Specifications 
| Software        | Version           | 
| ------------- |:-------------:|
|**Windows**| 10 |
|**MATLAB**|  2016a |
|**CUDA**| 10.1|
|**Visual Studio**| 2015|
|**GPU**| GTX1060 |

| Software        | Version           | 
| ------------- |:-------------:|
|**Windows**| 10 |
|**MATLAB**|  2016a |
|**CUDA**| 10.1|
|**Visual Studio**| 2015|
|**GPU**| 2 x RTX2080Ti |

**Comment by AnderBiguri** [comment]
Thanks! I suspect it may be something to do with `tvdenoising.cu`, will check further.

**Comment by AnderBiguri** [comment]
This has been validated by a second user, that showed that on 2-GPU machines this can lead to CUDA errors and thus TIGRE errors. There is likely some memory access error somewhere in `tvdenoising.cu`.

**Comment by genusn** [comment]
@AnderBiguri https://github.com/CERN/TIGRE/blob/aab042202159181ca666bb0b7a8fba5592478b51/MATLAB/Source/tvdenoising.cu#L498-L505

Is it possible that these offsets of the destination of cudaMemcpyAsync, ```+slices_per_split+buffer_pixels```  are related to this issue?

**Comment by AnderBiguri** [comment]
So, what is happening here is that each of the slices has a buffer of overlapping image slices. So each GPU has its corresponding part of the image, plus few slices on top and on the bottom. What we see in the lines you listed is the piece of code that takes care syncronizing those buffers, to be able to continue iterating with the correct values. 

So, for each of the device variables, we just need to copy the upper chunk of the buffer from host to device. 

But indeed, the names of the variables are suspicious, as one seems to suggest its in slices and the other one in pixels. They should be both in pixels, I think.... So its plausible this is the source of errors indeed. 

I'd say that instead of `slices_per_split` that should be `slices_per_split*image_size[0]*image_size[1]`.... Need to test that.

**Comment by genusn** [comment]
@AnderBiguri Thank you for your suggestion. It seems to be working fine. I'll make a PR.

**Comment by AnderBiguri** [comment]
This is now fixed for MATLAB, I suspect not for python

**Comment by genusn** [comment]
I agree. tvdenoising.cu in master/MATLAB is copied into the branch for PR #189 because the MATLAB version is multi-GPU ready and I thought the Python version was not, but I now found now that the MATLAB and Python version in the master branch are "almost" the same.
Should I have firstly made another PR?

**Comment by AnderBiguri** [comment]
No, here it's OK, no worries! Thanks for the change! Yes, I think the TV parts are multi GPU as they are axis independent. They just work on 3D volumes, not important their direction.

**Comment by AnderBiguri** [comment]
@genusn the other user that complained about this says that this still fails in MATLAB. 

sorry to ask this, as I dont have a 2 GPU machine, I can not test. Can you try to run SART-TV on MATLAB with 2 GPUs?

**Comment by AnderBiguri** [comment]
False alarm the error may be something else.

**Comment by genusn** [comment]
@AnderBiguri 
> Can you try to run SART-TV on MATLAB with 2 GPUs?

False alarm, OK.
I revised the test program of #196 to use SART_TV and ran it just for confirmation and it was OK, but my machine has 2xRTX2080Ti, not P5000, and the image size was not so big (splits=1).
