### ISSUE TITLE
Ax (ray-voxel) produces defect lines with specific parameters

### ISSUE THREAD

**Issue by genusn** [CERN/TIGRE#198]
## Expected Behavior
![interpolated](https://user-images.githubusercontent.com/25704789/99951744-eb9ff980-2dc1-11eb-8052-1c2a926c078e.gif)

## Actual Behavior
If the components of dDetector are integers and at least one of nDetectorU and nDetectorV is (are) odd number(s), the result of Ax of "ray-voxel" has defect line(s).

![rayvoxel](https://user-images.githubusercontent.com/25704789/99951760-f22e7100-2dc1-11eb-8247-dcd919bc1622.gif)

I compared the results of "ray-voxel" and "interpolated" and obtained the image as below:

![diffabs](https://user-images.githubusercontent.com/25704789/99951804-04101400-2dc2-11eb-9b41-a9c8f697481a.gif)

  - revision: 220935a

## Code to reproduce the problem (If applicable)

```
clear;
close all;

nangles=30;
nVoxelX=128;
nVoxelY=128;
nVoxelZ=128;
nDetectorU=251;  % virtical line of 'degee 0' at 251, not: 250
nDetectorV=251;  % horizontal line at 251,249, 125,.. not at 120,100,250
    
geo=defaultGeometry('nVoxel',[nVoxelX;nVoxelY;nVoxelZ]);
geo.nDetector=[nDetectorU; nDetectorV];
geo.dDetector = [1; 1]*2;  % 2 can be replaced with (maybe) any integer
geo.sDetector=geo.nDetector.*geo.dDetector;

angles=linspace(0,2*pi-2*pi/nangles,nangles);
head=headPhantom(geo.nVoxel);

proj_rayvoxel=Ax(head,geo,angles,'ray-voxel');
proj_interp  =Ax(head,geo,angles,'interpolated');

plotProj(proj_rayvoxel, angles, 'savegif', 'rayvoxel.gif') % Looks wrong
plotProj(proj_interp, angles, 'savegif', 'interpolated.gif')   % Looks correct
plotProj(abs(proj_rayvoxel-proj_interp), angles, 'savegif', 'diffabs.gif')
```

## Specifications 

  - MATLAB version: 2016a
  - OS: Windows 10
  - CUDA version: 10.1
  - GPU: 1 x GTX1060

 * This also occurs in Python.

**Comment by AnderBiguri** [comment]
Ah yes.... This is caused by finite precision on forward projectors. 

I think the only solution to this is to catch the conditions on the cuda side (odd detector, even image, zero vOffset, zero zOffset) and then simply add epsilon (0.000001) to any of the offsets. This would avoid the numerical error of the rays intersecting with the boundary of 2 layers of voxel.

I'll give it a go as soon as I have some time, thanks!

**Comment by AnderBiguri** [comment]
@genusn made a PR, works on my side, but would be nice if you can test it on your side too, just to double check. Let me know if that is possible, otherwise I'll just merge.
