### ISSUE TITLE
Change python's projector type variable name

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#209]
Krylov makes no sense and it comes from a copy paste. Should be `proj_type` or something similar. 

`tigre.Ax(head,geo,angles, krylov="interpolated")`

**Comment by genusn** [comment]
If you are considering changing that option, there is one thing that I want you to consider together. When I started using TIGRE, it seemed to me that the term "ray-voxel" is not self-explanatory. I expected something like "siddon-jacobs", "siddon", "jacobs", "matched (not good as an option of Ax)" etc. I am not sure other potential user may feel so.

**Comment by AnderBiguri** [comment]
@genusn fully agree

**Comment by AnderBiguri** [comment]
Reopening this because we also need to change the one for `Atb()` to something more sensible, plus change its default value.

**Comment by tsadakane** [comment]
@AnderBiguri 
Change
```
def Atb(projections, geo, angles, krylov="matched", **kwargs):
```
to 
```
def Atb(projections, geo, angles, backprojection_type="FDK", **kwargs):
```
?

**Comment by AnderBiguri** [comment]
@tsadakane correct. the variable name shoudl be `backprojection_type` and shoudl be able to take FDK and matched, but FDK as default. This also means making sure algorithms use the correct backprojection (matched for FISTA and CGLS, FDK for the rest)
