### ISSUE TITLE
Harmonize python/MATLAB demos

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#219]
Ideally we'd have the same examples in both. The python ones are particularly lacking.

**Comment by yliu88au** [comment]
Good idea. So far I could not get python versions algorithms (particularly POCS) to agree with MATLAB version.

**Comment by genusn** [comment]
As for demos, do you keep using jupyter notebooks or migrate to python scripts?

**Comment by AnderBiguri** [comment]
@genusn still unsure. 

I really like jupyter notebooks when they are proper, as they can be rendered in Github, so one can have demos without even running them. But also they are a bit more of a paint to maintain and use in github. 

I though about making 2 set of "demos": demos and exercises. The first being basically the same as in MATLAB, using basic python scripts and the second just a limited amount of "shiny" visual examples, with tidier comments, plots etc using jupyter. As they currently are, there is no advantage of having the demos in jupyter, as they barely use the power of the notebooks (markdown, latex, plots etc). 


Of course, then I never get to do any of this, because its too many thins hehe.

**Comment by AnderBiguri** [comment]
fair point. 

Thing is, MATLAB also has its own notebook system, that basically is a copy of what a jupyter notebook is. 
I think its likely better to have just all in standard MATLAB and python, then as you say, if at some point we have much nicer examples to show, we can either make a new repo  TIGRE-examples, or simply make a folder in Frontispiece with nice visual examples that work well in Github itself. 

This is what you meant right?

**Comment by yliu88au** [comment]
@AnderBiguri I still could not get Python examples to agree with MATLAB for the POCS algorithms, even with the same setups I used. I have compared all CUDA sources (*.cu), the main difference between MATLAB and Python versions are lines:

"#if IS_FOR_MATLAB_TIGRE"
   "......"
"#else"
   "......"
"#endif"

My understanding of these lines are to deal with "row_major" and "column_major" difference in storing data in MATLAB and Python. However, I have found that there are 3 files: tvdenoising.cu, POCS_TV.cu, and POCSTV2.cu are identical for both MATLAB and Python. Do we still have the same row_major/column_major problem within these files?

**Comment by AnderBiguri** [comment]
@yliu88au  do you have example code to reproduce this? Maybe we should open a different issue on the topic. I suspect its not the CUDA code, as the TV calculation is symmetric, thus axis-changing should not have an impact on the TV computation. Maybe something else is off...

**Comment by AnderBiguri** [comment]
I have started working on this on #263

**Comment by AnderBiguri** [comment]
This is not 100% solved, but almost, so I will close this issue and we can now open specific issues for each missing/unmatched demo.
