### ISSUE TITLE
FDK does a different thing in MATLAB and python

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#229]
#223

**Comment by genusn** [comment]
Tested.

## Preparation on MATLAB
```
%%
clear;
close all;

%% Prepare image
nangles = 36;  % 512
nVoxelX = 100;%200;
nVoxelY = 111;%251;
nVoxelZ = 90;%303;
nDetectU = 128;%256;
nDetectV = 100;%128;
dDetect  = 0.8*4; % *2
geo=defaultGeometry('nVoxel',[nVoxelX;nVoxelY;nVoxelZ]);
geo.nDetector=[nDetectU;nDetectV];
geo.dDetector=[dDetect; dDetect]; 					% size of each pixel            (mm)
geo.sDetector=geo.nDetector.*geo.dDetector; % total size of the detector    (mm)
angles=linspace(0,2*pi,nangles);
head=headPhantom(geo.nVoxel);
projections=Ax(head,geo,angles,'interpolated');
noise_projections=addCTnoise(projections);
%%
save('angles.mat', 'angles', '-v7')
%%
save('matProj.mat', 'noise_projections', '-v7')
imgFDK=FDK(noise_projections,geo,angles);
%% Save image
save('matFDK.mat', 'imgFDK', '-v7');

%%
plotProj(noise_projections, angles);

```
## Test on Python
```
#%%
import scipy as sp
import scipy.io
import numpy as np
import tigre
import matplotlib.pyplot as plt


#%%
pathFDK = "../MATLAB/matFDK.mat"
pathProj = "../MATLAB/matProj.mat"
pathAngles = "../MATLAB/angles.mat"

obj_matFDK = scipy.io.loadmat(pathFDK)
obj_matProj = scipy.io.loadmat(pathProj)

print(type(obj_matFDK))
print(obj_matFDK.keys())
print(obj_matFDK['imgFDK'].shape)

imgFDK_mat  = obj_matFDK['imgFDK'].transpose((2,1,0)).copy() # shape must be reorganized as (303, 201, 100)
imgProj_mat = obj_matProj['noise_projections'].transpose((2,0, 1)).copy()
print("imgFDK_mat.shape", imgFDK_mat.shape)
print(imgProj_mat.shape)
# %%
if True:
    # load angles of matlab.
    obj_Angles = scipy.io.loadmat(pathAngles)
    angles  = obj_Angles['angles'].reshape((-1)).copy()
    print("loaded angles: {}".format(angles.shape))
    nangles = angles.shape[0]
else:
    # create equivallent angles
    nangles = 36
    angles=np.linspace(0,2*np.pi,nangles, endpoint=True)
nVoxelX = 100 #200
nVoxelY = 111 #251
nVoxelZ = 90  #303
nDetectU = 128 #256
nDetectV = 100 #128
dDetect = 0.8*4  #*2
geo=tigre.geometry(nVoxel=np.array([nVoxelZ,nVoxelY,nVoxelX]), default=True)
geo.nDetector=np.array([nDetectV,nDetectU])
geo.dDetector=np.array([dDetect, dDetect]) 				# size of each pixel            (mm)
geo.sDetector=geo.nDetector*geo.dDetector; # total size of the detector    (mm)
print("angles.shape = {}".format(angles.shape))
imgFDK_py = tigre.algorithms.fdk(imgProj_mat, geo, angles)
print("imgFDK_py.shape", imgFDK_py.shape)
imgDiff = np.abs(imgFDK_mat-imgFDK_py)

maxDiff = np.max(imgDiff)
minDiff = np.min(imgDiff)
print("diff is in [{}, {}]".format(minDiff, maxDiff))

#%%
tigre.plotImg(imgDiff, savegif="imgDiffY.gif")
tigre.plotImg(imgDiff, savegif="imgDiffZ.gif", dim='Z')
#%%
plt.imshow(np.hstack((imgFDK_mat[nVoxelZ//2], imgFDK_py[nVoxelZ//2])))
plt.show()

```

## Result
The maximum difference between the corresponding voxels was 2.2370368242263794e-06. 
```
diff is in [0.0, 2.2370368242263794e-06]
```
![imgDiffY](https://user-images.githubusercontent.com/25704789/103045283-38e0d800-45c7-11eb-979c-3c4b07cb86dd.gif)

![imgDiffZ](https://user-images.githubusercontent.com/25704789/103045277-31b9ca00-45c7-11eb-995e-2ac741b19eab.gif)


What do you think @AnderBiguri , @yliu88au ?

**Comment by yliu88au** [comment]
@genusn Very interesting! I just cannot see what was wrong with my following two tests:
Python:

        from __future__ import print_function
        from __future__ import division
        import tigre
        import tigre.algorithms as algs
        import numpy as np
        from matplotlib import pyplot as plt
        from tigre.utilities.Measure_Quality import Measure_Quality
        from scipy.io import loadmat
        
        geo = tigre.geometry(mode='cone', nVoxel=np.array([256,256,256]),default=True)
        geo.dDetector = np.array([0.8, 0.8])*2               
        geo.sDetector = geo.dDetector * geo.nDetector
        geo.accuracy = 0.1
        
        niter = 20
        nangles = 101
        angles = np.linspace(0, 2 * np.pi, nangles, dtype=np.float32)
        head=loadmat('head.mat')['img'].transpose(2,1,0).copy()
        proj = tigre.Ax(head,geo,angles)
        fdkout = algs.fdk(proj,geo,angles)
        sirtout = algs.awasd_pocs(proj,geo,angles,niter,init='FDK',blocksize=20,tviter=20,maxl2err=0.5,alpha=0.08,delta=-0.01)
        
        print('RMSE fdk:')
        print(Measure_Quality(fdkout,head,['nRMSE']))
        print('RMSE osawasdpocs')
        print(Measure_Quality(sirtout,head,['nRMSE']))
        
        plt.subplot(131)
        plt.imshow(head[63,:,:])
        plt.subplot(132)
        plt.imshow(fdkout[63,:,:])
        plt.subplot(133)
        plt.imshow(sirtout[63,:,:])
        plt.show()

Results:
        RMSE fdk:
        0.17262956846694968
        RMSE osawasdpocs
        0.0861031033908827
![image](https://user-images.githubusercontent.com/75292881/103047854-ef9d8200-45e0-11eb-9a79-2fc0ab087a93.png)


MATLAB:

        InitTIGRE        
        geo = defaultGeometry();
        geo.mode='cone';
        geo.nVoxel=[256;256;256];
        geo.sVoxel=geo.nVoxel*1.0;
        geo.dVoxel=geo.sVoxel./geo.nVoxel;          % size of each voxel            (mm)
        geo.dDetector = [0.8; 0.8]*2;               % size of each pixel            (mm)
        geo.nDetector = [256;256];
        geo.sDetector = geo.dDetector .* geo.nDetector;
        geo.offDetector = [0;0];                   % Offset of Detector            (mm)
        
        geo.accuracy = 0.1;
        
        niter = 20;
        nangles = 101;
        angles = linspace(0, 2 * pi, nangles);
        
        head = load('head.mat');
        head=head.img;
        %head = imresize3(head.img,[256,512,128]);
        proj = Ax(head,geo,angles); 
        fdkout = FDK(proj,geo,angles); 
        awasdpocsout = OS_AwASD_POCS(proj,geo,angles,niter,'Init','FDK','TViter',20,'blocksize',20,'maxL2err',0.5,'alpha',0.08,'delta',-0.01);
        
        subplot(131)
        imshow(head(:,:,64))
        subplot(132)
        imshow(fdkout(:,:,64))
        subplot(133)
        imshow(awasdpocsout(:,:,64))
        
        disp(['RMSE fdk: ' num2str(Measure_Quality(head,fdkout,{'RMSE'}))])
        disp(['RMSE awasdpocs: ' num2str(Measure_Quality(head,awasdpocsout,{'RMSE'}))])

Results:
RMSE fdk: 0.039947
RMSE awasdpocs: 0.023778

![image](https://user-images.githubusercontent.com/75292881/103047898-0fcd4100-45e1-11eb-8d4c-dc8a49eda7f2.png)

You have used 'interpolated' projection, I have used default (Siddon) project, that is all difference I can see. Puzzled!

**Comment by genusn** [comment]
@yliu88au Interesting! I modified MATLAB code as
```
%projections=Ax(head,geo,angles,'interpolated');
projections=Ax(head,geo,angles);
```
and re-run the python code. Obtained almost the same result:
```
diff is in [0.0, 2.2351741790771484e-06]
```
My test uses the projections generated by MATLAB to focus on the FDK process.

What happens if you save ```proj``` in MATLAB and load it from Python?

**Comment by yliu88au** [comment]
@genusn Sorry, My bad, I was calculating 'nRMSE" in Python, compared with "RMSE" in MATLAB.
Now, the error in Python are:

RMSE fdk:
0.03994673895037564
RMSE osawasdpocs
0.019924386213311437

 Much closer to the results of MATLAB. I think we can safely close this case now. @AnderBiguri
