### ISSUE TITLE
setup.py is for CUDA 11

### ISSUE THREAD

**Issue by franzpx125** [CERN/TIGRE#231]
Installation Instructions for Python reports that CUDA 10.1 was successfully tested (on Windows). However, setup.py includes:

-gencode=arch=compute_86,code=sm_86

which seems to me is available only on CUDA 11.

**Comment by AnderBiguri** [comment]
@franzpx125 ah, absolutely. I should change the documentation to clarify that. Its an easy fix, you just need to remove that line, and it will compile in 10.1. 

I should find a way to have a flexible `setup.py`, as TIGRE does not really care which CUDA is being used, as long as its newer than 9.2...

**Comment by AnderBiguri** [comment]
@franzpx125 this is now fixed and setup.py will accept any CUDA. Thanks for raising this.
