### ISSUE TITLE
something with size of reconstruction image in d09_Algorithms04.m

### ISSUE THREAD

**Issue by ilanzhang** [CERN/TIGRE#24]
Hi again @AnderBiguri, Last time I found the code run well with the projections you provide but crashed with a hint which is wrong use of minTV.mexw64 applying mine. Just now I found that, the size of reconstruction image maybe result in that, because the matlab crashed when I set the`geo.nVoxel=[256;256;170];`,but the code just worked well with `geo.nVoxel=[256;256;256];`. Obviously memory isn't the problems here, Could you please tell me the reasons?

**Comment by AnderBiguri** [comment]
@ilanzhang  Thanks for reporting this. I am going to check it out and fix it as soon as possible.
I am quite confident this may be due to some internal bug. Will come back with an answer this week.

**Comment by AnderBiguri** [comment]
@ilanzhang  Thanks for reporting this! The development version ha sit fixed, the next release will have it included.

**Comment by ilanzhang** [comment]
@AnderBiguri Thank you!

**Comment by ilanzhang** [comment]
@AnderBiguri Hi, you just do an efficient work! In the lastest version, the computing time of OS-SART is between SIRT and SART which I think is reasonable while in the last version, the computing time of OS-SART is much shorter than SART and SART. Could you tell me why the computing time of OS-SART in the 2 versions is different?

**Comment by AnderBiguri** [comment]
The last version has some improvements in the backprojection step of the
algorithms that makes it scale non-linearly with number of projections.
The speedup is unexistent for SART.  It is indeed very interesting to see
that OS-SART can be the fastest,  but it won't be for all cases,  it
depends on number of projections used.  Don't worry,  this is not a  bug.

I will try to make some tests to further analize this behaviour,  but you
may only be getting the fastest OS-SART for your specific configuration of
total number of projections and block size.

Best
Ander

**Comment by ilanzhang** [comment]
@AnderBiguri Thanks for explaining!

**Comment by AnderBiguri** [comment]
If you are more interested I  technicalities I can refer you to the papers
that discuss this.
Ander
