### ISSUE TITLE
No module named '_Ax'

### ISSUE THREAD

**Issue by JitendRathore** [CERN/TIGRE#246]
Hello, 

I was trying to implement the TIGRE module, I setup the environment following the instructions:

I already had the python
Installed Visual Studio
Installed CUDA
Downloaded TIGRE-master
run python setup.py install --user in the pyhton folder (with CUDA 10.1 this did not work so I upgraded to 11)

It looked, that the steps worked fine.
![xx](https://user-images.githubusercontent.com/78167947/106258323-f6419980-621d-11eb-9b8e-8c1497a6a5d9.png)

But while running the example.py file, there seems to be an error as “No module named _Ax”
![www](https://user-images.githubusercontent.com/78167947/106257698-2fc5d500-621d-11eb-9edc-1a92e6fbe8e0.png)

## Specifications 

  - Python version: Python 3.7.6
  - OS: Windows 10
  - Visual Studio Community 2019
  - CUDA version: cuda_11.2.0_460.89_win10

**Comment by AnderBiguri** [comment]
Thanks! It did not work for 10.1 because my instructions are unfinished, there is just a single line in `setup.py` that basically targets most modern GPUs, and that requires CUDA 11.0. However, this information is not too useful for you. 

Let me try to install those versions on my windows PC, see if I get the same errors.... 
Meanwhile if anyone else knows how to solve the issue, feel free to pitch in.

**Comment by AnderBiguri** [comment]
Hi again @JitendRathore

Can you verify you are using Python 3.7? There has been some reports of TIGRE not working on python 3.8 and 3.9, and your output suggest you are using 3.9:



> ![xx](https://user-images.githubusercontent.com/78167947/106258323-f6419980-621d-11eb-9b8e-8c1497a6a5d9.png)

**Comment by JitendRathore** [comment]
Actually, I just checked it seems I have both python 3.7 and 3.9 on my system and I tried on both it does not work on either and give the same error: 
In 3.9: ImportError: DLL load failed while importing _Ax: Le module spécifié est introuvable. (The specified module could not be found.)
In 3.7: No module named '_Ax'

**Comment by AnderBiguri** [comment]
It is likely that you compiled `python setup.py install --user` using python 3.9, and this is why you are getting this error when running with either 3.9 and 3.7 the code. Try to rebuild (delete contents of `/build` folder, just in case) making sure you use 3.7, and try again.

**Comment by JitendRathore** [comment]
I deleted the the contents on `/build` and complied again `python setup.py install --user` now it gives another error
![xx](https://user-images.githubusercontent.com/78167947/106268659-b08bcd80-622b-11eb-84ac-784732741091.png)

**Comment by AnderBiguri** [comment]
Hi @JitendRathore ,

Can you please post the entire message, in text format?

**Comment by JitendRathore** [comment]
Using c:\users\jr\anaconda3\lib\site-packages
Finished processing dependencies for pytigre==0.1.8

(base) C:\Users\JR\AdvanCT_project\TIGRE-master\Python>python example.py
tigre/Source/TIGRE_common.cpp (7): kernel fail
tigre/Source/TIGRE_common.cpp (14): Ax:Siddon_projection invalid device symbol

**Comment by AnderBiguri** [comment]
@JitendRathore  which GPU are you using?

**Comment by JitendRathore** [comment]
it is NVIDIA QuadroM1200 version 460.89

**Comment by AnderBiguri** [comment]
Hum, you may have found a bug that almost only apply to your GPU. 

Lets try one thing: Can you open `setup.py`  and go to lines 18-29: 

```
COMPUTE_CAPABILITY_ARGS = [  # '-gencode=arch=compute_20,code=sm_20', #deprecated
    '-gencode=arch=compute_30,code=sm_30',
    '-gencode=arch=compute_37,code=sm_37',
    '-gencode=arch=compute_52,code=sm_52',
    '-gencode=arch=compute_60,code=sm_60',
    '-gencode=arch=compute_61,code=sm_61',
    '-gencode=arch=compute_70,code=sm_70',
    '-gencode=arch=compute_75,code=sm_75',
   '-gencode=arch=compute_86,code=sm_86',
    '--ptxas-options=-v', '-c',
    '--default-stream=per-thread',
    ]
```
and ad a line that says teh following, just after the 37 one: 

`   '-gencode=arch=compute_50,code=sm_50',
`
Then run setup again, and test again. 
I think we just missed your GPU in the compilation options, apologies!

**Comment by JitendRathore** [comment]
Thank you Ander. It is working now.

**Comment by AnderBiguri** [comment]
@JitendRathore  wonderful!

Don't hesitate to ask more questions!
