### ISSUE TITLE
Python does not work for 3.8 and/or 3.9 on windows

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#247]
It gives error "`no module named _Ax`"

I think this only happens with python _not from Anaconda_.

**Comment by genusn** [comment]
While ```building '_Ax' extension```, my compiler complains as below:
```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe -c tigre/Source/Siddon_projection.cu -o build\temp.win-amd64-3.8\Release\tigre/Source/Siddon_projection.obj -IC:\opt\anaconda3\envs\dev\lib\site-packages\numpy\core\include "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -ISource -IC:\opt\anaconda3\envs\dev\include -IC:\opt\anaconda3\envs\dev\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" "-IC:\Program Files (x86)\Intel\IPP\6.1.6.056\em64t\include" "-IC:\Program Files (x86)\Intel\IPP\6.1.6.056\ia32\include" -Xcompiler /EHsc -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_86,code=sm_86 --ptxas-options=-v -c --default-stream=per-thread --define-macro IS_FOR_PYTIGRE
nvcc fatal   : Unsupported gpu architecture 'compute_30'
```

Tested on a fresh clone in a dedicated folder on a machine of following specs:

| Software        | Version           | 
| ------------- |:-------------:|
|**Windows**| 10  64bit |
|**Python(anaconda)**|  3.8.5 |
|**CUDA**| 11.1|
|**Visual Studio**| 2019 |
|**GPU**| GTX1060 |

**Comment by AnderBiguri** [comment]
That is due to a separate thing: you are using CUDA 11.1 which does not support cc_30 anymore.

Comment that architecture in the setup.py (technically you can just leave the one for your gpu)

**Comment by AnderBiguri** [comment]
Have fixed your error in commit https://github.com/CERN/TIGRE/commit/4eca27945c42d8aa0944eca014ce0fdc9d6d8b0d, now there is no need to edit setup.py depending on the CUDS SDK version.

**Comment by genusn** [comment]
Thank you very much for your updating, but in my environment, it failed in ```setup.py``` with error
```
Traceback (most recent call last):
  File "setup.py", line 37, in get_cuda_version
    with open(version_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.1\\version.txt'
```
I am sure my CUDA installation has been done in a standard manner.

**Comment by genusn** [comment]
I found that version.txt exists in v9.0 and v10.1, but not in v11.1

**Comment by AnderBiguri** [comment]
Huh interesting. Unsure if NVIDIA keeps changing stuff or some bug in my code.

Is that the location of your CUDA on your PC? If so, can you see if there is a file named like that, or something similar?

In any other older version, its  a file just containing the text: `CUDA Version 10.2.89`

**Comment by AnderBiguri** [comment]
Ah, interesting find... I need to find a different way to solve this issue then. Ouch.

**Comment by genusn** [comment]
```
nvcc --version
```
or something like that?

**Comment by AnderBiguri** [comment]
Yes, it will have to be that. I was trying to avoid it because it means calling the `nvcc` and I also don't know if they changed the way they print that.

**Comment by AnderBiguri** [comment]
@genusn  can you test the latest commit?

**Comment by genusn** [comment]
@AnderBiguri It stopped immediately without any output.
v.11 outputs an extra line. 
```
$ /c/Program\ Files/NVIDIA\ GPU\ Computing\ Toolkit/CUDA/v8.0/bin/nvcc.exe -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Mon_Jan__9_17:32:33_CST_2017
Cuda compilation tools, release 8.0, V8.0.60

$ /c/Program\ Files/NVIDIA\ GPU\ Computing\ Toolkit/CUDA/v9.0/bin/nvcc.exe -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:32_Central_Daylight_Time_2017
Cuda compilation tools, release 9.0, V9.0.176

$ /c/Program\ Files/NVIDIA\ GPU\ Computing\ Toolkit/CUDA/v10.1/bin/nvcc.exe -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:11:20_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.168

$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:54:10_Pacific_Daylight_Time_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.relgpu_drvr455TC455_06.29190527_0
```

**Comment by AnderBiguri** [comment]
Oppps! Remove the following, try again:

https://github.com/CERN/TIGRE/blob/master/Python/setup.py#L91

**Comment by genusn** [comment]
```
Traceback (most recent call last):
  File "setup.py", line 92, in <module>
    if float(CUDA_VERSION) < 11.0:
ValueError: could not convert string to float: 'uda_'
```
My suggestion is to use $2 of 
```
(Cuda compilation tools, release)\s*(\d+\.\d+)
```

**Comment by AnderBiguri** [comment]
Will try to install CUDA 11 and test it myself

**Comment by AnderBiguri** [comment]
It works well on 11.0.

**Comment by AnderBiguri** [comment]
It also works well in 11.1 on my machine. 

Can you try to debug why you got that message? From your output, I cant see how the current `setup.py` can cause the error you got (to grave `uda_` as string for version, instead of `11.1`)

**Comment by genusn** [comment]
@AnderBiguri  Thank you very much. It worked fine.
I think the code that I tried last was ```...[-1]...[xx:yy]```-ish, but I don't remeber well. I think I might have done some mistake while updating my workspace.
