### ISSUE TITLE
set_cuda_cc_flags() cannot work fine on Linux;

### ISSUE THREAD

**Issue by aspfate** [CERN/TIGRE#254]
## Expected Behavior
build success

## Actual Behavior
build failed

## Code to reproduce the problem (If applicable)

```

```

## Specifications 

  - MATLAB version:2020b
  - OS:Centos8
  - CUDA version:11.0

new introduced set_cuda_cc_flags() function don't compatible with mex_CUDA_glnxa64.xml struct.

**Comment by AnderBiguri** [comment]
Thanks! Fixed :)
