### ISSUE TITLE
Error in running Compile.m on Matlab 2016a

### ISSUE THREAD

**Issue by genusn** [CERN/TIGRE#273]
## Actual Behavior
```
>> Compile
Error: File: Compile.m Line: 1 Column: 1
Function definitions are not permitted in this context.
```

## Specifications 
Failed:
  - MATLAB version: Matlab 2016a
  - OS: Windows 10
  - CUDA version: CUDA 11
  - Visual Studio 2015

 Succeeded:
  - MATLAB version: Matlab 2021a
  - OS: Windows 10
  - CUDA version: CUDA 11
  - Visual Studio 2019
 
## Cause
According to https://www.mathworks.com/help//matlab/matlab_prog/local-functions-in-scripts.html , it seems that no function definition in a script file is allowed before 2016b. `Compile.m` includes definitions of locate_cuda() etc.

I think there are two options: to remove 2016a and before from the list or to move the definitions to `Utilities` folder or somewhere and add `addpath('./Utilities');`-ish line to `Compile.m`.

**Comment by AnderBiguri** [comment]
Ah, that is correct! Maintaining this many versions is always a headache. 

I think the second option is best, simply because its almost no effort, and keeps compatibility alive for longer.
