### ISSUE TITLE
plotting function in python to have optional show()

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#285]
If you are running on a machine without GUI, plt.show() will error. 

Perhaps having an user-switch to turn this off (or change it to plt.savefig(), if this works in non-graphical machines) would be good. 

Can this be automatically detected? (maybe just a try-except ?)

**Comment by genusn** [comment]
@AnderBiguri  `matplotlib.get_backend()` may work. I haven't tested it, though. https://stackoverflow.com/questions/3580027/how-do-you-determine-which-backend-is-being-used-by-matplotlib
