### ISSUE TITLE
Orientation of Phantoms

### ISSUE THREAD

**Issue by tsadakane** [CERN/TIGRE#287]
## Expected Behavior

Orientation of the Head and Shepp-Logan  phantoms are the same.

## Actual Behavior

![phantoms](https://user-images.githubusercontent.com/40597344/116426083-c5551d00-a87d-11eb-9dd7-b9e32815f697.gif)

The AP direction of the head phantom is Y+, and that of the SL phantom is X+.

SL phantom matrix does not seems to match the memory layout described at https://github.com/CERN/TIGRE/issues/191#issuecomment-750699972

## Code to reproduce the problem (If applicable)

```
%% Initialize
clear;
close all;
%% Define Geometry
geo=defaultGeometry('nVoxel',[64; 128; 256]);   
%% Sample data:
shepp_type='Modified Shepp-Logan';  % (default).
shepp=sheppLogan3D(geo.nVoxel,shepp_type); % Default are 128^3 and Modified shepp-logan
head=headPhantom(geo.nVoxel); %default is 128^3
%% Plot
plotImg([head  shepp],'Dim','Z','Savegif','phantoms.gif');
```

## Specifications 

  - MATLAB version: 2021a
  - OS: Windows 10
  - CUDA version: 11.1

## Proposal
Modify `sheppLogan3D.m` as below:
```
if nargin==0
    sz=[128,128,128];
    type='modified shepp-logan';
else
    if nargin<2
    type='modified shepp-logan';
    end
end
sz = [sz(2), sz(1), sz(3)];   % ADD
warning('This file is NOT under BSD license!')
[p,ellipse]=phantom3dAniso(sz,type);
p=permute(p, [2,1,3]);  % ADD
p=single(p);
% p=[];
end
```
, which results in 
![phantoms_modified](https://user-images.githubusercontent.com/40597344/116428783-33024880-a880-11eb-8d92-77c464709ca7.gif)

**Comment by AnderBiguri** [comment]
Good catch! thanks a lot!

Would you be happy to make a Pull request with your proposed solution?
