### ISSUE TITLE
ImportError: DLL load failed while importing _Ax: The specified module could not be found.

### ISSUE THREAD

**Issue by SamJPHarris** [CERN/TIGRE#294]
## Expected Behavior
TIGRE has been running fine until this morning when I installed a package that would allow me to call MATLAB functions from within Python. Now when I run code that has worked previously I am met with "ImportError: DLL load failed while importing _Ax: The specified module could not be found"

## Actual Behavior
>> import tigre
ImportError: DLL load failed while importing _Ax: The specified module could not be found

## Code to reproduce the problem (If applicable)

```

```

## Specifications 

  - Python version: 3.8.5 (Anaconda)
  - OS: Windows 10
  - CUDA version: 11.3.0

**Comment by AnderBiguri** [comment]
Hum, I have no idea. Let me dig into this further to see if I can find a solution. 

Which package did you install?

**Comment by SamJPHarris** [comment]
I followed the installation instructions on https://uk.mathworks.com/help/matlab/matlab_external/install-the-matlab-engine-for-python.html

**Comment by SamJPHarris** [comment]
Hi Dr. Biguri,

I think I fixed that problem but now I get another error message only from
trying to import tigre in the anaconda console:

import tigre
Traceback (most recent call last):

  File "<ipython-input-1-f8af9a001cc7>", line 1, in <module>
    import tigre

  File
"C:\Users\Harri2_s\AppData\Roaming\Python\Python37\site-packages\pytigre-2.1.0-py3.7-win-amd64.egg\tigre\__init__.py",
line 4, in <module>
    from .utilities.Ax import Ax

  File
"C:\Users\Harri2_s\AppData\Roaming\Python\Python37\site-packages\pytigre-2.1.0-py3.7-win-amd64.egg\tigre\utilities\Ax.py",
line 4, in <module>
    from _Ax import _Ax_ext

*ImportError: DLL load failed: The specified module could not be found.*


Have you seen this type of error before and do you have any suggestions as
to how I should fix it?

Thank you so much for your help
Sam

**Comment by AnderBiguri** [comment]
Hi @SamJPHarris , 

This seems to be the same error as before?
Interestingly this does not match with what you were saying before, as the error is from python 3.7, not python 3.8.5 (anaconda), according to your folders. 
I really don't know how to help, seems that it has to do again with whatever configuration you have in your machine. I have only seen this error on windows when there was something wrong with the setup. I assume you have recompiled just in case?
