### ISSUE TITLE
ComputeV fails for detector offset

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#301]
the 0.9 multiplier in computeV creates ring artifacts in detector offset recons. 

Why is that there? I forgot.

**Comment by yliu88au** [comment]
I think it is there for keeping the back-projection of unity matrix (Vs) does not have zeros. Offset may make this logic fail, hence the artefacts. Should check if geox has correct settings.

**Comment by AnderBiguri** [comment]
@yliu88au thanks for the clarification! 

I see and that makes sense. I think the better solution is perhaps to increase the size of the detector, instead of shirking the image size. I think that should be enough to make sure there are no zeros, while maintaining the correct pixel value in the V matrix.

**Comment by AnderBiguri** [comment]
nah, that does work to remove zeroes, but does not work with offsets.

**Comment by AnderBiguri** [comment]
Seems that the easy solution was to simply +0.000001 to V with standard geo.
