### ISSUE TITLE
Cmake to install TIGRE

### ISSUE THREAD

**Issue by Neilblaze** [CERN/TIGRE#306]
## Expected Behavior
I'm trying to compile TIGRE via Cmake v3.21.0, but I'm getting few errors on my system. This is the log that I'm getting `CMake Error: Error executing cmake::LoadCache(). Aborting.` 

## Specifications 

  - MATLAB version: R2021a
  - OS: Windows 10 pro x64 | WSL
  - CUDA version: 11.3.0

**Comment by AnderBiguri** [comment]
Hi @Neilblaze
There is no Cmake files in Tigre, it is currently not supported for compiling. I am not very sure how you are even calling it to be honest! 
Try the instalation instructions

**Comment by Neilblaze** [comment]
I recently upgraded my CUDA, since then I'm facing some issues during installation, but later found a solution on StackOverflow which didn't work.

@AnderBiguri  I was going through the issues where I found an [issue](https://github.com/CERN/TIGRE/issues/251) where I thought apart from the normal instructions, I could install TIGRE via Cmake. So, I tried running Cmake with the filepath as it's source, but it's showing the mentioned error. I actually thought that support for Cmake might have been added to this.

**Comment by AnderBiguri** [comment]
No, unfortunately that is not right. The issue is there because I want to enable Cmake compilation, but its open because its still not there.

**Comment by Neilblaze** [comment]
Ah I see. Thanks for the info :)

**Comment by AnderBiguri** [comment]
No worries. Do let me know if you have any issue compiling the normal way :+1:

**Comment by Neilblaze** [comment]
@AnderBiguri Sure! I'll. Also, is CUDA mandatory for TIGRE? or is there any bypass method?

**Comment by AnderBiguri** [comment]
No theres not. The core of the entire toolbox is that it uses GPUs for computing, and this was coded in CUDA.

**Comment by Neilblaze** [comment]
Ok, let me see if I can resolve the installation issue. If I get stuck at any point, I'll let you know. Thanks again 😄
