### ISSUE TITLE
'conegeometrydefault' object has no attribute 'convert_contig_mode'

### ISSUE THREAD

**Issue by xiaoxiaobao1992** [CERN/TIGRE#307]
when I ran 'python d03_generatedate.py'
I got the AttributeError: 'conegeometrydefault' object has no attribute 'convert_contig_mode'

  - Python2.7 version:
  - CUDA version: 9.2

**Comment by AnderBiguri** [comment]
Did you solve your issue then?

**Comment by xiaoxiaobao1992** [comment]
> Did you solve your issue then?

No. But it works when switched to Win10. 
Thanks for your reply！
