### ISSUE TITLE
Implement FDK filtering on GPU

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#312]
Suprising I don't have an issue for this: 

FDK filtering is slow now because its done in the CPU (and does some ugly transposes). 
We should just accelerate this, it makes no sense to have such a slow version of FDK. 

Note: Not all FFT libraries in GPU/CPU are compatible with BSD license.

**Comment by tsadakane** [comment]
Use cuFFT?

**Comment by AnderBiguri** [comment]
Sounds good actually.

**Comment by AnderBiguri** [comment]
I'll close this for now, as #423 suggests this is not a good idea.
