### ISSUE TITLE
Tomosynthesis 

### ISSUE THREAD

**Issue by ghan7213** [CERN/TIGRE#315]
Would you modify it to work the code for breast tomosynthesis?

**Comment by AnderBiguri** [comment]
Hi @ghan7213 , with careful tuning of the TIGRE geometry, it already works for breast tomosynthesis. I suggest having a look at the demos, there is one specially for digital breast tomosynthesis (DBT).

**Comment by AnderBiguri** [comment]
I will close this issue @ghan7213 , but do not hesitate to reopen or email me if you have questions.
