### ISSUE TITLE
Inaccurate description of addCTNoise function parameters 

### ISSUE THREAD

**Issue by leekunpeng** [CERN/TIGRE#321]
## Expected Behavior
![image](https://user-images.githubusercontent.com/61607176/130541395-74db6d44-a27c-42e5-9c12-6be4a1d41573.png)

The two parameters for adding Gaussian noise are the mean and the standard deviation, but in fact the variance is used in the program.
## Actual Behavior
![image](https://user-images.githubusercontent.com/61607176/130541665-948f90b3-2b9e-4230-8ffb-a292be1d5f40.png)

In fact, the standard deviation is not used, and the sigma parameter refers to the variance.
I think you should modify this description。

## Specifications 

  - MATLAB version:  MATLAB202b
  - OS:  Winodws10
  - CUDA version: CUDA10.2

**Comment by tsadakane** [comment]
Indeed.
As described in https://www.mathworks.com/help/images/ref/imnoise.html 
the `imnoise` function interprets the argument at the position as the variance of the output.

If the Image Processing Toolbox is not installed and the Statitics Toolbox is installed, 
https://github.com/CERN/TIGRE/blob/7e761f505e3c156a816d77fcc8570333a8ed528d/MATLAB/Utilities/addCTnoise.m#L102
is used. Is this line acceptable for you?

I have made a PR #320, which provides the random number generator that uses GPU (cuda).
Your comment can be another reason to change the default implementation to cuda. Thank you!
