### ISSUE TITLE
Add optional parameter to algorithms: Image to compute quality measurements against, per iteration

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#332]
As the title says, this would be a parameter that allows the quality measurement parameters to be computed against a known image, rather than change per iteration. 

Something like:

`[img, qual] = SIRT(proj,geo,angles, 'QualMeas','RMSE','ground_truth',my_image)`

**Comment by wahaj** [comment]
Can I get on this ? Would help me to wrap my head around the project. It seems that the init options argument  supports providing an image, do you want to seperate that from `opt` and make it a separate argument ?
`%   'Init':        Describes diferent initialization techniques.
%                  'none'     : Initializes the image to zeros (default)
%                  'FDK'      : intializes image to FDK reconstrucition
%                  'multigrid': Initializes image by solving the problem in
%                               small scale and increasing it when relative
%                               convergence is reached.
%                  'image'    : Initialization using a user specified
%                               image. Not recomended unless you really
%                               know what you are doing.`

**Comment by AnderBiguri** [comment]
Hi @wahaj , absolutely, all yours ;)

I think the best way would be to have a separate argument. Mostly because it should be possible to have both, an image to initialize your algorithm with and an image to compare your results to, and those images be different.

I suggest calling this new argument `'ground_truth'`, or something like that. Perhaps we could also throw an warning if the user has not chosen to call the function with several outputs (`nargout`), so they know the input is being ignored.

**Comment by AnderBiguri** [comment]
This already exists in MATLAB, only needed in python now. Closing as duplicate of #410
