### ISSUE TITLE
Ax.exp, Atb.exe , minTV.exp, tvDenoise.exp

### ISSUE THREAD

**Issue by CarlaRomano** [CERN/TIGRE#34]
Hello everyone,
when I try to run Compile it gives me this 
Building with 'NVIDIA CUDA Compiler'.
Could Not Find H:\CERN-TIGRE-7e349d7\Mex_files\win64\Atb.exp
and the same for the other in the header. 
Could anyone help me?
Plus I have 3142 projections and images of 2000x2000, so matrix with 2000x2000x3142. Is it normal that for FDK it goes out of memory (128Gb RAM)?

**Comment by AnderBiguri** [comment]
Hi @CarlaRomano ,
Do not worry about the .exp warnings, they are a MATLAB thing that has no influence whatsoever in the correct compilation of the code.

About the memory... Unfortunately TIGRE has no multiGPU support yet. This means that the maximum image that you can reconstruct will need to fit inside your GPU RAM (not CPU RAM). 

To compute if something will fit in your GPU you can use the following formula:

Memory=nVoxelX*nVoxelY*nVoxelZ*4+nPixelU*NPixelV*nagles*4

This number has to be smaller than the RAM in your GPU. Note that as for today, the biggest RAM in an NVIDIA GPU is 12Gb.

Hopefully we would be able to add multi GPU support anytime soon.

Best
Ander Biguri

**Comment by CarlaRomano** [comment]
Thank you. At the end of the formula will I have a number in kb?

**Comment by AnderBiguri** [comment]
@CarlaRomano  At the end of the formula you have the number in bytes.

Lets put an example: 512x512 detector, 360 angles, a 512x512x512 image.

That gives 914358272 bytes or 892928Kb or 872 Mb 

Ander

**Comment by CarlaRomano** [comment]
Thank you!
