### ISSUE TITLE
Error in running Compile.m

### ISSUE THREAD

**Issue by blauyang** [CERN/TIGRE#343]
## Expected Behavior
By opening MATLAB on myTIGREpath/MATLAB, execute Compile.m

## Actual Behavior
Run the Compile.m with the following error. I have renamed mex_CUDA_win64_MVS2015.xml to mex_CUDA_win64.xml.  But I don't know why it still shows that the xml file cannot be found. I did all steps 1-6 of the installation tutorial and there were no errors.

In addition, although I downloaded cuda9.2 and ran nvcc -V in the system cmd, the cuda version is also 9.2, but when I execute gpuDevice in the matlab command window, it shows tooltik Version: 8.0 This is also a very confusing place for me, I do not know if I am really running the 9.2 version of cuda I even reset my computer system to install only 9.2 cuda, but it still shows 8.0 in matlab.
![problem](https://user-images.githubusercontent.com/87274625/141468573-7960c780-3202-4497-a933-0caeaa33030a.PNG)
![problem2](https://user-images.githubusercontent.com/87274625/141468685-f885b90d-4f46-45ce-a329-e39c8fefe088.PNG)

## Code to reproduce the problem (If applicable)

mex_CUDA_win64.xml not found. You may need to rename the existing files depending on your MVS version
```

```

## Specifications 

  -MATLAB version: R2017a
  - OS: Windows 10
  - CUDA version: 9.2 
  - VS 2015

**Comment by AnderBiguri** [comment]
When you run Compile.m, you need MATLAB to be in the TIGRE folder, i.e. in `D:\Tigre\TIGRE-master\MATLAB`. Are you running the code from there, or are you just adding all to path, then compiling from somewhere else? Looking at your MATLAB folders there, it looks like you are compiling from somewhere else.

**Comment by blauyang** [comment]
Hi @AnderBiguri ，
Wow, it worked, I should have come to ask you earlier. I also spent a day resetting my computer as well as installing various software. Thank you so much!
Also can you answer my other question, I'm not sure if I'm using CUDA 9.2 or not, because the tigre toolkit requires cuda 9.2 or higher, and now my tigre is running successfully, does that mean anything?

**Comment by AnderBiguri** [comment]
You must be using CUDA 9.2 (newer also works, that is the minimum requirement) . Try demo 3, if that works, then you are good to go ;)

**Comment by blauyang** [comment]
it works! thanks again!
