### ISSUE TITLE
  Flip after projection loading and  ring artefacts

### ISSUE THREAD

**Issue by blauyang** [CERN/TIGRE#345]
## Expected Behavior
I would like to keep the projection image in its original coordinates once it has been loaded into the toolkit

## Actual Behavior

The top figure shows the single original projection and the bottom figure shows the projection obtained by using plotProj().

![original-projections](https://user-images.githubusercontent.com/87274625/141835593-5bb6872f-55f7-4271-b6a3-fe7960af1b62.PNG)
![cera_projections](https://user-images.githubusercontent.com/87274625/141835320-18ef3eea-e863-419f-826d-afc8f2db9d1f.PNG)

When I imported the projection through the loop, the projection was reversed up and down, including the reconstruction results. The image on the left is the result I got via tigre. The picture on the right is the result obtained by commercial CT.

![tigre-cera-Y](https://user-images.githubusercontent.com/87274625/141833494-0a48da51-d013-4d08-aa86-36b54103f486.PNG)

In addition ring artefacts appear in the reconstruction results as shown below.

![Tigre_Z_slice128](https://user-images.githubusercontent.com/87274625/141835968-c0d5eac3-b5a9-4bdf-a4bf-5cd5c5bea805.PNG)

## Specifications 

  - MATLAB version: R2017a
  - OS: win10 x64
  - CUDA version: 9.2

Thank you in advance!

**Comment by AnderBiguri** [comment]
This is unrelated to TIGRE, and related to how images are visualized in MATLAB.

Your first image is the same as TIGRE one, except that in matlab, if you do `imshow`, the 0,0 point is in the top left corner, not bottom right. The only difference between the two is visualization. 
It also may be a difference between what your compercial CT considers the positive Z axis and what TIGRE considers the positive Z axis, there is no reason (and in reality, it almost never happens) to have a consensus in what is each thing. 

So.... why don't you just flip it? Matlab provides functions such as `flip()` to simple flip any axis that you want.

**Comment by AnderBiguri** [comment]
About the ring artifacts: can you show a higher resolution image? It all looks like expected artifacts, TIGRE has no function to reduce ring artifacts (in fact this is often done in acquisition rather than post-processing), so if there are artifacts its likely they are in the data.

**Comment by blauyang** [comment]
Hi @AnderBiguri, 
Thank you for your quick and detailed answer. I will go and flip them.

About the ring artifacts, For the same projection I also used the Astra toolkit to reconstruct it, but no ring artifacts appeared. 

![Astra_XYZ](https://user-images.githubusercontent.com/87274625/141842785-df30eb02-c5b7-4b5d-9818-46ca172ab892.PNG)


By high resolution image do you mean the original projection image, if so ,the image below. The image above is the one I opened using matlab, the one below is opened using imageJ.

![original-projections-1](https://user-images.githubusercontent.com/87274625/141842550-11cb770c-3a30-416d-b613-63bbbd0838de.PNG)
![original-projections-imageJ](https://user-images.githubusercontent.com/87274625/141842580-d6cf39d0-3c9a-435e-b0ce-3f650dbbc3fd.PNG)

**Comment by AnderBiguri** [comment]
No, I meant a high resolution image of the result with the artifacts. The images are too small and I can't honestly see what you mean, or any difference.

**Comment by blauyang** [comment]
Hallo @AnderBiguri , 
By ring artefact I mean this shiny circle that surrounds the outside of the workpiece. 

![Tigre_Z_slice128-1](https://user-images.githubusercontent.com/87274625/141843895-3a20215d-5f6b-4308-82b7-a3cd85ab7386.PNG)

**Comment by AnderBiguri** [comment]
That is normal in FDK. Most people just crop it with a circular mask. 

Note: ring artifacts are a very specific artifact type in CT, that look like this:

![image](https://user-images.githubusercontent.com/11854388/141844820-0ac4884b-fb6d-432a-8896-306033404510.png)

This is why I could not see them.

**Comment by blauyang** [comment]
Sorry for my incorrect use of technical words. I got it. Thank you again for your answer.

**Comment by AnderBiguri** [comment]
No worries :) I was just clarifying for the future! we all learn at some point!
