### ISSUE TITLE
Add MVS 2022 Support

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#348]
related #347

**Comment by tsadakane** [comment]
Hi,

CUDA 11.6 released. It supports VS2022.
* https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
   * The cudaDeviceSynchronize() function used for on-device fork/join parallelism is deprecated...
   * CUDA 11.6 officially supports the latest VS2022 as host compiler.

I tried...

As for python, the package was build successfully and `example.py` seemed to work.

As for Matlab, `>> mex -setup -v` could not find VS2022; 2021b does not support VS2022 yet.
* https://jp.mathworks.com/support/requirements/supported-compilers.html

**Comment by AnderBiguri** [comment]
Fantastik @tsadakane . This would need indeed a change in MATLAB. Even if mex seems not to support it, a correct xml file may make it work.

**Comment by tsadakane** [comment]
Modifying the XML file to specify 2022 as the c++ compiler used by nvcc was straight forward. ([15.0, 16.0) => [16.0, 17.0) ).

But, there is another issue.
It seems that mex searches for `cl` (vc compiler) if the file list only includes `.cpp` files. If vs2019 is installed too, no problem. but if only vs2022 was installed, it fails. Adding a dummy `.cu` file solves this problem:
```
        mex -largeArrayDims ./Utilities/IO/VarianCBCT/mexReadXim.cpp ../Common/CUDA/gpuUtils.cu -outdir ./Mex_files/win64
```
Of course, `gpuUtils.cu` is unnecessary for `mexReadXim.cpp`. Ugly solution.

What do you think?

**Comment by AnderBiguri** [comment]
I'd say go for it. Its ugly, but so is the way nvcc and mex search for compilers, so I'd say if it works, its fine!

**Comment by AnderBiguri** [comment]
Fantastic! Good to know!
