### ISSUE TITLE
Error using Atb

### ISSUE THREAD

**Issue by CarlaRomano** [CERN/TIGRE#35]
Error using Atb
invalid argument

Error in OS_SART (line 145)
                res=res+lambda*
                bsxfun(@times,1./sum(V(:,:,orig_index{jj}),3),Atb(W(:,:,orig_index{jj}).*(proj(:,:,orig_index{jj})-Ax(res,geo,alphablocks{jj})),geo,alphablocks{jj})); 

Do you know why?

**Comment by AnderBiguri** [comment]
Hi @CarlaRomano,
That is strange, my code does not throw any error. Can you share more information? What is your geometry definition like? Did you compile it right?

Ander
