### ISSUE TITLE
minimizeTV outputs NaN images unexpectedly.

### ISSUE THREAD

**Issue by ilanzhang** [CERN/TIGRE#36]
Hi!
When I used my experiment date to reconstruct the image some days ago, sometimes the voxel value of reconstructions were all NaN and sometimes not, and recently, the results are all NaN when using the GPU code
`f=minimizeTV(f0,dtvg,ng);`, 
but the results will be correct when using the matlab code:
`df=gradientTVnorm(f,'forward');df=df./im3Dnorm(df,'L2');f=f-dtvg.*df;`. 
could you tell me why? It will cost much more time when using the matlab code.
Thank you!

**Comment by AnderBiguri** [comment]
Hi @ilanzhang,
This is very interesting. One of my colleagues use to have this problem very sporadically and I have never been able to reproduce it. One day she stopped having the error and we more or less forgot about it.
Unfortunately my answer is:  I have absolutely no idea. Both codes are exactly the same, and should (and would) give the exact numerical solution given the same values. This has 100% of the times worked in my PC and I do not know why it would not in some (almost none!) PCs. I will try to go back to this and dig a bit more what could be.

I would like to ask you to try a small thing in your PC:
 What image sizes are you trying?  
If you reduce the image size (say, by two), this does effect still happens? Is it constant among different data/image sizes?

Best
Ander

**Comment by ilanzhang** [comment]
Hi, @AnderBiguri 
Thank you for the answer. I'll describe the thing about NaN in detail. At first code came out the problem when I tried to get a better reconstruction by changing the `alpha` and `ng` in OSC-TV, and for some `alpha` or(and) `ng`, the NaN came out while the other didn't. And now, I try to decrease the number of ordered subsets when the iterations goes on, it seems the NaN then just show out, when sometimes the iterations will be just one, and sometimes will be dozens. and now the NaN come out just after the `minimizeTV`.
The size of projections is 482*482*125, reconstruction size is 241*241*241. I'll try to reduce the reconstruction size to see what happened. thank you!

**Comment by AnderBiguri** [comment]
Hi @ilanzhang  
Thanks for the comments. 
If you find specific cases on where NaNs always appear (specific parameters,geometry, ...) please let me know so I can try to study those cases and pinpoint the problem. It is a bit frustrating because I can not reproduce in any means the behavior but I know it exists.  It definitely always is caused by `minimizeTV`, but I am still baffled as I don't know how.

**Comment by ilanzhang** [comment]
Sorry I concentrate other problems and I forget I've already been raise the question. 
the geometry:
`%% Define Geometry
geo.DSD = 960.45;                                               % Distance Source Detector      (mm)
geo.DSO = 628.88;                                               % Distance Source Origin        (mm)
geo.ratio=geo.DSO/geo.DSD;
% Detector parameters
detment=0.1067; detsize=480;
geo.dDetector=[detment;detment];            				   % size of each pixel            (mm)
geo.nDetector=[detsize;detsize];                            		% number of pixels              (px)
geo.sDetector=geo.nDetector.*geo.dDetector;     % total size of the detector         (mm)
% Image parameters
geo.dVoxel=2*[detment;detment;detment]*geo.ratio;    % size of each voxel            (mm)
geo.nVoxel=[detsize;detsize;100]./2;                        % number of voxels              (vx)
geo.sVoxel=geo.nVoxel.*geo.dVoxel;                    % total size of the image       (mm)
% Offsets
geo.offOrigin =[0;0;0];                                         % Offset of image from origin   (mm)              
geo.offDetector=[0; 0];                                        % Offset of Detector            (mm)
% Auxiliary 
geo.accuracy=0.5;                                               % Accuracy of FWD proj    
`
At first the angle 0:1:180, and now, 0:4.4444:360.

**Comment by AnderBiguri** [comment]
@ilanzhang  No worries. Can you also please tell me the GPU you are running this on, and how much RAM does it have?

**Comment by ilanzhang** [comment]
GTX-660 and the RAM is 8GB

**Comment by ilanzhang** [comment]
@AnderBiguri  Hello, I found recently when the NaN image would be produced. It is the time when I do other things using computer and the reconstructions at thes same time. for example, do the reconstruction and use virtual machine, or do the reconstruction and do my ppt. When the NaN images are produced, What I should do is restart my computer and do the reconstruction but don't do any other things. Then the NaN images won't be shown.

**Comment by AnderBiguri** [comment]
@ilanzhang  Strange behavior. I have no idea what can cause this. I am still trying to reproduce this in my PC, but can not. I will try it in a slower specs PC, with a similar GPU as yours.
Ander

**Comment by ilanzhang** [comment]
@AnderBiguri Thank you!

**Comment by AnderBiguri** [comment]
This is due to memory problems. If the memory is full, the algorithm will output NaN.
I need to figure out why sometimes the memory gets full, as it should be emptied every call. I also need to investigate how to throw an error instead of getting NaNs.

**Comment by AnderBiguri** [comment]
This is caused by not enough memory on the GPU.
