### ISSUE TITLE
SDK 7.1 May not be compatible

### ISSUE THREAD

**Issue by emrtpl** [CERN/TIGRE#37]
I am using matlab r2016a, cuda 8 and sdk 7.1. When i tried to run compile.m file, i got message below:

>> Compile
MEX configured to use 'Microsoft Windows SDK 7.1 (C)' for C language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
	 variables with more than 2^32-1 elements. In the near future
	 you will be required to update your code to utilize the
	 new API. You can find more information about this at:
	 http://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN
Compiling TIGRE source...
This may take a couple of minutes....
Error using mex
No supported compiler or SDK was found. For options, visit http://www.mathworks.com/support/compilers/R2016a/win64.html.

Error in Compile (line 37)
        mex -largeArrayDims ./Source/Ax.cpp ./Source/ray_interpolated_projection.cu ./Source/Siddon_projection.cu
        ./Source/ray_interpolated_projection_parallel.cu ./Source/Siddon_projection_parallel.cu -outdir ./Mex_files/win64
output of mex-setup

>> mex -setup
MEX configured to use 'Microsoft Windows SDK 7.1 (C)' for C language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
	 variables with more than 2^32-1 elements. In the near future
	 you will be required to update your code to utilize the
	 new API. You can find more information about this at:
	 http://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN
and details of gpudevice

>> gpuDevice()

ans = 

  CUDADevice with properties:

                      Name: 'Quadro K5000'
                     Index: 1
         ComputeCapability: '3.0'
            SupportsDouble: 1
             DriverVersion: 8
            ToolkitVersion: 7.5000
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 4.2950e+09
           AvailableMemory: 4.1018e+09
       MultiprocessorCount: 8
              ClockRateKHz: 705500
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
            DeviceSelected: 1

**Comment by AnderBiguri** [comment]
Hi @emrtpl ,

If when you run `mex -setup` the SDK is properly found, I assume this happens because NVCC is not found. Where is it installed in your PC? Make sure that [mex_CUDA_win64.xml](https://github.com/CERN/TIGRE/blob/master/mex_CUDA_win64.xml) is properly set up with your information.  The first lines are relevant, as long as line 125. 

Ander

**Comment by AnderBiguri** [comment]
@emrtpl  also try to run `mex -setup C++` to make sure its C++ not C selected

**Comment by emrtpl** [comment]
Hi Mr. Biguri

Thank you for prompt reply, I checked the path of nvcc, it is installed in the default path. Also I tried your second suggestion too, the result is unfortunately same with previous one. Also to be sure, i tried to use another mex file and it worked fine with same setup. So when i got the error, i assumed that it is related with my program installation paths but apparently i am missing something.

**Comment by AnderBiguri** [comment]
@emrtpl  Do you have distributed computing toolbox? If so, please try to compile some of the examples there:

http://uk.mathworks.com/help/distcomp/run-mex-functions-containing-cuda-code.html

**Comment by emrtpl** [comment]
I have parallel computing toolbox. i tried the first one and the problem is exactly same with compile.m.

```
>> mexcuda mexGPUExample.cu
Warning: The selected C++ compiler is not supported for CUDA compilation. Searching for a supported compiler. 
> In mexcuda (line 89) 
Error using mex
No supported compiler or SDK was found. For options, visit http://www.mathworks.com/support/compilers/R2016a/win64.html.

Error in mexcuda (line 157)
    [varargout{1:nargout}] = mex(mexArguments{:});
 
>> x = ones(4,4,'gpuArray');
y = mexGPUExample(x)
Undefined function or variable 'mexGPUExample'.
```

**Comment by AnderBiguri** [comment]
@emrtpl  try to compile it with `mex -largeArraydims mexGPUExample.cu`

**Comment by emrtpl** [comment]
@AnderBiguri thank you for your assistance. I checked an another mex file to avoid take your time for something unrelated before asking you, but now I am thinking that way too, it is completely unrelated with tigre toolbox. Anyway, i hope i find a way to use this toolbox because the results in your paper was very promising.  I am really sorry to take your time.

**Comment by AnderBiguri** [comment]
@emrtpl  No worries, I will help with whatever I can! however I do not know what can be the error in your set up. it seems related do the CUDA compiler, not the C++ compiler, so I'd start looking there.

**Comment by AnderBiguri** [comment]
@emrtpl  Any news about this?

**Comment by emrtpl** [comment]
@AnderBiguri Thank you for asking, I spent my all day with trying different suggestions on Matlab forums and checking my computer configuration, but unfortunately I couldn't find a way to compile anything with CUDA, it simply doesn't work with Matlab. I checked every software and and driver and everything is just perfectly fine besides of compiler. So eventually I gave up and focused back to my own algorithm. I also have some problem in my own algorithm too, especially in reconstruction. Actually my FDK algorithm is very similar to Tigre, but after back projection, the only thing I see is an empty black circle. When I have some time I will focus on compiler problem again, and if I find a way I will let you know.

**Comment by AnderBiguri** [comment]
I have opened a question in Mathworks webpage.

https://uk.mathworks.com/matlabcentral/answers/327688-mex-files-cuda-compilers-and-all-that

**Comment by AnderBiguri** [comment]
@emrtpl Try the following. Open MATLAB and type:

`setenv('CUDA_PATH','C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0');`

Change the path to your corresponding CUDA path.

**Comment by emrtpl** [comment]
@AnderBiguri I tried but the result is unfortunately same.

**Comment by AnderBiguri** [comment]
@emrtpl  What do you get if you do `getenv('CUDA_PATH');`?
Unfortunately the only computer with CUDA that I have access right now is one without admin rights... 
My hands are tied, but I promise to have a further look at this as soon as I can.

Apologize for all the inconvenience! TIGRE is supposed to be easy to install, and it looks its is not being very friendly to you.

**Comment by emrtpl** [comment]
@AnderBiguri Sorry for late response, I got the same path when i did. Anyway, really thanks for your assistance. It is very specific problem and furthermore it is certainly not mainly related with tigre.

**Comment by AnderBiguri** [comment]
@emrtpl  Still not 100% sure that SDK 7.1 works with CUDA, I am going to test that. Thanks for reporting this, I will try to test it myself. 

Ander

**Comment by AnderBiguri** [comment]
@emrtpl  I have confirmation from Mathworks: Visual Studio is the only CUDA compatible compiler. I am closing this issue, but opening a new one to try to find a workaround.
