### ISSUE TITLE
Bug in detector offset geometry reconstruction in FDK

### ISSUE THREAD

**Issue by yidu-bjcancer** [CERN/TIGRE#382]
## Expected Behavior
Bug in the latest version of FDK for detector offset geometry reconstruction, only in certain geometry (maybe rotation direction? unclear yet)

## Actual Behavior
It seems the detector offset weighting is incorrect. 

## Code to reproduce the problem (If applicable)
I think someone modified the FDK.m function, particularly the weighting session, and there is a bug there. When I replaced the latest FDK.m with an old version, the bug disappeared. 

## Specifications 

  - MATLAB version: R2022a
  - OS: Win10
  - CUDA version: 11.5

Report first. I can fix this myself when I have time.

**Comment by AnderBiguri** [comment]
There has been ineed some changes in the weigting, but tests showed better recon with the changes. If you have troubles fixing it, can you post your geometry, so I can compare?

**Comment by yidu-bjcancer** [comment]
> There has been ineed some changes in the weigting, but tests showed better recon with the changes. If you have troubles fixing it, can you post your geometry, so I can compare?

This is the geometry to trigger the bug.
[geo.zip](https://github.com/CERN/TIGRE/files/9033116/geo.zip)

**Comment by shaohua-zhi** [comment]
@AnderBiguri @yidu-bjcancer Hi, I also met a problem with the same Varian half-fan geometry. after adding wang pre-weighting(not sure which version), the reconstructed image has a circle dark drop at the center. could you help me fix it?
![image](https://github.com/CERN/TIGRE/assets/54792733/5852a1bd-0558-4816-805d-e680311844e9)

**Comment by AnderBiguri** [comment]
Hi @shaohua-zhi , thanks for the message. 

Can you verify which exact version of TIGRE are you using? In the latest release (2.4) a big like this existed, but in the current latests commit in master it does not. 

What you see may be a different bug, but I want to first verify that, and if it is, I would need to have a way to reproduce it, so I can fix it. Can you share (privately if you want) the data, if you are using the latest version of TIGRE?

**Comment by AnderBiguri** [comment]
@shaohua-zhi  I have just released TIGRE 2.5, check if the error is still there.

**Comment by shaohua-zhi** [comment]
@AnderBiguri Thanks a lot! It works now. may I ask if are there any utilities in TIGRE for ElektaCBCT data?

**Comment by yidu-bjcancer** [comment]
@shaohua-zhi 
Sorry for this late reply. I guess the bug was in the Python version FDK, since the Matlab version works well for me.  

As for TIGRE for Elekta, I am sorry that clinical work piles up and I can not spare enough time to write an ElektaCBCT module (probably until the end of this year). As an alternative, you may use RTK, which provides a specific module for ElektaCBCT (however I don't have any user experience with it).

**Comment by AnderBiguri** [comment]
I think I fixed the offset detector in python. Let me know if this is still aproblem
