### ISSUE TITLE
cpu reconstruction

### ISSUE THREAD

**Issue by shaghayegh1376** [CERN/TIGRE#401]
hello is there any way(code) to implement these algorithm on cpu for comparing the result with gpu ?
because these demos are gpu based

**Comment by AnderBiguri** [comment]
Hi @shaghayegh1376 there is a "way", but TIGRE does not have it. You'd need to rewrite the forward and backprojection operators, or substitute it for some other from another library. Careful when doing this, in 3D this gets very, _very_, **very** slow quite quickly. 

This is why TIGRE only supports GPUs.
