### ISSUE TITLE
Image Quality Issues

### ISSUE THREAD

**Issue by Peacepppp** [CERN/TIGRE#412]
Hello, I am trying to use the haed digital model that comes with the tigre toolbox to do some algorithm tests on the python version, but I find that the image quality of the head digital model in python is far inferior to that of matlab. What is the reason?

<img width="480" alt="3739ed53bd0b55be7cc6ec7b30dca7c" src="https://user-images.githubusercontent.com/71495625/203057570-34181a04-6699-4088-bfd8-8ce8219dfa7a.png">
<img width="464" alt="d726dc4d81f736399f9c08ed8b14a4a" src="https://user-images.githubusercontent.com/71495625/203058237-e6fb2ece-8c61-4e35-9ea0-eabde12af224.png">

**Comment by AnderBiguri** [comment]
hi @Peacepppp: it just seems that you are loading it with a different resolution. The code that loads it up reads the same data, and the interpolates to the resolution you ask. Perhaps the defaults are not the same, need to double check that....

**Comment by Peacepppp** [comment]
Thanks for the reminder, indeed the defaults are different. Now the doubt has been resolved!
