### ISSUE TITLE
 nvcc(11.8) cannot find a supported version of Microsoft Visual Studio (2015).Only the versions between 2017 and 2019 (inclusive) are supported!

### ISSUE THREAD

**Issue by slxaso** [CERN/TIGRE#414]
## Expected Behavior
Successful running of Compile.m

## Actual Behavior
When running Compile.m, giving following errors:
Error using mex
nvcc warning : The 'compute_35', 'compute_37', 'sm_35', and 'sm_37' architectures are deprecated, and may be removed in a future release (Use
-Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions between 2017 and 2019 (inclusive) are supported! The nvcc flag
'-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run
time execution. Use at your own risk.

Error in Compile (line 65)
        mex -largeArrayDims ./Utilities/cuda_interface/Ax_mex.cpp ../Common/CUDA/ray_interpolated_projection.cu ../Common/CUDA/Siddon_projection.cu ../Common/CUDA/ray_interpolated_projection_parallel.cu ../Common/CUDA/Siddon_projection_parallel.cu ../Common/CUDA/GpuIds.cpp -outdir ./Mex_files/win64

## Code to reproduce the problem (If applicable)

Tried to add '-allow-unsupported-compiler'  to mex_CUDA_win64.xml line 36, but it overwrite anyway.
Anyway to walk around?

## Specifications 

  - MATLAB version:2022a
  - OS:Windows 11
  - CUDA version:11.8

**Comment by AnderBiguri** [comment]
Hi @slxaso,
This seems like a new cuda 11.8 issue aparently.
I don't think I can do anything about this, you will need to just install one of those supported compilers, MSV2017 OR MSV2019
