### ISSUE TITLE
Image size in demos

### ISSUE THREAD

**Issue by shaghayegh1376** [CERN/TIGRE#425]
hi authors, in defining default geometry in TIGRE  the image size is 256.256 but why in implementing algorithms we use head phantom with 64.64 image size?

**Comment by AnderBiguri** [comment]
Hi @shaghayegh1376 

The size you want to use is completely arbitrary, you can use whichever you want. In the demos, sometimes we have small images just so they run fast on your computer, but feel free to change the size as much as you wish.

**Comment by shaghayegh1376** [comment]
I appreciate your guidance
Another question is that compared to the results of other articles using GPU, it seems that the execution time using this toolbox is a little longer. what is the reason

**Comment by AnderBiguri** [comment]
@shaghayegh1376 What do you mean "other articles"? The execution time will totally depend on your GPU, of course.

**Comment by shaghayegh1376** [comment]
I mean the results of articles about CBCT reconstruction algorithms using GPU.
i got your point so it depends on system hardware . i am using NVIDIA GeForce RTX 3050

**Comment by AnderBiguri** [comment]
@shaghayegh1376 the  RTX XX50 is the slowest GPU of any generation XX of NVIDIA GPUs, so its reasonable that you get slower performance.

**Comment by shaghayegh1376** [comment]
how we can measure image quality for FDK?
because  with "Measure_Quality.m" function we can measure image quality in each iteration
how we can measure image quality compare with ground truth

**Comment by AnderBiguri** [comment]
The quality measurement functions can be used given a ground truth. You can
find them inside the utilities folder, in their own su folder. They just
compute the parameter between the two inputs.
