### ISSUE TITLE
unstability for minimizeTV

### ISSUE THREAD

**Issue by ilanzhang** [CERN/TIGRE#43]
Hello again:
    Sometimes reconstruction will end with NaN(and sometiomes not) after minimizeTV for OSCTV. Especially when my virtual machine works. Restart the matlab may not solve the problem but restart the computer does. Recently I've been come across such condition many times, do you know why and how to solve it permanently?
    Thank you!

**Comment by AnderBiguri** [comment]
@ilanzhang Insetead of opening another issue, lets go back to Issue #36
