### ISSUE TITLE
shepp_logan_3d ignores numpy arrays

### ISSUE THREAD

**Issue by amaarquadri** [CERN/TIGRE#432]
## Expected Behavior
```
sl3d.shepp_logan_3d(np.array([10, 10, 10])).shape == (10, 10, 10)
```

## Actual Behavior
```
sl3d.shepp_logan_3d(np.array([10, 10, 10])).shape == (128, 128, 128)
```

## Specifications 
  - MATLAB/python version: 3.9.15
  - OS: Ubuntu 22.04.1 LTS

## Fix
Change `np.array` to `np.ndarray` in [this line of code](https://github.com/CERN/TIGRE/blob/master/Python/tigre/utilities/sl3d.py#L146)

**Comment by AnderBiguri** [comment]
Thanks for pointing this out @amaarquadri .

I can try to find some time soon to fix it, but do please feel free to make a PR to fix it yourself, if you want :)
