### ISSUE TITLE
Use the projection residual to get the value that the current reconstructed image should update

### ISSUE THREAD

**Issue by Kwong-Yam-Lie** [CERN/TIGRE#437]
Hello,  

I'm implementing an algorithm .   

I want to "Use the projection residual to get the value that the current reconstructed image should update" , but I falied. For example, with SART-based algs. I find that all algorithms return non-negative results .  

So when I want to get the value that the current reconstructed image should update, I got the wrong result.  
```Python
# Load thorax phatom data
head = sample_loader.load_head_phantom(geo.nVoxel)
# generate projections
projections = tigre.Ax(head, geo, angles)
# SART
imgSART = algs.sart(-projections, geo, angles, niter = 10) 
## Just a test, the 'projections' is  negative but 'imgSART' is filled with zeros.  
``` 
Excuse me how can I realize my requirements by calling this software?  

Does the software have this function?
I need your help, **thanks!**

**Comment by AnderBiguri** [comment]
I believe `imgSART = algs.sart(-projections, geo, angles, niter = 10, nonneg= False)` should remove the non-negativity constraint, if that is what you are looking for. 

But again, getting `img_residual` is just a line that uses the backprojection and forward projection. 
You can find the exact line here: 

https://github.com/CERN/TIGRE/blob/8df632662228d1b1c52afd95c90d0f7a9f8dc4b3/Python/tigre/algorithms/iterative_recon_alg.py#L385-L397

or you can have a simple non-weighted one by doing: 

```
img_res=tigre.Atb(projections-tigre.Ax(x,geo,angles),geo,angles)
```

**Comment by Kwong-Yam-Lie** [comment]
With your suggestion, my problem has been solved！ 😄
