### ISSUE TITLE
Error in Compile

### ISSUE THREAD

**Issue by ffbfbfdf** [CERN/TIGRE#442]
Hello, I had the same problem installing the tigre library

Specifications：
OS: Win11
VS: 2019 community
CUDA version: 11.6
Graphics：NVIDIA Geforce rtx3060

Actual Behavior：

false using mex
nvcc warning : The 'compute_35', 'compute_37', 'sm_35', and 'sm_37' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress
warning).
Error in Compile (line 56)
mex -largeArrayDims ./Utilities/cuda_interface/Ax_mex.cpp ../Common/CUDA/ray_interpolated_projection.cu ../Common/CUDA/Siddon_projection.cu ../Common/CUDA/ray_interpolated_projection_parallel.cu ../Common/CUDA/Siddon_projection_parallel.cu ../Common/CUDA/GpuIds.cpp -outdir ./Mex_files/win64

Can you give me some advice?

**Comment by ffbfbfdf** [comment]
step one
 ![image](https://github.com/CERN/TIGRE/assets/95928214/22069f99-58ab-404c-8895-c560e9203b56)
![image](https://github.com/CERN/TIGRE/assets/95928214/24a7353a-f134-48ac-8937-c703b18ba785)
step two
![image](https://github.com/CERN/TIGRE/assets/95928214/6ed93a9f-a277-460f-adc1-e4372a1241fb)

**Comment by ffbfbfdf** [comment]
vs disposition：
![image](https://github.com/CERN/TIGRE/assets/95928214/9b3b4179-7dea-49d8-90fa-c8adbf56f6d9)
![image](https://github.com/CERN/TIGRE/assets/95928214/83f516bd-bb2b-4c58-b2e6-191f27f918ef)

**Comment by AnderBiguri** [comment]
Hi!

Can you show the actual error text that happened during `compile.m` ?

**Comment by ffbfbfdf** [comment]
The problem has been solved，I downgraded the CUDA version from 11.6 to 11.1
