### ISSUE TITLE
Error when compiling the python dist

### ISSUE THREAD

**Issue by jxhno1** [CERN/TIGRE#451]
![image](https://github.com/CERN/TIGRE/assets/37684984/7e915de5-d488-4996-a67e-0bff145449e0)

**Comment by AnderBiguri** [comment]
It seems that you don't have scipy installed? can you confirm?

**Comment by jxhno1** [comment]
I tested and found it required the scipy==1.11.0rc2, so i pip install scipy==1.11.0rc2 and no error about scipy but...
![image](https://github.com/CERN/TIGRE/assets/37684984/b784bd34-813f-4827-973a-65e815dda4f3)

**Comment by AnderBiguri** [comment]
Hi @jxhno1 , I believe this is because of python 3.11. TIGRE per se should work with this recent version, but some of the dependencies are still working on being updated, and thus fail. I suggest changing to python 3.10 and trying again.

**Comment by AnderBiguri** [comment]
This should be fixed.  Closing it due to inactivity, feel free to open it again if you still have issues

**Comment by jxhno1** [comment]
thank you！
