### ISSUE TITLE
complier setting isuue in .xml file

### ISSUE THREAD

**Issue by edimetia3d** [CERN/TIGRE#46]
1. The xml file is using `VS120COMNTOOLS` by default . If VS2013 is not installed , `run complie.m` will report a error ` No supported compiler or SDK was found`
2. I  changed it to  `VS100COMNTOOLS`, it falid with some C3861 complie error when  calling `round()` in  "minTV.cpp", I simply used a `std::round()/<cmath>` replace it, and I passed the complement

**Comment by AnderBiguri** [comment]
Hi @edimetia3d ,
If I understand correctly you managed to get TIGRE running?
For which versions of MATLAB and Visual Studio did you need these changes?
Best
Ander

**Comment by edimetia3d** [comment]
I can complie it now ,but haven't tested the functions yet.
I'm using VS2010 / MATLAB 2014b / CUDA 8.0.  

also, I changed the `arch=compute_52,code=sm_52` to `arch=compute_50,code=sm_50` in the xml file, because nvcc report compute_52 is not supported.  I'm using GTX 760,it might be a reason

**Comment by AnderBiguri** [comment]
@edimetia3d

Thanks for the coments. I may add various versions of the `xml` for different people. I will investigate the `round()` issue and change it if needed. About the CUDA flags, yes, those are GPU-specific, thus not all flags will work in all GPUs. 

If you have any further questions please do not hesitate to open an issue or contact us.
Ander
