### ISSUE TITLE
Confusing about the OSC-TV algorithm

### ISSUE THREAD

**Issue by ilanzhang** [CERN/TIGRE#47]
Hello @AnderBiguri 
I have read your paper about the TIRGE, it's a great job. OSC-TV algorithm you site is "GPU-accelerated regularized iterative reconstruction for few-view cone beam CT" by Philippe etc. I notice that in the article by Philippe, the author mentioned that OSC-TV is a statistics iterative technique because it  serves the poisson log-likelihood of the image estimate µ as the data-correspondence criterion.
However, I don't know how the possion model been participated in the code, could you explain it to me? and also, it seems that the only difference between ASD-POCS algorithm and OSC-TV algorithm is the using of subsets in the OSC-TV, if OSC-TV is a statistics iterative technique, could ASD-POCS also seen as a statistics iteratice technique? Thank you very much!

**Comment by AnderBiguri** [comment]
Hi @ilanzhang,

you are right! 

OSC-TV shoudl be called OSSART_TV, or ASD_OSPOCS, or something like that (not published, AFAIK).

I have no idea how that happened, I think it has to do with me coding a version of ASD-POCS with OS-SART, and then way later someone suggesting that it was the same algorithm an in that paper. I did at the time not read the paper thoroughly enough.

Apologies for my misteake, I will try to be more thorough in the future!
Thanks for bringing this up!
Best
Ander

**Comment by ilanzhang** [comment]
Thank you for answering! @AnderBiguri 

Your job have been helping me a lot, wish you'll do a greater job in the future :)
