### ISSUE TITLE
Python 3.10 install error:file tigre\py.py (for module tigre.py) not found

### ISSUE THREAD

**Issue by TianSong1991** [CERN/TIGRE#471]
## Expected Behavior
When I run `python ./setup.py install`, it returns error:

running install
D:\miniconda3\envs\cil\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
D:\miniconda3\envs\cil\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing pytigre.egg-info\PKG-INFO
writing dependency_links to pytigre.egg-info\dependency_links.txt
writing requirements to pytigre.egg-info\requires.txt
writing top-level names to pytigre.egg-info\top_level.txt
file tigre\py.py (for module tigre.py) not found
reading manifest file 'pytigre.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.ipynb' under directory 'tigre\demos'
warning: no files found matching '*.mat' under directory 'tigre\demos'
adding license  file 'LICENSE'
writing manifest file 'pytigre.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
file tigre\py.py (for module tigre.py) not found
D:\miniconda3\envs\cil\lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'tigre.utilities.cuda_interface' as data is deprecated, please list it in `packages`.
    !!
    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'tigre.utilities.cuda_interface' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'tigre.utilities.cuda_interface' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'tigre.utilities.cuda_interface' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.
!!

  check.warn(importable)
 **file tigre\py.py (for module tigre.py) not found**
running build_ext
building '_Ax' extension
error: unknown file type '.pxd' (from 'tigre/utilities/cuda_interface/_gpuUtils.pxd')

## Actual Behavior
I don't find the py.py in tigre file. How can I fix it. Thank you very much.

## Code to reproduce the problem (If applicable)

```

```

## Specifications 

  - python version: 3.10
  - OS:win10
  - CUDA version:CUDA 11.7

**Comment by AnderBiguri** [comment]
Hum, very strange error. 

Try `python setup.py install`. I know it should be the same, but its just strange that you are getting this error. `py.py` does not exist, is not part of TIGRE, should not be required.

**Comment by AnderBiguri** [comment]
Also, does your environment have `cython` installed?

**Comment by TianSong1991** [comment]
> 
I have already installed cython.
Requirement already satisfied: cython in d:\miniconda3\envs\cil\lib\site-packages (3.0.0)

**Comment by TianSong1991** [comment]
@AnderBiguri  Hi AnderBiguri , I try python setup.py install and it returns the same error. I think it's my machine error. I try to install in other computer.

**Comment by AnderBiguri** [comment]
@TianSong1991 it may be related to #472 , the newest version of cython was indeed released just before your error.

**Comment by TianSong1991** [comment]
Thank you very much for your reply. My problem has been solved. The reason is that the python that executes python setup.py install does not use my virtual environment, but my main environment. I use numpy==1.22.0 and Cython==3.0.0 installed successfully!
