### ISSUE TITLE
Installation fails with default Cython version

### ISSUE THREAD

**Issue by ACTIVgroup** [CERN/TIGRE#472]
## Expected Behavior
Installation of TIGRE v2.5

## Actual Behavior
Installation fails with:
```
Compiling tigre/utilities/cuda_interface/_Ax.pyx because it changed.
[1/1] Cythonizing tigre/utilities/cuda_interface/_Ax.pyx
/home/localadmin/PycharmProjects/scripts_ct/venv/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/localadmin/PycharmProjects/TIGRE/Python/tigre/utilities/cuda_interface/_Ax.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
building '_Ax' extension
error: unknown file type '.pxd' (from 'tigre/utilities/cuda_interface/_gpuUtils.pxd')
```
## Code to reproduce the problem (If applicable)

```
python setup.py develop --no_pinned_memory
```

## Specifications 

  - python version: 3.10.12
  - OS: ubuntu 22.04
  - CUDA version: 12.2

## Solution
 - use Cython 0.29.35 instead of current default version 3.0.0

**Comment by AnderBiguri** [comment]
Thanks for the report!

I'll need to try to figure out how to update the code/installation for cython 3.0.0 then....

**Comment by AnderBiguri** [comment]
@ACTIVgroup this is foxed now! let me know if you have problems
