### ISSUE TITLE
Can add support VS2017 to MATLAB TIGRE?

### ISSUE THREAD

**Issue by fujintao1999** [CERN/TIGRE#477]
Can add support VS2017 to MATLAB TIGRE?

## Specifications 

  - MATLAB version: R2022a $ R2020b
  - OS: Windows
  - CUDA version: 11.3

**Comment by AnderBiguri** [comment]
I think the xml file fore 2015 should work for 2017, but I haven't really tested it in a while, with modern MATLAB versions.

**Comment by AnderBiguri** [comment]
Closing it due to inactivity, feel free to open it again if you have issues
