### ISSUE TITLE
What is the specific version of python's matplotlib module？

### ISSUE THREAD

**Issue by TianSong1991** [CERN/TIGRE#483]
Hello, may I ask which specific version of python's matplotlib you tested specifically, I tested 3.7.2 and 3.5.0, and there will be different errors in your demo file, and the error of 3.7.2 is replaced by 3.5 .0 repair, but other errors will appear in 3.5.0, what is the version of matplotlib tested by the code in your sample demo, thank you.

>   File "D:\miniconda3\envs\tigre\lib\site-packages\pytigre-2.4.0-py3.10-win-amd64.egg\tigre\utilities\visualization\plotproj.py", line 165, in update_frame
    "{}:{}, alpha={:+.3f} pi".format(self.dimlist[2], i, self.angles[i,0] / np.pi)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

I test d17_DetectorRotation.py shows the below error.
My python virtual environment:

> Package           Version
colorama          0.4.6
contourpy         1.1.0
cycler            0.11.0
Cython            3.0.2
fonttools         4.42.1
kiwisolver        1.4.5
matplotlib        3.5.0
numpy             1.25.2
packaging         23.1
Pillow            10.0.0
pip               23.2.1
pyparsing         3.0.9
python-dateutil   2.8.2
pytigre           2.4.0
scipy             1.11.2
setuptools        68.1.2
setuptools-scm    7.1.0
six               1.16.0
tomli             2.0.1
tqdm              4.66.1
typing_extensions 4.7.1
wheel             0.41.2

**Comment by AnderBiguri** [comment]
Hi @TianSong1991 , let me get back to you about the matplotlib version sometime this week. AFAIK any should work, or the most modern ones at least. If they don't, thats a bug and I need to fix it. 

You also mentions bugs in d21. Can you elaborate?

**Comment by TianSong1991** [comment]
![d21](https://github.com/CERN/TIGRE/assets/33627940/85c3723e-0243-40a1-8c41-17235d4b9c37)

Thanks for your replying, I think d21 is test python script and it guides users to run own data. I upload the few mistake.
