### ISSUE TITLE
"RNG.add_noise" function

### ISSUE THREAD

**Issue by Love-Sunshine** [CERN/TIGRE#487]
I have a new question. In the "CTnoise.py" file, I cannot see the specific execution steps of the "RNG.add_noise" function. Can you open-source the code for the "add_noise" function?
Thanks a lot!

**Comment by AnderBiguri** [comment]
Hi @Love-Sunshine , 
here it is!: https://github.com/CERN/TIGRE/blob/master/Common/CUDA/RandomNumberGenerator.cu

In any case, the noise should be a mix of Poisson noise in absorbtion projections +gaussian noise.
