### ISSUE TITLE
Is there limit size in OSSART and SIRT algorithm?

### ISSUE THREAD

**Issue by TianSong1991** [CERN/TIGRE#494]
## Expected Behavior

I can reconstruct it by inputting `512*512*512`, but when I input another set of data `2146*2146*1762`, it crashes in the OSSART and SIRT algorithms. I Debug found that _Ax_ext(img, geox, geox.angles, projection_type, geox.mode, gpuids=gpuids) in Ax.py was abnormally wrong, and no error message was reported.

## Actual Behavior

The only error message reported is Process finished with exit code -1073741819 (0xC0000005). The functions inside cannot be debugged. May I ask if this problem has occurred before? Thank you.

## Code to reproduce the problem (If applicable)

```

```

## Specifications 

  - MATLAB/python version: python
  - OS:win10
  - CUDA version:11.6

**Comment by AnderBiguri** [comment]
TIGRE can handle any size, but your computer may not.
Note that the algorithms will need at least two copies of the images and two of the sinograms. Do you have enough RAM to hold that?

**Comment by TianSong1991** [comment]
> TIGRE can handle any size, but your computer may not. Note that the algorithms will need at least two copies of the images and two of the sinograms. Do you have enough RAM to hold that?

Emmm, my computer has 512G RAM and I don't find the algorithm use the full RAM. Perhaps my computer may not deal with the big size matrix. Thank you very much!
