### ISSUE TITLE
Error when installing tigre2.0

### ISSUE THREAD

**Issue by yuanpengpeng** [CERN/TIGRE#498]
Error when installing tigre2.0

(prior) yuanpeng@DESKTOP-6RR65PH:/mnt/f/TIGRE-2.0/TIGRE-2.0/Python$ python setup.py install --user
running install
/home/yuanpeng/conda/envs/prior/lib/python3.6/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/yuanpeng/conda/envs/prior/lib/python3.6/site-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
creating pytigre.egg-info
writing pytigre.egg-info/PKG-INFO
writing dependency_links to pytigre.egg-info/dependency_links.txt
writing requirements to pytigre.egg-info/requires.txt
writing top-level names to pytigre.egg-info/top_level.txt
writing manifest file 'pytigre.egg-info/SOURCES.txt'
file tigre/py.py (for module tigre.py) not found
reading manifest file 'pytigre.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pytigre.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
file tigre/py.py (for module tigre.py) not found
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/tigre
copying tigre/__init__.py -> build/lib.linux-x86_64-3.6/tigre
error: [Errno 1] Operation not permitted

**Comment by AnderBiguri** [comment]
It seems that the copy operation requires doesn't work because you don't have permissions to copy the file.
