### ISSUE TITLE
TIGRE Installation Issue 

### ISSUE THREAD

**Issue by harshamarupudi56** [CERN/TIGRE#499]
I have installed tigre into my own virtual environment on Linux using Python version 3.9.7 and cuda 11.3. I cloned the repository from Github. When I run import tigre I get the following error. 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f8af9a001cc7> in <module>
----> 1 import tigre

/didsr/fs05/projects01/sriharsha.marupudi/TIGRE/Python/tigre/__init__.py in <module>
     21 from .utilities.geometry import geometry
     22 from .utilities.geometry_default import ConeGeometryDefault as geometry_default
---> 23 from .utilities.Ax import Ax
     24 from .utilities.Atb import Atb
     25 from .utilities.visualization.plotproj import plotproj, plotProj, plotSinogram

/a/projects/sriharsha.marupudi/TIGRE/Python/tigre/utilities/Ax.py in <module>
      2
      3 import numpy as np
----> 4 from _Ax import _Ax_ext
      5
      6 from .gpu import GpuIds

ModuleNotFoundError: No module named '_Ax'

**Comment by AnderBiguri** [comment]
Hi @harshamarupudi56  have you installed TIGRE? You need to compile the CUDA things, so donwloading it is not enough, as explained in the installation instructions. Have you run `pip install .` or if you are not using the current master branch, `python setup.py install` ?

**Comment by AnderBiguri** [comment]
@harshamarupudi56  I will close this issue, do feel free to reopen it if you still have issues.

**Comment by harshamarupudi56** [comment]
I was able to resolve this but had some dependency issues.
