### ISSUE TITLE
Missing malloc in Ax.cpp?

### ISSUE THREAD

**Issue by rffowler** [CERN/TIGRE#5]
In Source/Ax,cpp the outsize variable is set by (line 421):
    mwSize* outsize;
    outsize[0]=geo.nDetecV;
    outsize[1]=geo.nDetecU;
    outsize[2]= nalpha;
I think there should be a malloc statement after the pointer declaration, e.g.:
    outsize = (mwSize*) malloc(3*sizeof(size_t));
Without this the Linux 64 version tends to crash in this function.

**Comment by AnderBiguri** [comment]
Thanks,  will have a look.
Indeed it looks like a malloc is missing,  surprising it works in Windows
as it is.
Thanks for reporting this.
Ander

**Comment by AnderBiguri** [comment]
Hi @rffowler  
I updated it in both Ax.cpp and Atb.cpp.
Please let me know if the problem persists, to close or not this Issue.
Thanks.

**Comment by rffowler** [comment]
Hi Ander
Yes that fixes the issue with Ax.cpp and, I assume, Atb.cpp as the demos I have tried run and look good. There is a problem with the demos for me since my Matlab does not include the license for the statistics and machine learning toolbox, needed for at least "poissrnd", "normrnd" and "prctile" functions. I have made "null" matlab versions of the first two of these which allows the demos to partly run. It would add to portability if these could be avoided, but that is another issue.
Thanks,
Ron

**Comment by AnderBiguri** [comment]
Thanks for telling me this.
Pcetile is only used for "fancier"  plotting so I think I may remove it and
maybe replace it for something similar of my own.

I will look to see if I can replace the functions for decent CT noise
simulation,  but its not a core function for the toolbox.
Glad to hear that this now works on Linux,  Thank you for you help.
Andef
