### ISSUE TITLE
Matlab implementation of FISTA broken - but with simple fix

### ISSUE THREAD

**Issue by EAM-Math** [CERN/TIGRE#502]
## Expected Behavior

Matlab function declaration (the first line) should read
             " function [x_rec,res,qualMeasOut] = FISTA(proj,geo,angles,niter,varargin)"
in order to return the solution given by the FISTA algorithm - in addition to other supplemental and convergence statistics that are generated/requested in the 2nd and 3rd output arguments.

## Actual Behavior

instead the function declaration is
          "function [res,qualMeasOut] = FISTA(proj,geo,angles,niter,varargin)"
which means that the usually desired value is not returned.

## Code to reproduce the problem (If applicable)

```

```

## Specifications 

  - MATLAB/python version:
  - OS:
  - CUDA version:

**Comment by AnderBiguri** [comment]
oops silly bug. I'll fix asap

**Comment by AnderBiguri** [comment]
Hum, no actually, I think its fine but  has misleading names, as `res` here is not the residual, but the result. I will change the names for clarity. 

However indeed, it is missing an output.

**Comment by AnderBiguri** [comment]
I haven't tested it, but I think this is fixed. It was the second output that was missing, not the first, but still important. 
Thanks for the report!
