### ISSUE TITLE
Error Compiling in Matlab

### ISSUE THREAD

**Issue by tamish2** [CERN/TIGRE#503]
## Expected Behavior

Compile code successfully

## Actual Behavior

Renamed options file '/home-local/user1/.matlab/R2023a/mex_CUDA_glnxa64.xml' to '/home-local/user1/.matlab/R2023a/mex_CUDA_glnxa64_backup.xml'.
MEX configured to use 'nvcc' for CUDA language compilation.
Compiling TIGRE source...
This may take a couple of minutes....
Warning: Selected compiler 'nvcc' is not supported and no other supported compiler was found. For options, visit
https://www.mathworks.com/support/compilers. 
> In Compile (line 94) 
Renamed options file '/home-local/user1/.matlab/R2023a/mex_CUDA_glnxa64.xml' to '/home-local/user1/.matlab/R2023a/mex_CUDA_glnxa64_backup.xml'.
Building with 'nvcc'.
/home-local/user1/TIGRE/MATLAB/../Common/CUDA/ray_interpolated_projection_parallel.cu(235): warning #177-D: variable "divangle" was declared but never referenced

/home-local/user1/TIGRE/MATLAB/../Common/CUDA/Siddon_projection_parallel.cu(159): warning #177-D: variable "azm" was declared but never referenced
/home-local/user1/TIGRE/MATLAB/../Common/CUDA/Siddon_projection_parallel.cu(160): warning #177-D: variable "azM" was declared but never referenced
/home-local/user1/TIGRE/MATLAB/../Common/CUDA/Siddon_projection_parallel.cu(317): warning #177-D: variable "divangle" was declared but never referenced

/home-local/user1/TIGRE/MATLAB/../Common/CUDA/GpuIds.cpp: In member function ‘void GpuIds::SetAllGpus(int)’:
/home-local/user1/TIGRE/MATLAB/../Common/CUDA/GpuIds.cpp:44:21: warning: ignoring return value of ‘void* malloc(size_t)’, declared with attribute warn_unused_result [-Wunused-result]
   44 |         (int*)malloc(iTotalDeviceCount*sizeof(int));
      |               ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error using mex
/usr/bin/ld: cannot find -lcudart: No such file or directory
collect2: error: ld returned 1 exit status

Error in Compile (line 94)
    mex('-largeArrayDims', '-I"../Common"',  './Utilities/cuda_interface/Ax_mex.cpp', '../Common/CUDA/ray_interpolated_projection.cu', '../Common/CUDA/Siddon_projection.cu', '../Common/CUDA/ray_interpolated_projection_parallel.cu', '../Common/CUDA/Siddon_projection_parallel.cu', '../Common/CUDA/GpuIds.cpp', '-outdir', outdir, FLAGS)
 

## Code to reproduce the problem (If applicable)

```
Just compiling the code
```

## Specifications 

  - MATLAB version: R2023A
  - OS: 22.04
  - CUDA version: 11.5

**Comment by AnderBiguri** [comment]
Hi @tamish2 . 
I've never seen this particular error, but it seems to say that it can't find `-lcudart`, i.e. the libraru of CUDA run time. This seems to suggest that the compiler does not know where `nvcc` is, in particular the libraries of CUDA. Have you perhaps installed somewhere strange?

**Comment by tamish2** [comment]
These are my paths 
export LD_LIBRARY_PATH=/usr/local/cuda-11.5/lib64:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda-11.5/bin:$PATH
export MW_NVCC_PATH=/usr/local/cuda-11.5/bin/nvcc

**Comment by AnderBiguri** [comment]
@tamish2 not in theory, no. Do you have the symlink for `/usr/loca/cuda` ?

**Comment by AnderBiguri** [comment]
Closing it due to inactivity, feel free to open it again if you still have issues

**Comment by Shi5013** [comment]
Additionally, when I download the Tigre files, where should I place this folder? Can I directly place it in the directory of my code files?

**Comment by Shi5013** [comment]
Thank you for your reply @AnderBiguri ! But  However, it seems like the error is occurring at line 108 of my program, not line 102. Can I directly comment out line 108? Will this affect my usage of the toolbox?

 The first time I ran it, there was an error at line 102, but after modifying the preceding FLAGS, the error no longer occurs at line 102.

 `%% FLAGS
if disable_pinned
    FLAGS=['-DNO_PINNED_MEMORY -std=c++11'];  % add -std=c++11 option
else
    FLAGS=['-DNO_FLAGS -std=c++11'];  % add -std=c++11 option
end
`

**Comment by AnderBiguri** [comment]
@Shi5013 you may be using an older version of TIGRE then. As you can see however, its the same line, i.e. the one that compiles `mexReadXim.cpp`.  Please refer to either the current status of TIGRE, or give me the line, not the number, of older versions. 

Currently line 108 is for the compilation in 32 bit CPUs, and reads:
    `mex( './Utilities/cuda_interface/minTV.cpp', '../Common/CUDA/POCS_TV.cu', '../Common/CUDA/GpuIds.cpp', '../Common/CUDA/gpuUtils.cu', '-outdir', outdir, FLAGS)`
