### ISSUE TITLE
Python: module Ax

### ISSUE THREAD

**Issue by AceCoooool** [CERN/TIGRE#51]
`from _Ax import Ax` can not work: No module  (through conda install )
And the demo in jupyter: 
`Source/_Ax.pyx in init _Ax (tigre/Source/_Ax.cpp:6038)()
__init__.pxd in numpy.import_array (tigre/Source/_Ax.cpp:5379)()
ImportError: numpy.core.multiarray failed to import
`
How can I use the Ax module (in Source file and pyx format), I try `from tiger.Source._Ax import Ax` or `from tiger.Source import Ax` alse failed.

And does this toolbox will be supported to python3+ ?

**Comment by Reuben481** [comment]
This error usually occurs when Conda cant find your CUDA pathway. If you try and update your cuda to the latest module (through either conda update cudatoolkit or through does it work?

Also, did you have cuda installed before you installed tigre?

**Comment by AceCoooool** [comment]
Thank you for your answer. I have installed cuda before I installed tigre. And I can use tensorflow-gpu versions.( it rely on cuda)

**Comment by Reuben481** [comment]
If you download the repo, change to the directory TIGRE/Python/python_build and run  (from the command line) 
>python setup.py install 
Does the install run then?

**Comment by Reuben481** [comment]
Hi, 
So ive reuploaded a new build to anaconda cloud that should work. There is however a little trick to be done, which is common for tensorflow as well but that will be fixed permanently in the near future. 

if, before installing, you set:

`export CUDAHOME=path/to/latest/cuda/`
and then
`LD_LIBRARY_PATH=$CUDAHOME/lib64:$LD_LIBRARY_PATH`

Note: this fix will only affect the paths in your presently open terminal so it will not mess with your other installations. I hope this helps!

**Comment by AceCoooool** [comment]
Thank you @Reuben481 , It can work now. (i did not check some sample),  `from _Ax import Ax` can work.~ I close this issue.
