### ISSUE TITLE
Add DBT example in python version

### ISSUE THREAD

**Issue by zhangyu233** [CERN/TIGRE#517]
I found that there is a d19_DBTexample in the MATLAB version, but there python version is missing. I tried  to adapt the geometry setting in the d19_DBTexample.m into the python version. But the results seems to be failed. Could you add the code in the python version?

**Comment by AnderBiguri** [comment]
Hi @zhangyu233,
Thanks for opening the issue. Indeed we don't have a python version of the code. Whenever I have time I'll try to make one, but unfortunately I am quite busy now so it may take a while.

**Comment by zhangyu233** [comment]
Hi, I have modified the code and got the following results.
![Figure_1](https://github.com/CERN/TIGRE/assets/22712879/fdcb3339-b16b-45cc-a319-f19ccbe4ed56)
![Figure_2](https://github.com/CERN/TIGRE/assets/22712879/3b418e2d-8ba4-44b0-a4f8-208f391363af)

`import tigre
import numpy as np
from tigre.utilities import sample_loader
 
from tigre.utilities.common_geometry import staticDetectorGeo
import tigre.algorithms as algs
 
geo = tigre.geometry()
# VARIABLE                                   DESCRIPTION                    UNITS
# -------------------------------------------------------------------------------------
# Distances
 
geo.DSD = 660  # Distance Source Detector      (mm)
geo.DSO = 620 # Distance Source Origin        (mm)
# Detector parameters
projs_rows =  3064/2
projs_cols =  2396/2
geo.nDetector = np.array([projs_rows, projs_cols]).astype('int32')  # number of pixels              (px)
geo.dDetector = np.array([0.1, 0.1])  # size of each pixel            (mm)
geo.sDetector = geo.nDetector * geo.dDetector  # total size of the detector    (mm)
# Image parameters
geo.nVoxel = np.array([1012, 1012, 200])  # number of voxels              (vx)[128;2054;784]/2
geo.sVoxel = np.array( [101.2, 101.2, 20])*2  # total size of the image       (mm) [63.3;205.3;78.4]/2
geo.dVoxel = geo.sVoxel / geo.nVoxel  # size of each voxel            (mm)
# Offsets
Airgap = 22 # 17
 
# geo.offOrigin = np.array([((geo.sVoxel[0]/2)-(geo.DSD-geo.DSO)+Airgap), 0 , geo.sVoxel[2]/2])
# geo.offDetector= np.array([0, geo.sDetector[1]/2])
geo.offOrigin = np.array([0, 0, 0])  # Offset of image from origin   (mm)
geo.offDetector = np.array([0, 0])  # Offset of Detector            (mm)

# Auxiliary
geo.accuracy = 0.5  # Variable to define accuracy of
# 'interpolated' projection
# It defines the amoutn of
# samples per voxel.
# Recommended <=0.5             (vx/sample)
 
# Optional Parameters
# There is no need to define these unless you actually need them in your
# reconstruction
 
 
geo.COR = 0  # y direction displacement for
# centre of rotation
# correction                   (mm)
# This can also be defined per
# angle
 
 
nprojs = 9  # Number of projections
tubeangle = 25  # Angle range
 
# Angles in radians
angles = np.deg2rad(np.linspace(-tubeangle / 2, tubeangle / 2, nprojs))
 
geo.rotDetector=[0, 0 ,0]                    # Rotation of the detector, by
# % X,Y and Z axis respectively. (rad)
# % This can also be defined per
# % angle
 
geo.mode='cone'                      # Or 'parallel'. Geometry type.
 
 
geo.rotDetector = np.array([0, 0, 0])  # Rotation of the detector, by
# X,Y and Z axis respectively. (rad)
# This can also be defined per
# angle
 
geo=staticDetectorGeo(geo,angles)
 
 
 
head = sample_loader.load_head_phantom(geo.nVoxel)
# generate projections
projections = tigre.Ax(head, geo, angles)
 
 
rec = algs.fdk(projections,geo,angles)
 
 
tigre.plotimg(rec, dim="X", clims = [0,1])`

**Comment by AnderBiguri** [comment]
@zhangyu233 I can not debug anything from an image, of course. 

If you are able to post the code your produced in python and:

1 - does the geometry utility for DBT that you coded produce the same values than the MATLAB one?  Show the comparison
2 - Does FBP produce the same result?  Show the comparison
3- Does SART produce the same result? Show the comparison

Otherwise I can unfortunately only say the same thing as you, that those images look a bad.
