### ISSUE TITLE
Test+fix Python 3 compatibility

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#52]
We tried to write the code compatible with python 3, but it has not been tested and likely some minor changes would be required. 

Currently we have no manpower for this task, any help is appreciated.

**Comment by sjha2048** [comment]
@AnderBiguri I would like to take up this issue.

**Comment by AnderBiguri** [comment]
@sjha2048 There is currently a pydev branch where the current python development is being worked. You are very welcomed to fork that branch and work on it, as we are currently not actively looking at this. When you have a working version feel free to make a pull request so we can check it and merge it if its valid.
Thanks!

**Comment by reubenlindroos** [comment]
@sjha2048 thank you for providing the solution for this issue!
