### ISSUE TITLE
cbct post processing

### ISSUE THREAD

**Issue by hyaihjq** [CERN/TIGRE#520]
![lQLPJxx4iewYoQfNAY7NA_uw0blw39i0UvkFqpzxzTjtAA_1019_398](https://github.com/CERN/TIGRE/assets/27874026/bc899b20-f00b-4e30-94e7-9ef3edc59e50)

What post-processing can be used to convert the right image into the left image？thanks

**Comment by AnderBiguri** [comment]
Hi @hyaihjq 
I have no idea! TIGRE does not have a lot of post processing tools yet.
But if the left image is from a manufacturer, then its likely that what they've done is propietary information. To be fair, it just looks like a bit of denoising over a different color range visualization.

**Comment by hyaihjq** [comment]
> Hi @hyaihjq I have no idea! TIGRE does not have a lot of post processing tools yet. But if the left image is from a manufacturer, then its likely that what they've done is propietary information. To be fair, it just looks like a bit of denoising over a different color range visualization.

thanks，Is there any way to enhance the contrast of the teeth area while reducing the contrast of the soft tissue?

**Comment by AnderBiguri** [comment]
@hyaihjq There are ways in the general image processing and medical imaging literature yes, but not any included in TIGRE.
