### ISSUE TITLE
Geometric parameter settings in the tigre

### ISSUE THREAD

**Issue by liq760** [CERN/TIGRE#524]
Hello, I would like to ask how the world coordinate system in Tigre is defined, and how to determine the origin, X-axis, Y-axis and Z-axis of the coordinate system. What is the origin coordinate O based on?

**Comment by AnderBiguri** [comment]
Hi @liq760 ,
as all coordinates are relative, the origin is just a decision to where it is. In TIGRE, 0,0,0 is the point in the middle of the image, and the axis of rotation of the machine goes through it by default. Have a look at the paper and the demos for more details

**Comment by liq760** [comment]
How do I find the center point of an object that is not symmetrical? I know that the axis of rotation is the Z axis in the world coordinate system, and the point pointing to the ray source point S is the x axis. So, is the origin O of the coordinate system determined based on the axis of rotation and the straight line perpendicular to the axis of rotation and passing through S? Or is it still looking for the Image center?

**Comment by liq760** [comment]
How do I find the center point of an object that is not symmetrical? I know that the axis of rotation is the Z axis in the world coordinate system, and the point pointing to the ray source point S is the x axis. So, is the origin O of the coordinate system determined based on the axis of rotation and the straight line perpendicular to the axis of rotation and passing through S? Or is it still looking for the Image center?

**Comment by AnderBiguri** [comment]
@liq760 I'm not sure what do you mean "it is not symmetrical". The image/object is a cube of pixels, its impossible for it not to be symmetrical. 

You defined the location of the origin perfectly w.r.t. the source and the axis of rotation. Is in this origin where the image center lives too. So both are true.

**Comment by liq760** [comment]
<img width="589" alt="屏幕截图 2023-12-03 154021" src="https://github.com/CERN/TIGRE/assets/162790010/fddb2c74-456c-4484-ab36-c2ecae35170a">
For example, for the above three parameters, geo.offOrigin =[0;0;0]; is the offset of the object in the world coordinate system. So, geo.offDetector=[0; 0], is it about the offset of the detector's own coordinate system? If so, where is its origin? geo.rotDetector=[0;0;0]; is the rotation of the detector. It rotates according to which coordinate system. Where is the origin?

**Comment by liq760** [comment]
![屏幕截图 2024-03-14 164747](https://github.com/CERN/TIGRE/assets/162790010/f2509045-e691-4f1f-ad42-a1faa2664798)
For example, for the above three parameters, geo.offOrigin =[0;0;0]; is the offset of the object in the world coordinate system. So, geo.offDetector=[0; 0], is it about the offset of the detector's own coordinate system? If so, where is its origin? geo.rotDetector=[0;0;0]; is the rotation of the detector. It rotates according to which coordinate system. Where is the origin?
