### ISSUE TITLE
Question about tvdenoising.cu

### ISSUE THREAD

**Issue by pjueon** [CERN/TIGRE#529]
Hello. I have a question regarding the tvdenoising algorithm (CUDA/tvdenoising.cu file.).
Firstly, please forgive my lack of theoretical background knowledge on TV denoising.

My question is about the `update_p` function in the code below. 

https://github.com/CERN/TIGRE/blob/ae39ee0dc038051bd026dae093ec1f1d311d3d36/Common/CUDA/tvdenoising.cu#L145-L170

What does `p` represent here?

Initially, when looking at the `update_u` function, I thought `p` might be $\nabla u/ | \nabla u|$ from [ROF PDE](https://en.wikipedia.org/wiki/Total_variation_denoising#Rudin%E2%80%93Osher%E2%80%93Fatemi_PDE):

$$\nabla \cdot (\nabla u/ | \nabla u|) + \lambda(f-u)$$

However, I'm having trouble understanding the logic of updating `p` in the `update_p` function.
Could you please explain this logic, or perhaps point me to a theoretical reference related to this?

Thank you for your time. I would really appreciate your assistance.

**Comment by AnderBiguri** [comment]
Its one of the variables for the primal-dual algorithm used to minimise the ROF. 
The code is essentially an implementation of this paper: https://pubmed.ncbi.nlm.nih.gov/20352289/. You can read more in the paper or my PhD thesis.

**Comment by AnderBiguri** [comment]
I actually should add a reference to it, there is a dead link to the paper in the source code. Should update that.

**Comment by pjueon** [comment]
Thank you very much. I'll check the paper!
