### ISSUE TITLE
FDK printing regardless of verbose kwarg

### ISSUE THREAD

**Issue by gfardell** [CERN/TIGRE#532]
Algorithm prints Tigre geometry and shape as default. I'm guessing this was left in from some debugging, but should probably be behind the a verbosity check.

https://github.com/CERN/TIGRE/blob/3abdda462a2216df71bb2ac2384382f45b21307b/Python/tigre/algorithms/single_pass_algorithms.py#L159-L160

**Comment by casperdcl** [comment]
proper solution: TIGRE should use `logging.getLogger(__name__).{info,warning,debug}` instead of `print`.

temporary end-user work-around for now:

```python
with contextlib.redirect_stdout(io.StringIO()):
    tigre.algorithms.FDK(...)
```

**Comment by AnderBiguri** [comment]
Thanks @gfardell and @casperdcl ! indeed some leftover code, will fix "soon". Ugh, many if these silly things all the time, I need some software engineering people working on TIGRE hehe
