### ISSUE TITLE
Support AAPM low-dose CT reconstruction

### ISSUE THREAD

**Issue by Starbucksmax** [CERN/TIGRE#533]
**Is your feature request related to a problem? Please describe.**
Although [Low Dose CT Grand Challenge](https://www.aapm.org/grandchallenge/lowdosect/) is 2016 dataset. Nowadays still many paper use it. But it seems not a clear code to guide how to reconstruct to CT image from the raw projection data which can be use to the down stream task(sparse-view & limited angle).

**Describe the solution you'd like**
Add the recons code to Demo 21: Loading scanner data to TIGRE.

**Comment by AnderBiguri** [comment]
@Starbucksmax that dataset is not real data, so it definetly doesn't fit the demo. Scanner data is data that comes raw from the machine, and the linked dataset is a machine learning one. 
To reconstruct that dataset with Tigre you just need to input the operator properly. Happy to add a separate demo of it if you provide code.

Note that in any case TIGRE will have limited ML support, I am putting my efforts of CT recon for ML in an unfinished project called LION, which will support datasets.

**Comment by AnderBiguri** [comment]
I am closing this issue @Starbucksmax , but do let me know if you need help.
