### ISSUE TITLE
Gaussian in CTnoise.add function is optional but it doesn't have a default value like Poisson  

### ISSUE THREAD

**Issue by Mr-Blue-Sky-Candy** [CERN/TIGRE#535]
## Expected Behavior
A default value of Gaussian is set

## Actual Behavior
Tigre tries indexing None variable

## Code to reproduce the problem (If applicable)
https://github.com/CERN/TIGRE/blob/master/Python/tigre/utilities/CTnoise.py

  - MATLAB/python version: 2.6

**Comment by AnderBiguri** [comment]
True! Should be (0,0.5)
