### ISSUE TITLE
2D Fan-beam or parallel-beam SART-TV algorithm

### ISSUE THREAD

**Issue by GreameLee** [CERN/TIGRE#537]
It seems like the ART reconstruction algorithm family can only be used in con-beam reconstruction. Our research is based on 2-D CT scan, so can you consider that transfer those algorithms into a 2D version?

**Comment by AnderBiguri** [comment]
Hi @GreameLee 

Is it only SART-TV, or is it all of them? Most of them should work.

**Comment by GreameLee** [comment]
You mean most of ART family algorithms can work on parallel-beam?   if so, what is the meaning of the ALPHA in "SART(PROJ,GEO,ALPHA,NITER)"? I thought it was the cone angle in 3D geography

**Comment by AnderBiguri** [comment]
@GreameLee  nope, all the geometry is defined within the `geo` parameter, except the angles, which used to be defined as `alpha` before, and there is some residue in the documentation still calling them that.
