### ISSUE TITLE
Add Flexible Initialization Option for User-Defined Image in Iteration Algorithm

### ISSUE THREAD

**Issue by stefenmax** [CERN/TIGRE#547]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the iteration algorithm only supports limited initialization techniques. Currently, it only allows initialization to zeros or using the FDK reconstruction.

**Describe the solution you'd like**
I would like to have a more flexible option that allows users to initialize the image using their own image. This new option should enable users to input their own image (as a numpy ndarray) for initialization. This would enhance the versatility and user-friendliness of the algorithm.

**Describe alternatives you've considered**
An alternative solution could be to preprocess the custom image externally before using the iteration algorithm. However, this approach is cumbersome and not as seamless as having the capability built directly into the algorithm.

**Comment by AnderBiguri** [comment]
Good point!

In fact, this seems to be a documentation issue, not a feature issue!:
https://github.com/CERN/TIGRE/blob/2b18d9bb489d2fb46ac87f58fbfcfd9981bb2ec6/Python/tigre/algorithms/iterative_recon_alg.py#L289

It does accept an image as an input :)

**Comment by stefenmax** [comment]
Thanks!
