### ISSUE TITLE
Algorithm on limited angles

### ISSUE THREAD

**Issue by ffbfbfdf** [CERN/TIGRE#548]
Hello, is there an algorithm in the code about solving the limited angle problem？

**Comment by AnderBiguri** [comment]
Hi!
There is no such thing as an algorithm that only works for linked angle, algorithms are geoemtry agnostic.

That said, anything total variation will likely produce a better image, eg SART-TV, or OS-SART-POCS, among others

**Comment by ffbfbfdf** [comment]
Which algorithm will be relatively better for limited angle models？ such as asd-pocs, os-sart

**Comment by AnderBiguri** [comment]
@ffbfbfdf the ones I said in my previous comments ;)
