### ISSUE TITLE
Get "ValueError: operands could not be broadcast together with shapes  " bug when using fbp after ossart_tv

### ISSUE THREAD

**Issue by GreameLee** [CERN/TIGRE#549]
when I run:

> limited_angle = np.linspace(0, np.pi/2, 180)
> limited_projection = tigre.Ax(img, geo, limited_angle)
> print(limited_projection.shape)
> img_tv = ossart_tv(limited_projection,geo,limited_angle,5)
> img_tv.shape
> img_fbp = tigre.algorithms.fbp(limited_projection,geo,limited_angle)
> img_fbp.shape

it get the bug, 
when I run:

> limited_angle = np.linspace(0, np.pi/2, 180)
> limited_projection = tigre.Ax(img, geo, limited_angle)
> print(limited_projection.shape)
> img_fbp = tigre.algorithms.fbp(limited_projection,geo,limited_angle)
> img_fbp.shape
> img_tv = ossart_tv(limited_projection,geo,limited_angle,5)
> img_tv.shape

it goes well

**Comment by AnderBiguri** [comment]
Which line is the bug in?

**Comment by GreameLee** [comment]
img_fbp = tigre.algorithms.fbp(limited_projection,geo,limited_angle)

**Comment by AnderBiguri** [comment]
@GreameLee I am quite sure the error message is much longer, and that it has more information :) Can you paste the entire error trace?

**Comment by GreameLee** [comment]
when I run 

> limited_angle = np.linspace(0, np.pi/2, 180)
> limited_projection = tigre.Ax(img, geo, limited_angle)
> print(limited_projection.shape)
> img_tv = ossart_tv(limited_projection,geo,limited_angle,5)
> img_tv.shape
> img_fbp = tigre.algorithms.fbp(limited_projection,geo,limited_angle)
> img_fbp.shape

I get this bug:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[40], [line 6](vscode-notebook-cell:?execution_count=40&line=6)
      [4](vscode-notebook-cell:?execution_count=40&line=4) img_tv = ossart_tv(limited_projection,geo,limited_angle,5)
      [5](vscode-notebook-cell:?execution_count=40&line=5) img_tv.shape
----> [6](vscode-notebook-cell:?execution_count=40&line=6) img_fbp = tigre.algorithms.fbp(limited_projection,geo,limited_angle)
      [7](vscode-notebook-cell:?execution_count=40&line=7) img_fbp.shape

File c:\Users\Haodong_Li\AppData\Local\anaconda3\envs\pytorch\lib\site-packages\tigre\algorithms\single_pass_algorithms.py:195, in fbp(proj, geo, angles, **kwargs)
    [192](file:///C:/Users/Haodong_Li/AppData/Local/anaconda3/envs/pytorch/lib/site-packages/tigre/algorithms/single_pass_algorithms.py:192) gpuids = kwargs["gpuids"] if "gpuids" in kwargs else None
    [193](file:///C:/Users/Haodong_Li/AppData/Local/anaconda3/envs/pytorch/lib/site-packages/tigre/algorithms/single_pass_algorithms.py:193) proj_filt = filtering(copy.deepcopy(proj), geox,
    [194](file:///C:/Users/Haodong_Li/AppData/Local/anaconda3/envs/pytorch/lib/site-packages/tigre/algorithms/single_pass_algorithms.py:194)                       angles, parker=False, verbose=verbose)
--> [195](file:///C:/Users/Haodong_Li/AppData/Local/anaconda3/envs/pytorch/lib/site-packages/tigre/algorithms/single_pass_algorithms.py:195) return Atb(proj_filt, geo, angles, gpuids=gpuids) * geo.DSO / geo.DSD

ValueError: operands could not be broadcast together with shapes (1,256,256) (180,)

**Comment by AnderBiguri** [comment]
I can not reproduce the error. 

Can you show a minimal example using the TIGRE head data that also trhows an error, so I can copy paste it?

**Comment by AnderBiguri** [comment]
I see. 

try modifying the line that errors to:

    `return Atb(proj_filt, geo, angles, gpuids=gpuids) * geo.DSO[0] / geo.DSD[0]`

This may solve the issue.

**Comment by GreameLee** [comment]
I met this bug after I modify the code as your comment:
'''
Traceback (most recent call last):
  File "tigre_ct.py", line 72, in <module>
    fbp = tigre.algorithms.fbp(sino, geo, angles)
  File "/home/haodong/anaconda3/envs/mbir/lib/python3.8/site-packages/tigre/algorithms/single_pass_algorithms.py", line 195, in fbp
    return Atb(proj_filt, geo, angles, gpuids=gpuids) * geo.DSO[0] / geo.DSD[0]
TypeError: 'int' object is not subscriptable
'''

**Comment by GreameLee** [comment]
> I see.
> 
> try modifying the line that errors to:
> 
> ```
> return Atb(proj_filt, geo, angles, gpuids=gpuids) * geo.DSO[0] / geo.DSD[0]
> ```
> 
> This may solve the issue.

Yes, this can solve the first issue but if I change as this when I run fbp, there will be a bug

**Comment by AnderBiguri** [comment]
Hi @GreameLee, I am currently traveling but I'll fix this ASAP. I think it's just a mix of vectors/ints there, should be an easy fix, but can't do it until I have full access to a computer with a gpu.
