### ISSUE TITLE
Can we do Sparse View 2D forward projection?  

### ISSUE THREAD

**Issue by GreameLee** [CERN/TIGRE#550]
By setting the angle as a small one, we can get the limited angle(such as if we want to get 90-degree limited-angle sinogram :
'''
limited_angle = np.linspace(0, np.pi/2, 90)
'''

But how to set the angle to do sparse view projection?

**Comment by AnderBiguri** [comment]
```
normal_anle= np.linspace(0, 2*np.pi, 360)
limited_angle = np.linspace(0, np.pi/2, 90)
sparse_anlge  = np.linspace(0, 2*np.pi, 90)
```

Obviously not set in stone, netiher "limited angle" nor "sparse angle" are descriptive enough, the numbers don't need to be exactly these.
