### ISSUE TITLE
Motion compensation

### ISSUE THREAD

**Issue by ProjX0** [CERN/TIGRE#558]
Hello,

Thank you very much for developing such a great toolkit.

Do you have any examples of motion correction algorithms for object movement in MATLAB's TIGRE?

Thank you.

**Comment by AnderBiguri** [comment]
Unfortunately most of the code I did back in the time (7 years ago or so) is in this repository https://github.com/AnderBiguri/MotionTIGRE which no lags quite behind TIGRE. Someone with enough time and coding skills could bring it up to current TIGRE standards, but its quite "research code" level.
