### ISSUE TITLE
Fix conda search path for cuda (similar error to tensorflow)

### ISSUE THREAD

**Issue by reubenlindroos** [CERN/TIGRE#56]
- ISSUE: when installing the package, conda will throw an error:
`libcudart.so.8.0 shared object not found`
- REASON: Non compatible versions of cuda for conda and system. 
- TMPFIX: `export CUDAHOME=path/to/latest/libcudart` , `export LD_LIB_PATH=$CUDAHOME:$LD_LIB_PATH`,

**Comment by AnderBiguri** [comment]
conda is being deprecated in favour of pip

**Comment by reubenlindroos** [comment]
Hey man,

Are we still having issues with the repo history? I saw a "bad revert"
commit on the python, which is why I ask.
