### ISSUE TITLE
reconstruct large data

### ISSUE THREAD

**Issue by halfsobolev** [CERN/TIGRE#561]
I need to reconstruct some data from our bench top CT system, and I am having trouble because the data is very large. Our detector is 4096^2 and we collected 1800 projections. For now, all I want to do is flat field the projection data and reconstruct with FBP, but my computer has only 64 GB of CPU RAM. I think FBP would require almost 400 GB of RAM.

Does TIGRE have tools to process this data on my computer?

**Comment by AnderBiguri** [comment]
Unfortunately no, TIGRE assumes you have enough RAM. 

you could always "hack it", i.e. if you break the projections in small enough pieces, and define a series of geometries for small enough sub-reconstructions (using offsets etc), you could do partial reconstructions and save them to disk, then accumulate them by pieces. TIGRE won't do it for you, but with good enough understanding of the geometry, you can write few loops that do the job.
