### ISSUE TITLE
Question about arbitrary axis of rotation using TIGRE

### ISSUE THREAD

**Issue by 1999kevin** [CERN/TIGRE#562]
## Expected Behavior
I want to first rotate the detector around Z-axis for angle0 and then rotate the detector around Y-axis for angle1, as shown in below figure:
![image](https://github.com/CERN/TIGRE/assets/37931674/d77c339c-a3c3-48ff-b342-dabda9348a43)

## Code to reproduce the problem (If applicable)
Is it possible to achieve this function with such code:

```
anglesZ1 = np.linspace(0, np.pi, numProjs)
anglesY = np.linspace(0, np.pi, numProjs)
anglesZ2 = np.zeros_like(anglesZ1)
angles = np.vstack([anglesZ1, anglesY, anglesZ2]).T
projections = tigre.Ax(head, geo, angles)
```

If not, could you please provide a figure about ZYZ configuration to illustrate the function of anglesZ1, anglesY, anglesZ2?

**Comment by AnderBiguri** [comment]
ah indeed, the figure mislead me, apologies. 

These are Euler angles https://en.wikipedia.org/wiki/Euler_angles 
So the rotations are w.r.t locally rotated axis. Indeed it could be that you want what you are proposing, not what I said :)

**Comment by 1999kevin** [comment]
Ok, so it is what I say, ```angles = np.vstack([theta 0, -theta 1, 0]).T``` (negative angle around y-axis) to achieve my figure, right?

**Comment by AnderBiguri** [comment]
I think so, yes.

**Comment by 1999kevin** [comment]
Thank you very much!!!
