### ISSUE TITLE
Python Wang weights don't work appropriately. 

### ISSUE THREAD

**Issue by rupikaraj** [CERN/TIGRE#571]
## Expected Behavior
I have been trying to reconstruct CBCT 670 projections, with a detector shift of 3 pixels.  The expected output is given below. 
https://drive.google.com/file/d/1VfDFkuLNrmzMu2Yst8B4_Q09Yymoc_FI/view?usp=drive_link

## Actual Behavior
By testing various values, I found that offDetector = [-3, -3] gives the best output. 

The output I obtained is in the link below. 
https://drive.google.com/file/d/1xf-21ZAjK-m9QC6srX1m6VRd7t3ss2S4/view?usp=drive_link

The geometry parameters are available in this link: 
https://drive.google.com/file/d/1OA8CvD5uBea98snv2_GKwvEg0q2l40FP/view?usp=drive_link

## Code to reproduce the problem (If applicable)

```
% I am using FDK for reconstruction. 
recon= FDK(projections, geo, angles);

```

Can anyone help me improve this reconstruction output? Are there any other factors which I should consider? 

## Specifications 

  - MATLAB version: 2021b
  - OS: windows 11
  - CUDA version: 11.1

**Comment by AnderBiguri** [comment]
hi @rupikaraj 
I wonder if your offDetector is correct, as its in TIGRE its in mm, not pixels. I can see your detector pixels are `0.139`, so if you know its 3 pixels of offset, it should be `0.139*3`, not `3` that you have offset. Also, is your detector offset in both axis, or just one? You are setting it in both axis, but its often only offseted in horizonal axis in reality.

**Comment by Mint41** [comment]
> hi @rupikaraj I wonder if your offDetector is correct, as its in TIGRE its in mm, not pixels. I can see your detector pixels are `0.139`, so if you know its 3 pixels of offset, it should be `0.139*3`, not `3` that you have offset. Also, is your detector offset in both axis, or just one? You are setting it in both axis, but its often only offseted in horizonal axis in reality.


I have encountered a similar issue in the reconstruction of CBCT。 I possess a set of multi-shadow data, which I intend to reconstruct using the FDK algorithm. The parameters for this reconstruction are as follows:

```python
geo.DSD = 1500
geo.nDetector = np.array([768, 1024])
geo.sDetector = np.array([768 * 0.388, 1024 * 0.388])
geo.dDetector = geo.sDetector / geo.nDetector
geo.offOrigin = np.array([0, 0, 0])
geo.offDetector = np.array([0, -160])
geo.nVoxel = np.array([256, 512, 512])
geo.sVoxel = np.array([256, 512, 512])
geo.dVoxel = geo.sVoxel / geo.nVoxel
geo.rotDetector = np.array([0, 0, 0])
geo.mode = "cone"
```



The corresponding scanning parameters are as follows:

```xml
<ImagerLat Name="Imager Lateral  [IEC Continuous, mm]" Description="Lateral displacement of the imager in half fan mode">-160</ImagerLat>
      <ImagerLng Name="Imager Longitudinal  [IEC Continuous, mm]" Description="Longitudinal displacement of the imager">0</ImagerLng>
      <ImagerSizeX Name="Imager Size X [pixels]" Description="Size of the image detector in X direction">1024</ImagerSizeX>
      <ImagerSizeY Name="Imager Size Y [pixels]" Description="Size of the image detector in Y direction">768</ImagerSizeY>
      <ImagerResX Name="Imager Resolution X [mm/pixel]" Description="Resolution of the image detector in X direction ">0.388</ImagerResX>
      <ImagerResY Name="Imager Resolution Y [mm/pixel]" Description="Resolution of the image detector in Y direction">0.388</ImagerResY>
```

The result is：
![image](https://github.com/user-attachments/assets/71d4283c-07c2-439b-ae6b-75cc2d2db880)

![image](https://github.com/user-attachments/assets/fbee2c6b-4b20-4111-a486-699c16bfbe74)

I am certain that there are no issues with the angle and the Source-to-Detector Distance (DSD). I suspect that the problem lies within the offset. How might I verify the value of this offset?

**Comment by AnderBiguri** [comment]
@Mint41 as I said to the other user, almost surely your lateral displacement is in pixels. However Tigre takes mm, so you need to convert.

**Comment by Mint41** [comment]
> @Mint41 as I said to the other user, almost surely your lateral displacement is in pixels. However Tigre takes mm, so you need to convert.
<ImagerLat Name="Imager Lateral  [IEC Continuous, mm]" Description="Lateral displacement of the imager in half fan mode">-160</ImagerLat>
I'm sorry, but within this parameters, it appears that the unit of measurement is millimeters, not pixels.

**Comment by Mint41** [comment]
<ImagerLat Name="Imager Lateral  [IEC Continuous, mm]" Description="Lateral displacement of the imager in half fan mode">-160</ImagerLat>

**Comment by Mint41** [comment]
`<ImagerLat Name="Imager Lateral  [IEC Continuous, mm]" Description="Lateral displacement of the imager in half fan mode">-160</ImagerLat>`

**Comment by AnderBiguri** [comment]
@Mint41 You are correct! I think you error is no coming from the gemetry, but from the FDK algorithm. 
If you use e.g. os_sart, do you get the same rings?

**Comment by Mint41** [comment]
Indeed, after employing the OS-SART, I obtained more satisfactory reconstruction results. Therefore, perhaps the reconstruction parameters are not at fault. Could you please enlighten me as to what aspect within the FDK algorithm might have led to these outcomes?
<img width="323" alt="image" src="https://github.com/user-attachments/assets/2d097355-266f-4745-a804-f219d6b34949">

**Comment by rupikaraj** [comment]
@AnderBiguri I have tried changing the offdetector values as you suggested, but the output is still not satisfactory. Like @Mint41 , I'm also getting good results when I tried OSSART. 

Can u suggest some other methods to make the output better using FDK ?

**Comment by rupikaraj** [comment]
Hi @AnderBiguri , I tried changing the offdetector values as you suggested and the output is still not good. Just like @Mint41 , I am getting better outputs in OSSART. Could you suggest how to improve the quality of output using FDK ?

**Comment by AnderBiguri** [comment]
@Mint41 @rupikaraj there is likely some issue in the Wang weigths of the filtering of FDK. Its not a user-parameter, but a mistake on my side, I think. 

There is a function that uses "Wang weights" to apply a weight to correct for detector offset, the relevant code is this: 
https://github.com/CERN/TIGRE/blob/7279e019645e3b9104f899e0255a5c2245915341/Python/tigre/algorithms/single_pass_algorithms.py#L103-L144

I believe that the MATLAB side does not have this issue. The relevant function is this: https://github.com/CERN/TIGRE/blob/master/MATLAB/Utilities/redundancy_weighting.m

If you can find differences, I suggest you try to fix them yourself, and test if that fixes the issue. I will try to investigate myself as soon as I have some time, but it won't be very soon, apologies for that, as I am very busy.  If you find the issue, let me know and I can update TIGRE to get it fixed.

**Comment by Mint41** [comment]
thanks for your patient elucidation

**Comment by Mint41** [comment]
When I endeavoured to proceed without the utilization of Wang weighting 
by change the code as
    # dowang = kwargs["dowang"] if "dowang" in kwargs else False
    dowang = False
  the reconstructed images still manifested the same rings. Hence, I think that the issue does not reside within preweighting. Could you suggest where else the problem might potentially originate?
![image](https://github.com/user-attachments/assets/04144ae4-a96e-4474-bfe2-77f23d254aca)

**Comment by AnderBiguri** [comment]
You may have misunderstood. Want weights are **required** to get a good image with detector offset. I think that my version of the Wang weigths may have a bug, some small mistake that makes them not perfect, and therefore you get the errors. If you remove Wang weigths then you are guaranteed to get a bad image.

**Comment by Medphys-KM** [comment]
In MATLAB, I always meet similar problems. Recently, I find if the 'parker' is set to be 'flase', the artifact can be reduced. This is confusing. It seems that other user meet the problem before in issues 382.
https://github.com/CERN/TIGRE/issues/382

**Comment by AnderBiguri** [comment]
@Medphys-KM I believe the the MATLAB version is now correct, but the python version indeed seems to have a bug

**Comment by AnderBiguri** [comment]
Seems that due to a bug Wang weigths were disabled by default. Fixed it. Let me know if you have more issues
