### ISSUE TITLE
gpuids must be positive integers

### ISSUE THREAD

**Issue by ReidIsaak** [CERN/TIGRE#573]
https://github.com/CERN/TIGRE/blob/7279e019645e3b9104f899e0255a5c2245915341/MATLAB/Utilities/IO/VarianCBCT/BH_ObjectRemapping.m#L58

Currently get the following error when trying to use beam hardening correction.
  Error using gpuDevice (line 26)
  Argument must be a positive integer or [].
  
Adding 1 to the gpuids.devices resolved the issue.
g = gpuDevice(gpuids.devices(ii)+1);

**Comment by AnderBiguri** [comment]
Thanks @ReidIsaak ! Ithought I fixed these, but clearly I have not! Thanks for the find!

**Comment by DaNian22** [comment]
How to use the beam hardening correction program？
