### ISSUE TITLE
When I set geo=defaultGeometry('nVoxel', [1024;1024;1024]), the program crashes directly, what is the cause of this?

### ISSUE THREAD

**Issue by daxiaojiupang** [CERN/TIGRE#575]
## Code to reproduce the problem (If applicable)

```

```

## Specifications 

  - MATLAB/python version:
  - OS:
  - CUDA version:

**Comment by daxiaojiupang** [comment]
![1724146603681](https://github.com/user-attachments/assets/3faa4579-7a50-4e51-823b-2044cd4af205)
![1724146755364](https://github.com/user-attachments/assets/508bfb89-5287-4d2b-815d-079ce6af57ac)
I only changed the geo.nVoxel parameter, nothing else, and then the program just crashed.

**Comment by daxiaojiupang** [comment]
> As you are aware,
> 
> geo=defaultGeometry('nVoxel', [1024;1024;1024])
> 
> Does not make the program crash. Code to reproduce the problem is importar, this is why it's there in your comment to fill it in. Please provide full information about where it crashes and the rest of the information required for me to be able to help. Otherwise as far as I know this could be unrelated to Tigre.

![1724146603681](https://github.com/user-attachments/assets/89ef1fc1-29ee-4554-8fb4-f62eaacb7fb8)
![1724146755364](https://github.com/user-attachments/assets/07472fdb-b42b-4cd4-92bd-110ad96a2553)
I only changed the geo.nVoxel parameter, nothing else, and then the program just crashed.

**Comment by AnderBiguri** [comment]
That's a matlab installation issue, in fact I don't even think that should crash matlab, just a normal Ubuntu + matlab warning.

In any case, that message is unrelated to Tigre, it's about your local installation of matlab, which I cna not help with

**Comment by daxiaojiupang** [comment]
> That's a matlab installation issue, in fact I don't even think that should crash matlab, just a normal Ubuntu + matlab warning.
> 
> In any case, that message is unrelated to Tigre, it's about your local installation of matlab, which I cna not help with

I see. Thank you very much for your reply.
