### ISSUE TITLE
Support for DICOM data from ADNI PET-CT dataset

### ISSUE THREAD

**Issue by jpsml** [CERN/TIGRE#578]
Hi, I am trying to use the TIGRE toolbox to load DICOM data from the ADNI PET-CT dataset (https://adni.loni.usc.edu/). However, I got the following error:

> 
> Warning: This loader has only been tested with C-arm (CARM) scanners, which your DICOM data does not seem to be
> If you have data not supported by this loader that you want supported, contact [tigre.toolbox@gmail.com](mailto:tigre.toolbox@gmail.com)
> and we can work together in improving this code to load your data.
> > In dicomDataLoader (line 28)
>   In AdniDataLoader (line 2)
> Attempting to read the data anyway....
> Warning: Some dicom files did not contain required fields: 540 files ignored.
> > In dicomDataLoader>checkDicomHeaders (line 172)
>   In dicomDataLoader (line 49)
>   In AdniDataLoader (line 2)
> Index exceeds array bounds.
> 
> Error in dicomDataLoader (line 52)
>     proj=zeros(dicomhdr{1}.Height,dicomhdr{1}.Width,length(dicomhdr),'single');
> 
> Error in AdniDataLoader (line 2)
> [proj,geo, angles,dicomhdr] = dicomDataLoader(datafolder);

I need to load this data in order to use them for running the following code:
https://github.com/Ruyi-Zha/naf_cbct

Would you help me to improve the TIGRE code to load this data?

**Comment by AnderBiguri** [comment]
Heya! I seem to have missed this, apologies. 

I am not sure if that dicom data is a sinogram or a CT image, given its a PET-CT scanner data, I suspect the latter. If so, you just need to open it with standard dicom data code, check the MATLAB documentation.
