### ISSUE TITLE
Iterative reconstruction produces artifacts on both ends of the slice

### ISSUE THREAD

**Issue by zezisme** [CERN/TIGRE#587]
## Expected Behavior
Hello ！
When using cone-beam CT reconstruction, no matter how I define the reconstruction parameters, using the iterative reconstruction algorithm (SART, OS-SART, ...) will cause serious artifacts on both ends of the slice image, while the FDK algorithm is normal. What may be the reason for this?
I have tested many iterative reconstruction algorithms and all of them have this problem.
![image](https://github.com/user-attachments/assets/85870a3a-7d79-4adc-93b2-79800d916f6d)

## Actual Behavior
FDK
![image](https://github.com/user-attachments/assets/b1689753-b7aa-4ef7-a846-160234ca0f81)

OS-SART
![image](https://github.com/user-attachments/assets/a505f12a-c6a5-4acd-91a3-61b5d1559138)
![image](https://github.com/user-attachments/assets/e2ef970a-e05c-4853-b814-f67fab669444)
![image](https://github.com/user-attachments/assets/a2bc9590-3e33-482a-89a5-c802646ae3df)
![image](https://github.com/user-attachments/assets/4be2b6e3-b92d-40f9-b2f5-54948ce7ddfb)

other example(OS-SART) MPR view
![image](https://github.com/user-attachments/assets/75877e45-fc4d-46a5-ae4b-098e4205dd99)

## Code to reproduce the problem (If applicable)

![image](https://github.com/user-attachments/assets/38c1c3e7-8441-49ea-bac2-b834c659c7fb)

## Specifications 

  - MATLAB version:
  - OS:
  - CUDA version:

**Comment by zezisme** [comment]
![image](https://github.com/user-attachments/assets/38c1c3e7-8441-49ea-bac2-b834c659c7fb)

**Comment by AnderBiguri** [comment]
Yes, those are cone beam artifacts, natural in CBCT. They tend to be worse in iterative algorithms in the situation in where there was more object in the area you are not reconstructing, as iterative algorithms try to match the measured projections with the reconstruction, however as you don't have the whole image in the ROI, they put more values in the extrema to accomodate. 

A standard way to mitigate these is to make the reconstruction volume (nVoxel and sVoxel) bigger in the Z direction. Then you can crop it out after recon if you want it the same size as FDK.

**Comment by zezisme** [comment]
> Yes, those are cone beam artifacts, natural in CBCT. They tend to be worse in iterative algorithms in the situation in where there was more object in the area you are not reconstructing, as iterative algorithms try to match the measured projections with the reconstruction, however as you don't have the whole image in the ROI, they put more values in the extrema to accomodate.
> 
> A standard way to mitigate these is to make the reconstruction volume (nVoxel and sVoxel) bigger in the Z direction. Then you can crop it out after recon if you want it the same size as FDK.

Thank you for your clear reply！I will try your suggestion
