### ISSUE TITLE
The ynesterov_prev is not updata in SIRT,SART,OS-SART

### ISSUE THREAD

**Issue by zezisme** [CERN/TIGRE#588]
## Expected Behavior
I found that the variable ynesterov_prev has not been updated when iterating using nesterov method，Is this a mistake?

  - MATLAB version:

**Comment by AnderBiguri** [comment]
Its here:

https://github.com/CERN/TIGRE/blob/851557aba6601bc6537f74859bf6a5bdba97ba6c/MATLAB/Algorithms/SIRT.m#L113

or you mean something else?

**Comment by zezisme** [comment]
> Its here:
> 
> https://github.com/CERN/TIGRE/blob/851557aba6601bc6537f74859bf6a5bdba97ba6c/MATLAB/Algorithms/SIRT.m#L113
> 
> or you mean something else?

ynesterov_prev is only initialized here, but do not updata with iterating, so its value seems to be always zero

**Comment by AnderBiguri** [comment]
Correct! this is a bug, not even sure when introduced. Indeed a mistake!
