### ISSUE TITLE
2D sinogram

### ISSUE THREAD

**Issue by rasad-hub** [CERN/TIGRE#590]
Hello, I have a two-dimensional sinogram matrix that I prepared from Phantom, how can I reconstruct this two-dimensional sinogram with package algorithms? Do I need to make the sinogram three-dimensional by manipulating it in MATLAB?

**Comment by AnderBiguri** [comment]
Hi! you can have a look at the 2D demo: https://github.com/CERN/TIGRE/blob/master/MATLAB/Demos/d16_2Dtomography.m

Let me know if you have any questions.
