### ISSUE TITLE
About Tomosynthesis geometry

### ISSUE THREAD

**Issue by SuBongHyun** [CERN/TIGRE#610]
Currently, I understand that TIGRE supports only the configuration where both the detector and source rotate together in alignment with CBCT geometry. Could you kindly let us know if there are any plans to update the system to support tomosynthesis configurations where the detector remains fixed while only the source rotates?

**Comment by AnderBiguri** [comment]
@SuBongHyun Tigre in fact supports any geometry, but for some understanding the geometry structure flexibility is needed. For tomosynthesis (eg digital breat tomosynthesis) have a look at demo 19.
