### ISSUE TITLE
Ax- forward projection error

### ISSUE THREAD

**Issue by esrasmr** [CERN/TIGRE#64]
I am using anistropic 3D shepp-logan phantom which is in test_data folders. But I have 'Input image must be a single noncomplex array.' error from MATLAB. How can I fix this ? 

Thanks for your reply.

**Comment by AnderBiguri** [comment]
Hum that may be a bug. When you load the Phantom, try converting it to
single as:

data=single(data) ;

**Comment by esrasmr** [comment]
I have just tried it but it did not work

**Comment by AnderBiguri** [comment]
Can you show me the complete code you are using?

**Comment by esrasmr** [comment]
%% Creating geometry 
geo.DSD = 1536;                             % Distance Source Detector      (mm)
geo.DSO = 1000;                             % Distance Source Origin        (mm)
%%Detector parameters 
geo.nDetector=[256;256];  
%Number of pixels
geo.dDetector=[0.8;0.8];                    %Size in (mm) of each pixel
geo.sDetector=geo.nDetector.*geo.dDetector; %Total size of detector in mm

%%Image parameters
geo.nVoxel=[128;128;32];                   % number of voxels              (vx)
geo.sVoxel=[128;128;32];                   % total size of the image       (mm)
geo.dVoxel=geo.sVoxel./geo.nVoxel;          % size of each voxel            (mm)

%%% Offsets
geo.offOrigin =[0;0;0];                     % Offset of image from origin   (mm)              
geo.offDetector=[0; 0];                     % Offset of Detector            (mm)

% Auxiliary 
geo.accuracy=0.5;                           % Variable to define accuracy of
                                            % 'interpolated' projection.It defines the amoutn of
                                            % samples per voxel.
                                            
geo.COR=0;                                  % y direction displacement for 
                                            % centre of rotation
                                            % correction   
                                            
geo.rotDetector=[0;0;0];                    % Rotation of the detector, by 
                                            % X,Y and Z axis respectively. (rad)
                                            % This can also be defined per
                                            % angle   
geo.mode='parallel';                            % Or 'parallel'

%%Plot the geometry
                                            
plotgeometry(geo,-pi/6);     


%%loading data 
head=phantom3dAniso([128 128 32]);
head=single(head);

%% Defining angles of projection 
angles=linspace(0,pi,30); %% in rad.

% Simulate forward projection
projections=Ax(head,geo,angles,'interpolated'); %%other option:voxel-ray intersection (Siddon)

**Comment by AnderBiguri** [comment]
Thanks. I will have a look at this as soon as I can.

**Comment by ilanzhang** [comment]
@AnderBiguri Actually, I met this problem too when I modify the file : minimizeTV to minimizePnorm for  calculating the p-norm regularization. Errors showed that single input parameters were needed.

**Comment by AnderBiguri** [comment]
@ilanzhang that is strange. MATLAB checks if the input is real and single (float) before doing th emaths, but there should be no error if it is.... I can not reproduce the error.

**Comment by AnderBiguri** [comment]
@esrasmr  Strange, I can run that piece of code perfectly and my version of TIGRE is the same as the one it Github.... Does it work for all images? have you tried some random data?

**Comment by ilanzhang** [comment]
@AnderBiguri i guess maybe the reason of different data type between matlab and C++. you have rewrote the code in the C++ for TV regularization with the parameters of images, iteration step and iteration numbers: 
`f=minimize(f,dtvg,ng)`
And i just added an additional paramter p for p-norm regularization:
`f=minimize(f,dtvg,ng,p)`
which is just similar to the setting of iteration step because they could be a single one. I have thought there shouldn't be any problem, but it just showed that the input paramter shouldn't be single. I couldn't think out where the problem is so I just realized it by matlab code, it just wasted more time and no errors showed.

**Comment by AnderBiguri** [comment]
@ilanzhang  that is strange, because the code that trows the error is written by me, not a MATLAB error, and minTV.cpp does not have it. DO you know what is the exact error?

**Comment by ilanzhang** [comment]
@AnderBiguri The code is running now, i'll try it again and put the exact error once it finish. Thank you!

**Comment by esrasmr** [comment]
The problem was solved, thank you for your suggestions.

**Comment by AnderBiguri** [comment]
Hi
How did you solve the problem?

Ander

**Comment by AnderBiguri** [comment]
@esrasmr  Fantastic! do not hesitate to contact me with any further questions

**Comment by ilanzhang** [comment]
@AnderBiguri It's embarrassing the error with single just couldn't show up agian, and just produce the result with NaN. It seems sometimes it just produce the NaN result but sometimes it just produce the error of single one.

**Comment by AnderBiguri** [comment]
The NaN problem may be fixable, I will have a look at that. I think it may
be that the eps to avoid division by zero is too small. The change should
be just increasing the size of that number by a couple of orders of
magnitudes.

Ander

**Comment by ilanzhang** [comment]
Thank you! I'll try it.
