### ISSUE TITLE
Python code not installing

### ISSUE THREAD

**Issue by venkat-purdue** [CERN/TIGRE#65]
When I run 

python setup.py build 

I get the following error:
tigre/Source/_Ax.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.

Could you please advice ?

**Comment by Reuben481** [comment]
Could you check your cython version? Also what OS/system are you trying to run this on?

**Comment by venkat-purdue** [comment]
Cython 0.25.2
Ubuntu 16.04

**Comment by Reuben481** [comment]
Sorry for the delayed reply! 

So, Cython is not compiling the files for some reason. have you tried with the conda install method? Does it throw the same error in that case?
