### ISSUE TITLE
Filtered Back Projection for 3D Parallel Beam Tomography

### ISSUE THREAD

**Issue by ritwickchaudhry** [CERN/TIGRE#71]
I read that TIGRE is in beta for Parallel Beam Tomography, and I wanted an FBP for 3D parallel beam tomography. When we run the FBP function it says, "Only use FBP for parallel beam CT" which is because in FBP.m, there is a check that the geo.mode should be "cone". Should it not be for Parallel Beam?

The code I am referring to is:
https://github.com/CERN/TIGRE/blob/20dd82c0861e48b1d41faaf5abbc6da8a173b146/MATLAB/Algorithms/FBP.m#L25

**Comment by AnderBiguri** [comment]
Hi @ritwickchaudhry , I can safe with sufficient conviction now that TIGRE is no more beta for Parallel Beam and that you can use it completely for it. I have already tested it myself with real data and sufficient algorithms and methods. 

That piece of code is for an error. It basically says:  "If there is no `mode` or the mode is the same as `'cone'`, then error. 

To be fair, its an obscure and weak error, so I am going to change it to `if isfield(geo,'mode') && strcmpi(geo.mode,'parallel')`, but ultimately, with the current version, it won't throw an error if you have defined `geo.mode='parallel'`). So if you have that error it means that you missed this. For cone beam, defining the mode is not necessary, but it is for parallel.
