### ISSUE TITLE
Issue with FBP

### ISSUE THREAD

**Issue by ritwickchaudhry** [CERN/TIGRE#72]
I had recently raised an issue with FBP. I still think either there is some issue, or I am doing something terribly wrong. I have geo.mode set as parallel

https://github.com/CERN/TIGRE/blob/d8dbfd24553a9f565e3be0e4348912f03943d682/MATLAB/Algorithms/FBP.m#L25

Here, since the mode is set isfield(geo,'mode') returns True, and strcmpi(geo.mode,'parallel') returns True as well. So an error will be thrown if the geo mode is set as parallel.

Am I missing something?

**Comment by AnderBiguri** [comment]
@ritwickchaudhry  that was a mistake, you are right. I'll fix it with more care. Thanks for raising this.

**Comment by ritwickchaudhry** [comment]
Thanks for that. @AnderBiguri

**Comment by ritwickchaudhry** [comment]
Also, @AnderBiguri can you please provide a sample script for 3D Parallel Beam Projections and then FBP. That would really help a lot.

**Comment by AnderBiguri** [comment]
@ritwickchaudhry  Certainly, have a look at demo 15:

https://github.com/CERN/TIGRE/blob/master/MATLAB/Demos/d15_3Dparallel.m

**Comment by ritwickchaudhry** [comment]
@AnderBiguri , I meant reconstruction using Filtered Back Projection. (The script has reconstruction by OS_SART). When I am doing FBP, I am getting 0 Values

**Comment by AnderBiguri** [comment]
@ritwickchaudhry  Yes, it should work just with the line I suggested. I will re-check this tomorrow in case I have at some point introduced any bug that have made it stopped working.  (as it has been tested with other data).

**Comment by ritwickchaudhry** [comment]
Thanks a lot. Please try this script.


`
geo.DSD = 2000;                             % Distance Source Detector      (mm)
geo.DSO = 1000;                             % Distance Source Origin        (mm)
% Detector parameters

% Make the pixels in the detector the same size as the image voxels
% (or viceversa)!

geo.nDetector=[512; 512];					% number of pixels              (px)
geo.dDetector=[2; 2]; 					    % size of each pixel            (mm)
geo.sDetector=geo.nDetector.*geo.dDetector; % total size of the detector    (mm)
% Image parameters
geo.nVoxel=[128;128;128];                   % number of voxels              (vx)
geo.sVoxel=[512;512;512];                   % total size of the image       (mm)
geo.dVoxel=geo.sVoxel./geo.nVoxel;          % size of each voxel            (mm)
% Offsets
geo.offOrigin =[0;0;0];                     % Offset of image from origin   (mm)              
geo.offDetector=[0; 0];                     % Offset of Detector            (mm)
% Auxiliary 
geo.accuracy=0.5;                           % Accuracy of FWD proj          (vx/sample)


%% As easy as this:
geo.mode='parallel';
%% Load data and generate projections 
% see previous demo for explanation
angles=linspace(0,2*pi/3,360);
head=headPhantom(geo.nVoxel);
projections=Ax(head,geo,angles,'interpolated');

reconFBP = FBP(projections,geo, angles)

imwrite(head(:,:,100), 'Actual.jpg')
imwrite(reconFBP(:,:,100), 'FBP.jpg')
`

**Comment by AnderBiguri** [comment]
@ritwickchaudhry I am looking at this now. As a side note: `jpg` is a lossy format, you will loose information thus generate images that are worse than the original ones. Use lossless formats, such as `png`

**Comment by AnderBiguri** [comment]
@ritwickchaudhry  I will push my small bug fixes, however I can not reproduce what you say. Your code outputs the following image ad `FBP.jpg`

![fbp](https://user-images.githubusercontent.com/11854388/37649656-5b143d86-2c2a-11e8-9aa7-68f68fca5c1b.jpg)
