### ISSUE TITLE
Motion compensation modelling

### ISSUE THREAD

**Issue by gudsqa** [CERN/TIGRE#79]
In you PhD thesis, there is a chapter for  motion compensation based 4D-CBCT reconstruction. Did you implement it in this toolbox? If not, any suggestion how to implement it. Thanks.

**Comment by AnderBiguri** [comment]
Hi @gudsqa  
Absolutely right, this is entirely my bad. The main reason for this is that the code is quite unpolished and its not efficient. 
However, I have just uploaded the code with a demo, that explains with the same terms as the PMB article how everything works. 
Here it is: https://github.com/AnderBiguri/MotionTIGRE

You need to put this files in the same folder as TIGRE.
Please, do not hesitate to contact me, or open issues in this other repository, so I can keep improving the code. 

Ander

**Comment by gudsqa** [comment]
Hi Ander, Thanks for the swift reply. I have downloaded the code. But have a problem when compiling it. I have successfully compiled the Tigre without a problem (win7x64, Matlab2107, vs2013,cuda8.0)
Any suggestion will be appreciated. Thanks.
-----------
>> mex -largeArrayDims ./Motion_Source/AxM.cpp   ./Motion_Source/ray_interpolated_projection_motion.cu ./Motion_Source/Siddon_projection.cu -outdir ./Motion_Correction
Error using mex
No supported compiler or SDK was found. For options, visit https://www.mathworks.com/support/compilers.

**Comment by AnderBiguri** [comment]
@gudsqa  hmmm, 
Try to add the compile lines to the `Compile.m` file, after this line  https://github.com/CERN/TIGRE/blob/master/MATLAB/Compile.m#L114
and then Compiling the entire TIGRE with it.
Let me know how that goes

**Comment by gudsqa** [comment]
I put all the motion source files to the Tigre source folder.
Start compiling but got an unsolved external symbol error. 
====
Building with 'NVIDIA CUDA Compiler'.
Error using mex
   Creating library E:\QACode\cbctReconst\test\TIGRE-master\TIGRE-master\MATLAB\Motion_Correction\AxM.lib and object
   E:\QACode\cbctReconst\test\TIGRE-master\TIGRE-master\MATLAB\Motion_Correction\AxM.exp
Siddon_projection.obj : error LNK2019: unresolved external symbol "void __cdecl rollPitchYaw(struct Geometry,unsigned int,struct Point3D *)"
(?rollPitchYaw@@YAXUGeometry@@IPEAUPoint3D@@@Z) referenced in function "void __cdecl computeDeltas_Siddon(struct Geometry,int,struct Point3D *,struct
Point3D *,struct Point3D *,struct Point3D *)" (?computeDeltas_Siddon@@YAXUGeometry@@HPEAUPoint3D@@111@Z)
Siddon_projection.obj : error LNK2019: unresolved external symbol "void __cdecl eulerZYZ(struct Geometry,struct Point3D *)"
(?eulerZYZ@@YAXUGeometry@@PEAUPoint3D@@@Z) referenced in function "void __cdecl computeDeltas_Siddon(struct Geometry,int,struct Point3D *,struct
Point3D *,struct Point3D *,struct Point3D *)" (?computeDeltas_Siddon@@YAXUGeometry@@HPEAUPoint3D@@111@Z)
E:\QACode\cbctReconst\test\TIGRE-master\TIGRE-master\MATLAB\Motion_Correction\AxM.mexw64 : fatal error LNK1120: 2 unresolved externals



Error in Compile (line 115)
        mex -largeArrayDims ./Source/AxM.cpp   ./Source/ray_interpolated_projection_motion.cu ./Source/Siddon_projection.cu -outdir
        ./Motion_Correction

**Comment by AnderBiguri** [comment]
@gudsqa I'll take a closer look at this on Monday with a bit more time, and try to fix any possible errors.
Ander

**Comment by gudsqa** [comment]
I modified the compile line to following and compiled without problem. Thanks.

===========
mex -largeArrayDims ./Source/AxM.cpp   ./Source/ray_interpolated_projection_motion.cu ./Source/ray_interpolated_projection.cu ./Source/Siddon_projection.cu ./Source/ray_interpolated_projection_parallel.cu ./Source/Siddon_projection_parallel.cu -outdir ./Mex_files/win64

**Comment by AnderBiguri** [comment]
@gudsqa  the only change you did was modifying the output location?
