### ISSUE TITLE
Compile Error in MATLAB

### ISSUE THREAD

**Issue by givens** [CERN/TIGRE#81]
## Expected Behavior

TIGRE compiling after typing Compile in MATLAB.

## Actual Behavior

Compile error

```
Error in Compile (line 110)
        mex -largeArrayDims ./Source/Ax_mex.cpp
        ./Source/ray_interpolated_projection.cu ./Source/Siddon_projection.cu
        ./Source/ray_interpolated_projection_parallel.cu
        ./Source/Siddon_projection_parallel.cu -outdir ./Mex_files/win64
```

## Code to reproduce the problem (If applicable)

Typing compile after installing MinGW64 Compiler, but no supported compiler found even though MEX is configured to use it.

```
Compile
MEX configured to use 'MinGW64 Compiler (C)' for C language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
	 variables with more than 2^32-1 elements. You will be required
	 to update your code to utilize the new API.
	 You can find more information about this at:
	 https://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN
Compiling TIGRE source...
This may take a couple of minutes....
Error using mex
No supported compiler was found. For options, visit
https://www.mathworks.com/support/compilers.

Error in Compile (line 110)
        mex -largeArrayDims ./Source/Ax_mex.cpp
        ./Source/ray_interpolated_projection.cu ./Source/Siddon_projection.cu
        ./Source/ray_interpolated_projection_parallel.cu
        ./Source/Siddon_projection_parallel.cu -outdir ./Mex_files/win64
```

## Specifications 

  - MATLAB version:  '9.4.0.813654 (R2018a)'
  - OS:  Windows 10
  - CUDA version:  9.2

**Comment by AnderBiguri** [comment]
Hi @givens ,
MinGW64 is not supported by CUDA, unfortunately. 
I suggest trying to install CUDA 9.1, as TIGRE currently provides compiled packages for that version. 
Best
Ander

**Comment by givens** [comment]
Thanks.  So Microsoft Visual Studio for C++?

**Comment by AnderBiguri** [comment]
Hi @givens  
I tried to compile the code without dependencies (adding all the libraries required in the compilation).
If you want, you can try to test this compiled files, they should be working  for any computer. 
Please let me know if they work.
Otherwise, yes,  Microsoft Visual Studio for C++. Check your MATLAB version and CUDA version compatibilities first.

Ander 

[win64.zip](https://github.com/CERN/TIGRE/files/2158595/win64.zip)

**Comment by givens** [comment]
I will let you know.

**Comment by givens** [comment]
I added the win64.zip file as a subdirectory called win64 to Mex_files.  I ran the d01, d02, d03, and d04 demos.  d01 and d02 worked.  I received errors for d03 and d04.  This is the error:

Invalid MEX-file 'C:\Users\englab\Documents\GitHub\TIGRE\MATLAB\Mex_files\win64\Ax_mex.mexw64': Missing
dependent shared libraries:
'cudart64_91.dll' required by 'C:\Users\englab\Documents\GitHub\TIGRE\MATLAB\Mex_files\win64\Ax_mex.mexw64'

The error is saying that cudaart64__91.dll is required by the Ax mex function.  This could be on my end.  However, I ask for your advice.  I downloaded and installed cuda 9.1 and three patches.  There was a path error.  The environment variable was at its max length and could not add new directory locations.  However, I checked the path variable and thought I saw that the directories were added.  The other thing that comes to mind is that I installed 9.2 first.  It could be defaulting to 9.2.  I am running this on Windows 7 now.

**Comment by AnderBiguri** [comment]
@givens  ah, I compiled the code hoping that this DLL would be included in the mex files and the error could be avoided, but it doesn't seem that it worked, it is not on your end. 
Let me install 9.2 on my end, recompile and put the files here, hopefully that will work for you. 

I will keep looking for ways to make sure I can distribute compiled files without dependencies

**Comment by AnderBiguri** [comment]
Hi @givens ,
Just as a test: try adding cudart64_91.dll (download down there) to the mex file folder and try again

[cudart64_91.zip](https://github.com/CERN/TIGRE/files/2166574/cudart64_91.zip)

**Comment by givens** [comment]
I got past the error by putting the cudart64_91 file into the win64 folder.  I ran into a bind fail.  My understanding is that there is a 3d array created by the Ax function that cannot bind to the CUDA texture or is somehow invalid.

>> d03_generateData
3D texture memory bind fail 
Error using Ax_mex
invalid texture reference

Error in Ax (line 59)
projections=Ax_mex(img,geo,angles,ptype);

Error in d03_generateData (line 56)
projections=Ax(head,geo,angles,'interpolated');

**Comment by AnderBiguri** [comment]
@givens sorry this is on my side, it just means there are more things needed than cudart64. I will compile with 9.2 and attach the files, hopefully it will work. Otherwise you can isntall Visual studio and try it yourself.

**Comment by AnderBiguri** [comment]
@givens  these have been compiled with 9.2. Have a try.
[mex.zip](https://github.com/CERN/TIGRE/files/2187911/mex.zip)

**Comment by givens** [comment]
Thank you.  

 I removed all Nvidia components, reinstalled 9.1, and re-tryed compiling with msvcpp2017 and msvcpp2013.  I received the error shown below.  The screen output states it cannot find, or open, gpu.lib.  Gpu.lib is part of matlab. 

I will try 9.2.

```
>> Compile
Renamed options file 'C:\Users\englab\AppData\Roaming\MathWorks\MATLAB\R2018a\mex_C++_win64.xml' to 'C:\Users\englab\AppData\Roaming\MathWorks\MATLAB\R2018a\mex_C++_win64_backup.xml'.
MEX configured to use 'Microsoft Visual C++ 2017' for C++ language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
	 variables with more than 2^32-1 elements. You will be required
	 to update your code to utilize the new API.
	 You can find more information about this at:
	 https://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.
Compiling TIGRE source...
This may take a couple of minutes....
Building with 'NVIDIA CUDA Compiler'.
C:/Users/englab/Documents/GitHub/TIGRE/MATLAB/Source/Siddon_projection_parallel.cu(144): warning: variable "azm" was declared but never referenced
C:/Users/englab/Documents/GitHub/TIGRE/MATLAB/Source/Siddon_projection_parallel.cu(145): warning: variable "azM" was declared but never referenced
C:/Users/englab/Documents/GitHub/TIGRE/MATLAB/Source/Siddon_projection_parallel.cu(144): warning: variable "azm" was declared but never referenced
C:/Users/englab/Documents/GitHub/TIGRE/MATLAB/Source/Siddon_projection_parallel.cu(145): warning: variable "azM" was declared but never referenced
C:/Users/englab/Documents/GitHub/TIGRE/MATLAB/Source/Siddon_projection_parallel.cu(144): warning: variable "azm" was declared but never referenced
C:/Users/englab/Documents/GitHub/TIGRE/MATLAB/Source/Siddon_projection_parallel.cu(145): warning: variable "azM" was declared but never referenced
C:/Users/englab/Documents/GitHub/TIGRE/MATLAB/Source/Siddon_projection_parallel.cu(144): warning: variable "azm" was declared but never referenced
C:/Users/englab/Documents/GitHub/TIGRE/MATLAB/Source/Siddon_projection_parallel.cu(145): warning: variable "azM" was declared but never referenced
C:/Users/englab/Documents/GitHub/TIGRE/MATLAB/Source/Siddon_projection_parallel.cu(144): warning: variable "azm" was declared but never referenced
C:/Users/englab/Documents/GitHub/TIGRE/MATLAB/Source/Siddon_projection_parallel.cu(145): warning: variable "azM" was declared but never referenced

Error using mex
LINK : fatal error LNK1181: cannot open input file 'gpu.lib'



Error in Compile (line 111)
        mex -largeArrayDims ./Source/Ax_mex.cpp
        ./Source/ray_interpolated_projection.cu ./Source/Siddon_projection.cu
        ./Source/ray_interpolated_projection_parallel.cu
        ./Source/Siddon_projection_parallel.cu -outdir ./Mex_files/win64
 ```

**Comment by givens** [comment]
https://support.microsoft.com/en-us/help/815645/you-receive-a-fatal-error-lnk1181-error-message-when-you-build-a-manag

**Comment by givens** [comment]
These libraries from mex_CUDA_win64.xml are not found in my 'C:\Program Files\MATLAB\R2018a\extern\lib\win64\microsoft':

gpu.lib cudart.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib  ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib

Line 49:
````
         LINKLIBS="/LIBPATH:&quot;$MATLABROOT\extern\lib\$ARCH\microsoft&quot; libmx.lib libmex.lib libmat.lib gpu.lib cudart.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib  ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib"
```

**Comment by givens** [comment]
My GPU hardware may be outdated.  I ran 9.1 and 9.2 from above and obtained the same error.

````
>> d03_generateData
cudaMalloc3D error 3D tex 
Error using Ax_mex
CUDA driver version is insufficient for CUDA runtime version

Error in Ax (line 59)
projections=Ax_mex(img,geo,angles,ptype);

Error in d03_generateData (line 56)
projections=Ax(head,geo,angles,'interpolated');
````

The CUDA driver version is insufficient for CUDA runtime version.  From looking at posts, this error is about old hardware.

- [Cuda driver version is insufficient](https://devtalk.nvidia.com/default/topic/946744/cuda-setup-and-installation/cuda-driver-version-is-insufficient-/)

The computer's GPUs are GeForce 8400GS (not supported) and GeForce GTX 580 (supported).  I used 

- [Supported GeForce GPUs](https://www.geforce.com/hardware/technology/cuda/supported-gpus)

as a reference.  Since the GTX 580 is supported, I don't really expect this error, so something else could be wrong.

**Comment by AnderBiguri** [comment]
@givens  hum strange. I have not much more ideas of what could it be.  the 580 should work indeed. Have you tried using `mexcuda` instead of `mex` ? you may need another version of CUDA, but it may work.

**Comment by givens** [comment]
This is the configuration that worked:

- Windows 10
- Cuda 8.0
- Matlab 2018a

I compiled with a different computer and it worked.

The compiled software from above didn't work.  I got the same error with the newer system using a GeForce 940MX.

Thanks for all your help.
