### ISSUE TITLE
Granular Access

### ISSUE THREAD

**Issue by givens** [CERN/TIGRE#84]
## Expected Behavior

I don't think it is possible to access individual rows and columns from the A*x or AT*b code.  My wishlist behavior is this:

Granular access to Ax_mex and its adjoint

This would allow implementation of separable paraboloidal surrogates such as in this paper:

https://deepblue.lib.umich.edu/bitstream/handle/2027.42/85895/Fessler74.pdf?sequence=1&isAllowed=y

See section II first two parts for the mono-energetic algorithm.  One solves a one variable least squares for each element and can impose KT conditions. 

## Actual Behavior

Projection-based access to Ax_mex and its adjoint

## Code to reproduce the problem (If applicable)

No code

```

```

## Specifications 

  - MATLAB version: 2018a
  - OS: Windows 10
  - CUDA version: 8.0

**Comment by AnderBiguri** [comment]
@givens  Interesting. By individual rows or columns you mean you want the individual $a_{ij}$ values?

**Comment by givens** [comment]
Thanks for your response!  You answered my question.  I see how I can implement it with 1s.

**Comment by AnderBiguri** [comment]
@givens  I received an email from you that I can not reply, as it appears to be a weird email address (perhaps hidden). My response:

Hi there,

You probably pushed it to your own TIGRE fork,  https://github.com/givens/TIGRE.
I have no access to that one, neither you have access to push to  https://github.com/CERN/TIGRE
Therefore do not worry about pushing anything to the main one, as your only way of doing that is creating a pull request that I'd need to manually approve. This has not happened.

In your own repo, you can revert to previous commits if you want.

Best
