### ISSUE TITLE
Won't Compile - macOS 10.13 // MATLAB R2018a // Xcode 9.4 // CUDA 9.2

### ISSUE THREAD

**Issue by jmpearce** [CERN/TIGRE#87]
Hi,
based on my Matlab output and closed issue #57, should I download and install XCode 8.2?  Do you see any other substantive issues in the Matlab output?  Thanks in advance for any advice on this.
John

## Expected Behavior
TIGRE compilation success

## Actual Behavior
TIGRE compilation failure

Matlab output:
>> Compile
MEX configured to use 'Xcode with Clang' for C language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
 variables with more than 2^32-1 elements. You will be required
 to update your code to utilize the new API.
 You can find more information about this at:
 https://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN
Compiling TIGRE source...
This may take a couple of minutes....
compiling for mac 64
Building with 'nvcc'.
Error using mex
nvcc fatal   : The version ('9.1') of the host compiler ('Apple clang') is not supported

Error in Compile (line 126)
        mex -largeArrayDims ./Source/Ax_mex.cpp ./Source/ray_interpolated_projection.cu ./Source/Siddon_projection.cu
        ./Source/ray_interpolated_projection_parallel.cu ./Source/Siddon_projection_parallel.cu -outdir ./Mex_files/mac64

## Specifications 

  - MATLAB version: R2018a
  - OS: macOS 10.13.6
  - CUDA version: 9.2

**Comment by jmpearce** [comment]
after switching to XCode 8.2, the fatal reference to the compiler version is gone, but compilation still fails, as far as I can tell.  Here is the new Matlab output:

>> Compile
MEX configured to use 'Xcode with Clang' for C language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
	 variables with more than 2^32-1 elements. You will be required
	 to update your code to utilize the new API.
	 You can find more information about this at:
	 https://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN
Compiling TIGRE source...
This may take a couple of minutes....
compiling for mac 64
Building with 'nvcc'.
/Users/.../Documents/MATLAB/.../TIGRE-1.3.1/MATLAB/./Source/Siddon_projection_parallel.cu(144): warning: variable "azm" was declared but never referenced
/Users/.../Documents/MATLAB/.../TIGRE-1.3.1/MATLAB/./Source/Siddon_projection_parallel.cu(145): warning: variable "azM" was declared but never referenced
/Users/.../Documents/MATLAB/.../TIGRE-1.3.1/MATLAB/./Source/Siddon_projection_parallel.cu(144): warning: variable "azm" was declared but never referenced
/Users/.../Documents/MATLAB/.../TIGRE-1.3.1/MATLAB/./Source/Siddon_projection_parallel.cu(145): warning: variable "azM" was declared but never referenced
/Users/.../Documents/MATLAB/.../TIGRE-1.3.1/MATLAB/./Source/Siddon_projection_parallel.cu(144): warning: variable "azm" was declared but never referenced
/Users/.../Documents/MATLAB/.../TIGRE-1.3.1/MATLAB/./Source/Siddon_projection_parallel.cu(145): warning: variable "azM" was declared but never referenced

Error using mex
clang: warning: libstdc++ is deprecated; move to libc++
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "___cudaPopCallConfiguration", referenced from:
      interpolation_projection(float const*, Geometry, float**, float const*, int) in ray_interpolated_projection.o
      void kernelPixelDetector<false>(Geometry, float*, Point3D, Point3D, Point3D, Point3D, float, float) in ray_interpolated_projection.o
      void kernelPixelDetector<true>(Geometry, float*, Point3D, Point3D, Point3D, Point3D, float, float) in ray_interpolated_projection.o
      __device_stub__Z19kernelPixelDetector8GeometryPf7Point3DS1_S1_S1_(Geometry&, float*, Point3D&, Point3D&, Point3D&, Point3D&) in
      Siddon_projection.o
      __device_stub__Z28kernelPixelDetector_parallel8GeometryPf7Point3DS1_S1_S1_ff(Geometry&, float*, Point3D&, Point3D&, Point3D&,
      Point3D&, float, float) in ray_interpolated_projection_parallel.o
      __device_stub__Z28kernelPixelDetector_parallel8GeometryPf7Point3DS1_S1_S1_(Geometry&, float*, Point3D&, Point3D&, Point3D&, Point3D&)
      in Siddon_projection_parallel.o
  "___cudaPushCallConfiguration", referenced from:
      interpolation_projection(float const*, Geometry, float**, float const*, int) in ray_interpolated_projection.o
      siddon_ray_projection(float const*, Geometry, float**, float const*, int) in Siddon_projection.o
      interpolation_projection_parallel(float const*, Geometry, float**, float const*, int) in ray_interpolated_projection_parallel.o
      siddon_ray_projection_parallel(float const*, Geometry, float**, float const*, int) in Siddon_projection_parallel.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Error in Compile (line 126)
        mex -largeArrayDims ./Source/Ax_mex.cpp ./Source/ray_interpolated_projection.cu ./Source/Siddon_projection.cu
        ./Source/ray_interpolated_projection_parallel.cu ./Source/Siddon_projection_parallel.cu -outdir ./Mex_files/mac64

**Comment by AnderBiguri** [comment]
@jmpearce  Can you try to compile a CUDA sample, the ones that come with CUDA, without MATLAB and TIGRE?

**Comment by jmpearce** [comment]
Looks like my GPU does not qualify.  Oops.  Will have to try to find a suitably equipped Windows or Linux machine.
