### ISSUE TITLE
No supported compiler was found

### ISSUE THREAD

**Issue by mirtatae** [CERN/TIGRE#88]
Hi Ander,

Thanks for sharing this toolbox. I'm trying to compile this but I get the following error:

> Error using mex
> No supported compiler was found. For options, visit https://www.mathworks.com/support/compilers.
> 
> Error in Compile (line 110)
>         mex -largeArrayDims "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cudart.lib" ./Source/Ax_mex.cpp
>         ./Source/ray_interpolated_projection.cu ./Source/Siddon_projection.cu ./Source/ray_interpolated_projection_parallel.cu
>         ./Source/Siddon_projection_parallel.cu -outdir ./Mex_files/win64

I read your answers to other issues to see if I can fix this error but I didn't have any success. I have installed Microsoft VS 2017 and CUDA 9.2. I made the following changes accordingly:

1. In mex_CUDA_win64, I replaced all of VS120COMNTOOLS by VS170COMNTOOLS since I'm using VS 2017.
2. In mex_CUDA_win64, I also changed the CUDA version from 8.0 to 9.2 as follows:

> <config
>     Name="NVIDIA CUDA Compiler"
>     ShortName="nvcc"
>     Manufacturer="NVIDIA"
>     Version=**"9.2"**
>     Language="CUDA"
>     Priority="A"
>     Location="$NVCC" >
> 

3. In Compile.m line 110, I changed the directory from

> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\lib\x64\cudart.lib

to

> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cudart.lib

Still I get the same error. When I run getenv('CUDA_PATH'), I get:

> 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2'

and when I run mex -setup, I get:

> MEX configured to use 'Microsoft Visual C++ 2017 (C)' for C language compilation.
> Warning: The MATLAB C and Fortran API has changed to support MATLAB
> 	 variables with more than 2^32-1 elements. You will be required
> 	 to update your code to utilize the new API.
> 	 You can find more information about this at:
> 	 https://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.
> 
> To choose a different C compiler, select one from the following:
> MinGW64 Compiler (C)  mex -setup:'C:\Program Files\MATLAB\R2018a\bin\win64\mexopts\mingw64.xml' C
> Microsoft Visual C++ 2017 (C)  mex -setup:C:\Users\mirtatae\AppData\Roaming\MathWorks\MATLAB\R2018a\mex_C_win64.xml C
> 
> To choose a different language, select one from the following:
>  mex -setup C++ 
>  mex -setup FORTRAN

I used mex on a different file and it worked. So I think there is an issue with the Compile.m file.
Can you please advise how I might be able to solve this issue.

P.S.: I tried with CUDA 8.0 and I got the same error.

## Expected Behavior
I am trying to run Compile.m

## Actual Behavior
I get the error that I described above.

## Code to reproduce the problem (If applicable)

```

```

## Specifications 

  - MATLAB version: R2018a
  - OS: Windows 10
  - CUDA version: Both 8.0 and 9.2

**Comment by AnderBiguri** [comment]
hi @mirtatae , apologies for the late reply, I was om holidays.

you say you replaced the line by VS170COMNTOOLS. Are you sure you need this command? VS120COMNTOOLS is for VS2012,VS2013,VS2014 for example, the number does not necessarily relate to the version of VS. Did you just guess it or do you know this is the right thing to put there? 

Also, have you compiled some CUDA samples before triying TIGRE? can you try that to check the rest of the things are properly installed?

**Comment by mirtatae** [comment]
I tried it first with VS120COMNTOOLS, and I got the same error. Then, I just tried VS170COMNTOOLS. I just guessed it.


> Also, have you compiled some CUDA samples before triying TIGRE? can you try that to check the rest of the things are properly installed?

I haven't. Is there any specific sample/example that you can share with me and I run on my Matlab? Thanks.

**Comment by AnderBiguri** [comment]
@mirtatae  CUDA comes with some CUDAsamples. They are not MATLAB related, they are just CUDA. Try to see if your VS runs properly with CUDA by compiling those Samples, so we can pinpoint the failure point better.

**Comment by slxaso** [comment]
> hi @mirtatae , apologies for the late reply, I was om holidays.
> 
> you say you replaced the line by VS170COMNTOOLS. Are you sure you need this command? VS120COMNTOOLS is for VS2012,VS2013,VS2014 for example, the number does not necessarily relate to the version of VS. Did you just guess it or do you know this is the right thing to put there?
> 
> Also, have you compiled some CUDA samples before triying TIGRE? can you try that to check the rest of the things are properly installed?

Hi, I have exactly the same issue. My system is Win 10, Cuda v7.5 with Matlab 2016b, MVS 2013 is used as compiler. I can use mexcuda to compile the matlab provided .cu example successfully:
"mexcuda mexGPUExample.cu
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully."

But when it comes to Compile.m with mex, I have the following errors
"Error using mex
No supported compiler or SDK was found. For options, visit http://www.mathworks.com/support/compilers/R2016b/win64.html.

Error in Compile (line 49)
        mex -largeArrayDims ./Source/Ax_mex.cpp ./Source/ray_interpolated_projection.cu ./Source/Siddon_projection.cu
        ./Source/ray_interpolated_projection_parallel.cu ./Source/Siddon_projection_parallel.cu -outdir ./Mex_files/win64"

It seems no compiler is recognized at all. 
I also revised the .xml file to Cuda v7.5 as Mirtatae has done, nothing happened. I though it might be due to the nvcc is not recognized, so I tried 'system('nvcc --version')', and got

nvcc: NVIDIA (R) Cuda compiler driver 
Copyright (c) 2005-2015 NVIDIA Corporation 
Built on Tue_Aug_11_14:49:10_CDT_2015 
Cuda compilation tools, release 7.5, V7.5.17 

ans =

     0

Not sure what to check next. Cam you please provide some advice? Any idea would be appreciated!
thank,
Linxi

**Comment by slxaso** [comment]
Hi @AnderBiguri ,
Thanks a lot. I am able to compile all the functions now but the Ax_mex.cpp. Errors are given as following 
mex -largeArrayDims ./Source/Ax_mex.cpp ./Source/ray_interpolated_projection.cu ./Source/Siddon_projection.cu ./Source/ray_interpolated_projection_parallel.cu ./Source/Siddon_projection_parallel.cu -outdir ./Mex_files/win64
       
Building with 'NVIDIA CUDA Compiler'.
Error using mex
Siddon_projection.cu

H:/TIGRE-master/TIGRE-master/MATLAB/Source/Siddon_projection.cu(249): error: identifier "gpuErrchk" is undefined
H:/TIGRE-master/TIGRE-master/MATLAB/Source/Siddon_projection.cu(279): warning: variable "fits_in_memory" was set but never used
H:/TIGRE-master/TIGRE-master/MATLAB/Source/Siddon_projection.cu(384): error: identifier "Geo" is undefined
H:/TIGRE-master/TIGRE-master/MATLAB/Source/Siddon_projection.cu(405): error: identifier "checkCudaErrors" is undefined
3 errors detected in the compilation of
"C:/Users/linxit/AppData/Local/Temp/tmpxft_00004074_00000000-17_Siddon_projection.compute_52.cpp1.ii".

It seems this is only thing bugging me now. Any clues?

Thank you so much for your time.

**Comment by AnderBiguri** [comment]
Hi, redownloaded the source code and compile again, I made a mistake
fiddling with the files and added a bug.

**Comment by AnderBiguri** [comment]
@slxaso  My bad. I just updated it and tested it. I left a bugfix uncommitted. Should be working now.
