### ISSUE TITLE
wrong result on the demo file [d03_simple_image_reconstruction.ipynb]

### ISSUE THREAD

**Issue by Jarrome** [CERN/TIGRE#89]
## Expected Behavior
Skeleton

## Actual Behavior
![figure_1](https://user-images.githubusercontent.com/13412144/47027236-ac8e2b80-d199-11e8-96bb-522662eb4b68.png)

## Code to reproduce the problem (If applicable)

```
# OS_SART
niter=50
imgOSSART=OS_SART(projections,geo,angles,niter)
# FDK 
imgfdk=FDK(projections,geo,angles,filter='ram_lak')
```

## Specifications 

  - Python version: 2.7.15
  - OS: Ubuntu 16.04 LTS
  - CUDA version: 9.0.176

**Comment by AnderBiguri** [comment]
Thanks for reporting this.
@Reuben481 Will have a look at this and get back to you soon. We are currently fiddling with the python version, maybe something went wrong.

**Comment by Reuben481** [comment]
@Jarrome 
https://github.com/CERN/TIGRE/blob/df5b40a72d28cf3b75ba4f87be304b0793fe64a2/Python/python_build/setup.py#L116

https://github.com/CERN/TIGRE/blob/df5b40a72d28cf3b75ba4f87be304b0793fe64a2/Python/python_build/setup.py#L133

https://github.com/CERN/TIGRE/blob/df5b40a72d28cf3b75ba4f87be304b0793fe64a2/Python/python_build/setup.py#L148

If you change the arch-sm20 in those 3 lines to arch-sm50 and recompile does that fix the issue?

**Comment by Jarrome** [comment]
Not really...

**Comment by Reuben481** [comment]
Does it change the output at all?

**Comment by Jarrome** [comment]
No it doesn't change. Also I use plotproj to plot the projections. Projections are good.

**Comment by Reuben481** [comment]
Did you modify the loading method for the head.mat file? When i modified this i got a similar issue to you.

**Comment by Jarrome** [comment]
Because the notebook can not run well for some dynamic lib issue on _Ax. I copied the code of demo03 into a script and run. I'm not changing the code actually. :). 

It is strange because the projections looks good when I use your plotproj. (with a vmax=.1 and vmin=-.1). Also I found np.max(projections) is Nan(maybe it would help?).

**Comment by AnderBiguri** [comment]
@Jarrome  certainly that NaN is causing the problem in the reconstruction, as a single NaN can destroy the entire reconstruction. In your visualization all the black dots are likely NaN valued. It is however, very strange that you get a NaN value in the projection, this should definitely not happen. We are investigating.
Can you please give us your GPU model name too?

**Comment by Jarrome** [comment]
I use the GeForce GTX 1050

**Comment by Reuben481** [comment]
@Jarrome did you solve this issue? We have someone else getting a similar problem.

**Comment by Jarrome** [comment]
Oh, I didn't... 
I'm not familiar with cuda or cython programming, so may not be able to help, so sorry...
