### ISSUE TITLE
Spherical Backprojection will throw create warped images when Detector is not rectangular. 

### ISSUE THREAD

**Issue by reubenlindroos** [CERN/TIGRE#92]
## Expected Behavior
nDetector = (n,m) where n!=m returns clear images for a spherical projection

## Actual Behavior
returns warped images

## Code to reproduce the problem (If applicable)
geo = geometry()
geo.DSD = 1536                                     # Distance Source Detector      (mm)
geo.DSO = 1000                                     # Distance Source Origin        (mm)
# Detector parameters
geo.nDetector = np.array((128, 127))               # number of pixels              (px)
geo.dDetector = np.array((0.8, 0.8))*4               # size of each pixel            (mm)
geo.sDetector = geo.nDetector * geo.dDetector    # total size of the detector    (mm)
# Image parameters
geo.nVoxel = np.array((64, 64, 64))             # number of voxels              (vx)
geo.sVoxel = np.array((256, 256, 256))             # total size of the image       (mm)
geo.dVoxel = geo.sVoxel/geo.nVoxel               # size of each voxel            (mm)
geo.mode = 'cone'

source_img = data_loader.load_head_phantom(number_of_voxels=geo.nVoxel)
#cube =data_loader.load_cube((64,64,64))

#---------------------ANGLES--------------------------------------------

angles_1 = np.linspace(0, 2*np.pi, 100, dtype=np.float32)
angles_2 = np.ones((100),dtype=np.float32)*np.array(np.pi/4, dtype=np.float32)
angles_3 = np.zeros((100),dtype=np.float32)
angles= np.vstack((angles_1,angles_2,angles_3)).T

proj_1 = Ax(source_img,geo,angles,'ray-voxel')

#--------------------Back Projection ----------------
fbp = FDK(proj_1,geo,angles)

```

```

## Specifications 

  - MATLAB version:
  - OS:
  - CUDA version:

**Comment by AnderBiguri** [comment]
This is now fixed.
