### ISSUE TITLE
Projection not giving correct results in python

### ISSUE THREAD

**Issue by PranjalSahu** [CERN/TIGRE#93]
## Expected Behavior

![screen shot 2018-11-10 at 12 59 32 am](https://user-images.githubusercontent.com/1044135/48298029-02e24780-e484-11e8-867b-c406b7126d1e.png)

## Actual Behavior
![t1](https://user-images.githubusercontent.com/1044135/48298043-4472f280-e484-11e8-83e0-7cab6864340b.png)

## Code to reproduce the problem (If applicable)

The code is sample d03_simple_image_reconstruction.ipynb in Python examples.
```

```

## Specifications 

  - MATLAB version:
  - OS: Ubuntu 16.04
  - CUDA version: 7.5

**Comment by AnderBiguri** [comment]
@PranjalSahu  Thanks for reporting this. Can I ask which GPU are you using?

**Comment by PranjalSahu** [comment]
I am using Titan Xp GPU.
The code is working fine on MATLAB but in Python it is not working.

**Comment by Reuben481** [comment]
@PranjalSahu Are you using the latest version of TIGRE on the github? 

If your using the conda install version of tigre, that is not the newest version. Also if you are using the conda install version of cudatoolkit this has caused issues in the past.

**Comment by PranjalSahu** [comment]
@Reuben481 I installed it from the source, however I used the cudatoolkit which comes with the conda installation. Which cuda version would you recommend?

**Comment by AnderBiguri** [comment]
@PranjalSahu  The conda isntallation of python-TIGRE has just been deprecated for a simpler compilation and dependencies method. This as you see, also allows for newer CUDA installations. Changing from 7.5 8 gave me 20% of speedup few years ago, I do not have the numbers now but I suspect you will see similar improvements, and we are now in CUDA 10! I suggest you get 9.2 or newer, preferably the latest one.  In fact your GPU did not exist when CUDA 7.5 was out, so I'd not trust any compilation with older CUDAs.

**Comment by Reuben481** [comment]
the cudatoolkit that comes with conda is quite limited so we recommend not using that. To make sure you have the latest version of TIGRE i would recommend you download straight from the github, as in:
`git clone https://github.com/CERN/TIGRE.git`
then install directrly from there:
`cd TIGRE/Python`
`python setup.py install`
And then try and run the demo files from the tigre_demo_file in the repo.

**Comment by PranjalSahu** [comment]
@Reuben481 I am using MATLAB with the same OS. I will re install the python implementation and compile it with an updated version of cudatoolkit.

**Comment by AnderBiguri** [comment]
@PranjalSahu I am closing this issue as I have not seen it reproduced and we have no way of reproducing it. Let me know if you have any issue!
