### ISSUE TITLE
Introduction of DSD variable not correct

### ISSUE THREAD

**Issue by PranjalSahu** [CERN/TIGRE#94]
## Expected Behavior
Sample code should execute without any error.

## Actual Behavior
![error1](https://user-images.githubusercontent.com/1044135/48307229-5d2be880-e516-11e8-87fd-cfa1926fd6ad.png)

## Code to reproduce the problem (If applicable)
Run codes where the variable DSD variable was introduced for example SART_TV, ASD_POCS etc.
```

```

## Specifications 

  - MATLAB version:
  - OS:
  - CUDA version:

**Comment by AnderBiguri** [comment]
@PranjalSahu  Thanks, this should be fixed now.
