### ISSUE TITLE
Is this support flying focal spot case? (is there rebinning process)

### ISSUE THREAD

**Issue by AceCoooool** [CERN/TIGRE#96]
As title.

**Comment by AnderBiguri** [comment]
Hi, I'm not 100% sure I know what you mean. Is the question related to
photon physics simulation? If that's the case, the answer is no, there is
no focal spot or rebinning. TIGRE is not designed to simulate realistic
X-rays, but recosntruction, thus the projection is always monochromatic,
infinitesimal width rays. You can simulate your projections in TIGRE but
they will just be ideal projections.
Ander

**Comment by AnderBiguri** [comment]
@AceCoooool  I am closing this issue as I havent heard anything from you. Let me know if you think it needs reopening.
