### ISSUE TITLE
Using the DBT example, the reconstructed volume gets shifted for each slice

### ISSUE THREAD

**Issue by PranjalSahu** [CERN/TIGRE#99]
## Expected Behavior
In the reconstructed volume slices should all be at same height.

## Actual Behavior
However, as the angle increases the volume slices are getting shifted upward.
It might be because of the way static Detector functionality is handled.

As shown in the recontructed volume the slices are moving slightly upwards as we scroll though the reconstructed slices.
![final](https://user-images.githubusercontent.com/1044135/49245167-8df99200-f3df-11e8-9c7b-3fcdf9947ec0.PNG)

## Code to reproduce the problem (If applicable)

Using the staticDetectorGeo where the detector is fixed for use cases such as Digital Breast Tomosynthesis.

This behaviour is produced if the projections are taken using areal DBT system such as Siemens Inspiration.
If the projections are taken using TIGRE's projector then this problem does not occur.

There is some issue with the static detector functionality which I have not been able to solve.

**_Could someone please help me understand why is this happening ?_**

The geometry of a DBT system is shown as below for reference.
![siemens1](https://user-images.githubusercontent.com/1044135/49245342-0c563400-f3e0-11e8-883d-bc724a07a123.png)

## Specifications 

  - MATLAB version:
  - OS:
  - CUDA version:

**Comment by AnderBiguri** [comment]
Hi,
I will have a further look at this as soon as I can
Ander

**Comment by AnderBiguri** [comment]
Hi @PranjalSahu ,

Could you share with me the geometry definition so I can have a further look?

**Comment by PranjalSahu** [comment]
Hello @AnderBiguri 

Following is the geometry definition I am using which is same as Siemens Mammomat Inspiration DBT system.


```
geo.DSD = 655;                             % Distance Source Detector      (mm)
geo.DSO = 608;                             % Distance Source Origin        (mm)

% Detector parameters
geo.nDetector = [3584;  1800];					    % number of pixels              (px)
geo.dDetector = [0.085; 0.085]; 					% size of each pixel            (mm)
geo.sDetector = geo.nDetector.*geo.dDetector;       % total size of the detector    (mm)

% Image parameters
geo.nVoxel = [50; 2400; 1100];                % number of voxels              (vx)
geo.dVoxel = [1 ; 0.085; 0.085];               % size of each voxel            (mm)
geo.sVoxel = geo.nVoxel.*geo.dVoxel;          % total size of the image       (mm)

% Offsets
Airgap                = 17;
geo.offOrigin     = [((geo.sVoxel(1)/2)-(geo.DSD-geo.DSO)+Airgap); 0; geo.sVoxel(3)/2];
geo.offDetector = [0; geo.sDetector(2)/2];    % Offset of Detector            (mm)

% Auxiliary 
geo.COR=0; 
geo.accuracy     = 0.1;                           % Accuracy of FWD proj          (vx/sample)
geo.mode          = 'cone';
geo.rotDetector = [0;0;0]; 

tubeangle = 50;
nprojs    = 25;
angles    = deg2rad(linspace(-tubeangle/2,tubeangle/2,nprojs));
```


<br>
<br>
<br>


**The staticDetectorGeo.m function which I am using is as below:**

```
function geo=staticDetectorGeo(geo,angles)
% This fucntion computes the translation and rotations needed in the system
% to desribe a detector that does not move when the source moves.

R=(geo.DSD-geo.DSO); %Radious of rotation of detector
R_prime = geo.DSD-R;
geo.DSD = geo.DSD-(R - R*cos(angles));
geo.offDetector=[R*sin(angles); ones(1, size(angles, 2))*20];

% Here, Ideally the offDetector should be ones(1, size(angles, 2))*geo.sDetector(2)/2  
% since it is an half-cone beam geometry, however this does not works for me 
% therefore by hit and trial I obtained the above value of 20.

geo.rotDetector=[zeros(1,size(angles,2));  zeros(1,size(angles,2));  -angles];
```



<br>
<br>
<br>


I am also sharing some sample phantoms projections obtained using the Original DBT system for reproducing the above issue. As I mentioned before if the projections are taken using the TIGRE's projector then this issue does not happens. However, if projections from real DBT system are used then this vertical shift in slices occurs.

**The google drive link for the projections. There are in total 25 projections.**
[https://drive.google.com/drive/folders/13QjN23oWdz6CIRnbgaPLFKT0jjRpx2PY?usp=sharing](url)


<br>
<br>

**And the code to read the projections is as follows:**
```
noise_projections = zeros(1800, 3584, 25, 'double');
files = dir('C:\Users\psahu\TESTBED\projections\Noise\72_80\Projections_Renamed_Seg');
for t=3:27
  disp(strcat(files(t).folder, '\', files(t).name))
  fid = fopen(strcat(files(t).folder, '/', files(t).name), 'r');
  c   = fread(fid, 3584*1800, 'float');
  cb  = reshape(c, [3584, 1800]);
  cb = cb';
  noise_projections(:, :, t-2) = cb;
end

noise_projections = single(noise_projections);
```


**And the code to save the reconstructed volume is below:**
```
temp = zeros(2400, 1100, 50, 'double');
for t=1:50
    temp(:, :, t) = recSART(t, :, :);
end

fid = fopen('vol31_2400x1100_50.raw','w+');
cnt = fwrite(fid, temp, 'float');
fclose(fid);

```
You can use ImageJ software to view the recontructed volume slice by slice where the probloem of vertical shift will be visible. In my system while viewing the volume in ImageJ  I use 32-bit real as image type and little endian byte order, width=2400, height=1100 and number of images=50.

<br>
<br>
<br>

Please let me know if anything else is needed.
Thank You.

**Comment by AnderBiguri** [comment]
@PranjalSahu  Thanks, I will try to run it myself. 

Right now the biggest possible cause of your error is that geo.offOrigin(3) and geo.offDetector(2). The visual effect seen in the reconstructed image can be explained by having the detector "too high" in the TIGRE's z direction,  therefore missing part of the image.  Check that. 

Otherwise I will have a further look when I have a better computer at hand (I am away currently, possibly won't have one until Monday).

**Comment by AnderBiguri** [comment]
@PranjalSahu  yes indeed. I was just wondering if you were visualizing the reconstruction upside down and in fact that lower dark gap is in fact the upper part. I will look into it further next week.

**Comment by PranjalSahu** [comment]
Hello @AnderBiguri , You were right. The projections were inverted.
I inverted the projections and changed the offset height and now the reconstructed volume is perfectly aligned. Thank you very much for the help. I am closing the issue.

**Comment by rodrigovimieiro** [comment]
> Hello @AnderBiguri , You were right. The projections were inverted.
> I inverted the projections and changed the offset height and now the reconstructed volume is perfectly aligned. Thank you very much for the help. I am closing the issue.

Just for reference, for people that might reach this post, probably this line might solve your problem:

`projections = rot90(permute(projections,[2 1 3]),2);`

There is a DBT Demo [here](https://github.com/CERN/TIGRE/blob/master/MATLAB/Demos/d19_DBTexample.m) at TIGRE in this directory.
